-- Generated by scripts/export-sql.ts — paste into the Supabase SQL editor.
-- image is left NULL on purpose: attach the photo later from the admin panel
-- (the site shows a category placeholder cover until then).

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('kurinye-oladi-s-kabachkom', 'main', true, null, 40, 190, 4, 'easy',
   '{"ru":"Сочные куриные оладьи с кабачком и сыром","en":"Juicy chicken & zucchini patties"}'::jsonb,
   '{"ru":"Нежные ПП-оладьи из куриного фарша и кабачка, запечённые в духовке без капли масла. Сочные внутри, румяные сверху — идеальный лёгкий ужин.","en":"Tender healthy patties of chicken mince and zucchini, oven-baked without a drop of oil. Juicy inside, golden on top — the perfect light dinner."}'::jsonb,
   '{"ru":["Куриный фарш — 500 г","Кабачок — 1 средний (~250–300 г)","Яйцо — 1 шт","Твёрдый сыр — 80–100 г","Мука — 2 ст. л.","Паприка — 1 ч. л.","Соль — по вкусу","Чёрный молотый перец — по вкусу","Для подачи: огурец — 1 шт, помидоры — 2 шт, укроп — небольшой пучок"],"en":["Chicken mince — 500 g","Zucchini — 1 medium (~250–300 g)","Egg — 1","Hard cheese — 80–100 g","Flour — 2 tbsp","Paprika — 1 tsp","Salt — to taste","Black pepper — to taste","To serve: cucumber — 1, tomatoes — 2, dill — a small bunch"]}'::jsonb,
   '{"ru":["Кабачок натрите на крупной тёрке и слегка отожмите лишнюю влагу.","Смешайте куриный фарш, кабачок, яйцо, тёртый сыр, муку, паприку, соль и перец.","Хорошо перемешайте до однородного вязкого фарша.","Выкладывайте ложкой на противень с пергаментом, формируя оладьи.","Запекайте 20–25 минут при 180 °C до румяной корочки.","Подавайте горячими с салатом из огурца, помидоров и укропа."],"en":["Grate the zucchini coarsely and squeeze out the excess moisture.","Combine the chicken mince, zucchini, egg, grated cheese, flour, paprika, salt and pepper.","Mix well into a smooth, sticky mixture.","Spoon onto a parchment-lined tray, shaping patties.","Bake for 20–25 minutes at 180 °C until golden.","Serve hot with a cucumber, tomato and dill salad."]}'::jsonb,
   '{"ru":["ПП","ужин","курица","кабачок"],"en":["healthy","dinner","chicken","zucchini"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

