-- Generated by scripts/export-sql.ts — paste into the Supabase SQL editor.
-- image is left NULL on purpose: attach the photo later from the admin panel
-- (the site shows a category placeholder cover until then).

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('shokoladnyy-fondan', 'dessert', false, null, 20, 380, 4, 'medium',
   '{"ru":"Шоколадный фондан с жидким центром","en":"Chocolate fondant with a molten centre","ua":"Шоколадний фондан із рідким центром"}'::jsonb,
   '{"ru":"Маленькие шоколадные кексы с горячей тягучей серединкой, которая вытекает при разломе. Секрет — не передержать в духовке: снаружи корочка, внутри жидкий шоколад.","en":"Little chocolate cakes with a hot, gooey centre that flows out when you break them open. The secret is not to overbake — a set crust outside, molten chocolate within.","ua":"Маленькі шоколадні кекси з гарячою тягучою серединкою, що витікає при розломі. Секрет — не перетримати в духовці: зовні скоринка, всередині рідкий шоколад."}'::jsonb,
   '{"ru":["Тёмный шоколад — 100 г","Сливочное масло — 100 г","Яйца — 2 шт.","Сахар — 60 г","Мука — 40 г","Щепотка соли"],"en":["Dark chocolate — 100 g","Butter — 100 g","Eggs — 2","Sugar — 60 g","Flour — 40 g","A pinch of salt"],"ua":["Чорний шоколад — 100 г","Вершкове масло — 100 г","Яйця — 2 шт.","Цукор — 60 г","Борошно — 40 г","Дрібка солі"]}'::jsonb,
   '{"ru":["Растопите шоколад со сливочным маслом на водяной бане.","Взбейте яйца с сахаром до пышности и соедините с шоколадом.","Аккуратно вмешайте муку и соль до однородности.","Разлейте по смазанным формочкам и выпекайте при 200 °C 9–11 минут.","Совет: центр должен остаться подвижным — тогда фондан вытечет при разломе."],"en":["Melt the chocolate with the butter over a water bath.","Whisk the eggs with the sugar until fluffy and fold into the chocolate.","Gently stir in the flour and salt until smooth.","Pour into greased ramekins and bake at 200 °C for 9–11 minutes.","Tip: the centre should still wobble — that''s what makes it flow."],"ua":["Розтопіть шоколад із вершковим маслом на водяній бані.","Збийте яйця з цукром до пишності й з''єднайте з шоколадом.","Обережно вмішайте борошно й сіль до однорідності.","Розлийте по змащених формочках і випікайте за 200 °C 9–11 хвилин.","Порада: центр має лишитися рухливим — тоді фондан витече при розломі."]}'::jsonb,
   '{"ru":["десерт","шоколад","выпечка"],"en":["dessert","chocolate","baking"],"ua":["десерт","шоколад","випічка"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('chizkeyk-bez-vypechki', 'dessert', false, null, 30, 340, 8, 'easy',
   '{"ru":"Чизкейк без выпечки","en":"No-bake cheesecake","ua":"Чизкейк без випікання"}'::jsonb,
   '{"ru":"Нежный сливочный чизкейк на песочной основе, который застывает в холодильнике — духовка не нужна. Готовится просто, а получается как из кондитерской.","en":"A silky cream-cheese cheesecake on a biscuit base that sets in the fridge — no oven needed. Simple to make, yet it tastes like it''s from a patisserie.","ua":"Ніжний вершковий чизкейк на пісочній основі, що застигає в холодильнику — духовка не потрібна. Готується просто, а виходить як із кондитерської."}'::jsonb,
   '{"ru":["Печенье песочное — 200 г","Сливочное масло — 90 г","Сливочный сыр — 400 г","Сливки 33% — 200 мл","Сахарная пудра — 80 г","Ванильный экстракт — 1 ч. л.","Желатин — 10 г"],"en":["Shortbread biscuits — 200 g","Butter — 90 g","Cream cheese — 400 g","Cream 33% — 200 ml","Icing sugar — 80 g","Vanilla extract — 1 tsp","Gelatin — 10 g"],"ua":["Пісочне печиво — 200 г","Вершкове масло — 90 г","Вершковий сир — 400 г","Вершки 33% — 200 мл","Цукрова пудра — 80 г","Ванільний екстракт — 1 ч. л.","Желатин — 10 г"]}'::jsonb,
   '{"ru":["Измельчите печенье, смешайте с растопленным маслом и утрамбуйте в форму.","Замочите желатин по инструкции и распустите, не кипятя.","Взбейте сливочный сыр с пудрой и ванилью, влейте желатин.","Отдельно взбейте сливки и аккуратно соедините с сырной массой.","Вылейте на основу и уберите в холодильник на 4 часа до застывания."],"en":["Crush the biscuits, mix with melted butter and press into a tin.","Soak the gelatin per the pack and dissolve it without boiling.","Beat the cream cheese with icing sugar and vanilla, then add the gelatin.","Whip the cream separately and fold gently into the cheese mixture.","Pour onto the base and chill for 4 hours until set."],"ua":["Подрібніть печиво, змішайте з розтопленим маслом і утрамбуйте у форму.","Замочіть желатин за інструкцією та розпустіть, не кип''ятячи.","Збийте вершковий сир із пудрою й ваніллю, влийте желатин.","Окремо збийте вершки й обережно з''єднайте із сирною масою.","Вилийте на основу й приберіть у холодильник на 4 години до застигання."]}'::jsonb,
   '{"ru":["десерт","чизкейк","без выпечки"],"en":["dessert","cheesecake","no-bake"],"ua":["десерт","чизкейк","без випікання"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('tiramisu-klassicheskiy', 'dessert', false, null, 30, 360, 6, 'medium',
   '{"ru":"Классический тирамису","en":"Classic tiramisu","ua":"Класичний тірамісу"}'::jsonb,
   '{"ru":"Итальянский десерт из печенья савоярди, пропитанного кофе, и воздушного крема на маскарпоне. Тает во рту, а сверху — щедрый слой какао.","en":"The Italian dessert of coffee-soaked savoiardi and an airy mascarpone cream. It melts in the mouth, under a generous dusting of cocoa.","ua":"Італійський десерт із печива савоярді, просоченого кавою, та повітряного крему на маскарпоне. Тане в роті, а зверху — щедрий шар какао."}'::jsonb,
   '{"ru":["Печенье савоярди — 200 г","Маскарпоне — 400 г","Яйца — 3 шт.","Сахар — 80 г","Крепкий кофе — 250 мл","Какао — для посыпки"],"en":["Savoiardi biscuits — 200 g","Mascarpone — 400 g","Eggs — 3","Sugar — 80 g","Strong coffee — 250 ml","Cocoa — for dusting"],"ua":["Печиво савоярді — 200 г","Маскарпоне — 400 г","Яйця — 3 шт.","Цукор — 80 г","Міцна кава — 250 мл","Какао — для посипання"]}'::jsonb,
   '{"ru":["Взбейте желтки с сахаром добела, вмешайте маскарпоне.","Отдельно взбейте белки до устойчивых пиков и аккуратно введите в крем.","Быстро обмакивайте савоярди в остывший кофе и выкладывайте слоем.","Покройте кремом, повторите слои и уберите в холодильник на 4–6 часов.","Перед подачей щедро посыпьте какао через сито."],"en":["Beat the yolks with sugar until pale, then stir in the mascarpone.","Whip the whites to stiff peaks and fold gently into the cream.","Quickly dip the savoiardi in cooled coffee and lay out a layer.","Cover with cream, repeat the layers and chill for 4–6 hours.","Before serving, dust generously with cocoa through a sieve."],"ua":["Збийте жовтки з цукром добіла, вмішайте маскарпоне.","Окремо збийте білки до стійких піків і обережно введіть у крем.","Швидко вмочайте савоярді в охолоджену каву й викладайте шаром.","Покрийте кремом, повторіть шари й приберіть у холодильник на 4–6 годин.","Перед подачею щедро посипте какао через сито."]}'::jsonb,
   '{"ru":["десерт","тирамису","кофе"],"en":["dessert","tiramisu","coffee"],"ua":["десерт","тірамісу","кава"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('ovsyanoe-pechenye', 'dessert', true, null, 25, 190, 6, 'easy',
   '{"ru":"Овсяное печенье без сахара","en":"Sugar-free oatmeal cookies","ua":"Вівсяне печиво без цукру"}'::jsonb,
   '{"ru":"Мягкое овсяное печенье на банане, без сахара и муки — полезный перекус к чаю. Готовится в одной миске за пять минут и печётся, пока закипает чайник.","en":"Soft banana oatmeal cookies with no sugar or flour — a wholesome snack with tea. One bowl, five minutes, and they bake while the kettle boils.","ua":"М''яке вівсяне печиво на банані, без цукру та борошна — корисний перекус до чаю. Готується в одній мисці за п''ять хвилин і печеться, поки закипає чайник."}'::jsonb,
   '{"ru":["Овсяные хлопья — 150 г","Банан спелый — 2 шт.","Изюм — 50 г","Орехи — 40 г","Корица — 0,5 ч. л.","Щепотка соли"],"en":["Rolled oats — 150 g","Ripe bananas — 2","Raisins — 50 g","Nuts — 40 g","Cinnamon — 0.5 tsp","A pinch of salt"],"ua":["Вівсяні пластівці — 150 г","Стиглий банан — 2 шт.","Родзинки — 50 г","Горіхи — 40 г","Кориця — 0,5 ч. л.","Дрібка солі"]}'::jsonb,
   '{"ru":["Разомните бананы вилкой в пюре.","Смешайте с хлопьями, изюмом, орехами, корицей и солью.","Дайте массе постоять 10 минут, чтобы хлопья набухли.","Выкладывайте ложкой на пергамент, формируя печенье.","Выпекайте при 180 °C 15–18 минут до румяности."],"en":["Mash the bananas with a fork into a purée.","Mix with the oats, raisins, nuts, cinnamon and salt.","Let the mixture rest 10 minutes so the oats swell.","Spoon onto parchment, shaping into cookies.","Bake at 180 °C for 15–18 minutes until golden."],"ua":["Розімніть банани виделкою в пюре.","Змішайте з пластівцями, родзинками, горіхами, корицею й сіллю.","Дайте масі постояти 10 хвилин, щоб пластівці набубнявіли.","Викладайте ложкою на пергамент, формуючи печиво.","Випікайте за 180 °C 15–18 хвилин до рум''яності."]}'::jsonb,
   '{"ru":["ПП","десерт","печенье","без сахара"],"en":["healthy","dessert","cookies","sugar-free"],"ua":["ПХ","десерт","печиво","без цукру"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('bananovyy-hleb', 'baking', false, null, 60, 280, 8, 'easy',
   '{"ru":"Банановый хлеб","en":"Banana bread","ua":"Банановий хліб"}'::jsonb,
   '{"ru":"Влажный ароматный кекс на спелых бананах — отличный способ пристроить потемневшие бананы. Простое тесто в одной миске и потрясающий аромат на всю кухню.","en":"A moist, fragrant loaf made with ripe bananas — the best way to use up ones that have gone brown. One-bowl batter and an aroma that fills the kitchen.","ua":"Вологий ароматний кекс на стиглих бананах — чудовий спосіб прилаштувати потемнілі банани. Просте тісто в одній мисці й приголомшливий аромат на всю кухню."}'::jsonb,
   '{"ru":["Банан спелый — 3 шт.","Мука — 200 г","Сахар — 100 г","Яйца — 2 шт.","Сливочное масло — 80 г","Разрыхлитель — 1 ч. л.","Щепотка соли","Грецкие орехи — 50 г"],"en":["Ripe bananas — 3","Flour — 200 g","Sugar — 100 g","Eggs — 2","Butter — 80 g","Baking powder — 1 tsp","A pinch of salt","Walnuts — 50 g"],"ua":["Стиглий банан — 3 шт.","Борошно — 200 г","Цукор — 100 г","Яйця — 2 шт.","Вершкове масло — 80 г","Розпушувач — 1 ч. л.","Дрібка солі","Волоські горіхи — 50 г"]}'::jsonb,
   '{"ru":["Разомните бананы, добавьте растопленное масло, сахар и яйца.","Всыпьте муку с разрыхлителем и солью, перемешайте до однородности.","Вмешайте рубленые орехи.","Вылейте тесто в форму для кекса, застеленную пергаментом.","Выпекайте при 175 °C около 45–50 минут до сухой шпажки."],"en":["Mash the bananas, add melted butter, sugar and eggs.","Stir in the flour with baking powder and salt until smooth.","Fold in the chopped walnuts.","Pour the batter into a parchment-lined loaf tin.","Bake at 175 °C for about 45–50 minutes until a skewer comes out clean."],"ua":["Розімніть банани, додайте розтоплене масло, цукор і яйця.","Всипте борошно з розпушувачем і сіллю, перемішайте до однорідності.","Вмішайте порубані горіхи.","Вилийте тісто у форму для кексу, застелену пергаментом.","Випікайте за 175 °C близько 45–50 хвилин до сухої шпажки."]}'::jsonb,
   '{"ru":["выпечка","банан","кекс"],"en":["baking","banana","loaf"],"ua":["випічка","банан","кекс"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('tvorozhnaya-zapekanka', 'dessert', true, null, 50, 200, 6, 'easy',
   '{"ru":"Творожная запеканка как в детстве","en":"Cottage-cheese bake","ua":"Сирна запіканка як у дитинстві"}'::jsonb,
   '{"ru":"Нежная творожная запеканка с ванилью — пышная, воздушная и не резиновая. Отличный ПП-завтрак или десерт с ложкой сметаны или ягод.","en":"A tender vanilla cottage-cheese bake — fluffy, airy and never rubbery. A great healthy breakfast or dessert with a spoon of sour cream or berries.","ua":"Ніжна сирна запіканка з ваніллю — пишна, повітряна й не гумова. Чудовий ПХ-сніданок або десерт із ложкою сметани чи ягодами."}'::jsonb,
   '{"ru":["Творог — 500 г","Яйца — 3 шт.","Манная крупа — 3 ст. л.","Сахар — 60 г","Сметана — 2 ст. л.","Ванильный сахар — 1 ч. л.","Щепотка соли"],"en":["Cottage cheese — 500 g","Eggs — 3","Semolina — 3 tbsp","Sugar — 60 g","Sour cream — 2 tbsp","Vanilla sugar — 1 tsp","A pinch of salt"],"ua":["Сир кисломолочний — 500 г","Яйця — 3 шт.","Манна крупа — 3 ст. л.","Цукор — 60 г","Сметана — 2 ст. л.","Ванільний цукор — 1 ч. л.","Дрібка солі"]}'::jsonb,
   '{"ru":["Разотрите творог с желтками, сахаром, сметаной и манкой.","Дайте массе постоять 15 минут, чтобы манка набухла.","Взбейте белки со щепоткой соли до пиков и аккуратно вмешайте.","Выложите в смазанную форму и разровняйте.","Выпекайте при 180 °C 35–40 минут; дайте остыть в форме, чтобы не осела."],"en":["Blend the cottage cheese with yolks, sugar, sour cream and semolina.","Let it rest 15 minutes so the semolina swells.","Whip the whites with a pinch of salt to peaks and fold in gently.","Spread into a greased dish and level the top.","Bake at 180 °C for 35–40 minutes; cool in the dish so it doesn''t sink."],"ua":["Розітріть сир із жовтками, цукром, сметаною й манкою.","Дайте масі постояти 15 хвилин, щоб манка набубнявіла.","Збийте білки з дрібкою солі до піків і обережно вмішайте.","Викладіть у змащену форму й розрівняйте.","Випікайте за 180 °C 35–40 хвилин; дайте охолонути у формі, щоб не осіла."]}'::jsonb,
   '{"ru":["ПП","десерт","творог","завтрак"],"en":["healthy","dessert","cottage cheese","breakfast"],"ua":["ПХ","десерт","сир","сніданок"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('sharlotka-s-yablokami', 'baking', false, null, 55, 240, 8, 'easy',
   '{"ru":"Шарлотка с яблоками","en":"Apple charlotte sponge","ua":"Шарлотка з яблуками"}'::jsonb,
   '{"ru":"Пышный бисквит с сочными яблоками — самый простой яблочный пирог, который получается всегда. Всего пять продуктов и никакого миксера-виртуоза.","en":"An airy sponge packed with juicy apples — the simplest apple cake that always works. Just five ingredients and no fancy mixer needed.","ua":"Пишний бісквіт із соковитими яблуками — найпростіший яблучний пиріг, що виходить завжди. Лише п''ять продуктів і жодного міксера-віртуоза."}'::jsonb,
   '{"ru":["Яблоки — 4 шт.","Яйца — 4 шт.","Сахар — 180 г","Мука — 180 г","Ванильный сахар — 1 ч. л.","Щепотка соли"],"en":["Apples — 4","Eggs — 4","Sugar — 180 g","Flour — 180 g","Vanilla sugar — 1 tsp","A pinch of salt"],"ua":["Яблука — 4 шт.","Яйця — 4 шт.","Цукор — 180 г","Борошно — 180 г","Ванільний цукор — 1 ч. л.","Дрібка солі"]}'::jsonb,
   '{"ru":["Взбейте яйца с сахаром и солью до пышной светлой массы 5–7 минут.","Аккуратно вмешайте просеянную муку, сохраняя воздушность.","Нарежьте яблоки дольками и выложите в форму.","Залейте тестом и распределите равномерно.","Выпекайте при 180 °C 35–40 минут до сухой шпажки; не открывайте духовку первые 25 минут."],"en":["Whip the eggs with sugar and salt to a pale, fluffy mass for 5–7 minutes.","Gently fold in the sifted flour, keeping the air in.","Slice the apples and arrange in the tin.","Pour over the batter and spread evenly.","Bake at 180 °C for 35–40 minutes until a skewer is clean; don''t open the oven for the first 25 minutes."],"ua":["Збийте яйця з цукром і сіллю до пишної світлої маси 5–7 хвилин.","Обережно вмішайте просіяне борошно, зберігаючи повітряність.","Наріжте яблука дольками й викладіть у форму.","Залийте тістом і розподіліть рівномірно.","Випікайте за 180 °C 35–40 хвилин до сухої шпажки; не відкривайте духовку перші 25 хвилин."]}'::jsonb,
   '{"ru":["выпечка","яблоки","пирог"],"en":["baking","apples","cake"],"ua":["випічка","яблука","пиріг"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('shokoladnyy-brauni', 'baking', false, null, 40, 320, 9, 'easy',
   '{"ru":"Шоколадный брауни","en":"Fudgy chocolate brownies","ua":"Шоколадний брауні"}'::jsonb,
   '{"ru":"Плотный влажный брауни с блестящей корочкой и насыщенным вкусом шоколада. Внутри — тягучая помадка, а не сухой бисквит. Идеально с шариком мороженого.","en":"Dense, fudgy brownies with a shiny crust and deep chocolate flavour. Gooey inside, not a dry sponge. Perfect with a scoop of ice cream.","ua":"Щільний вологий брауні з блискучою скоринкою та насиченим смаком шоколаду. Усередині — тягуча помадка, а не сухий бісквіт. Ідеально з кулькою морозива."}'::jsonb,
   '{"ru":["Тёмный шоколад — 150 г","Сливочное масло — 120 г","Сахар — 150 г","Яйца — 3 шт.","Мука — 90 г","Какао — 20 г","Щепотка соли"],"en":["Dark chocolate — 150 g","Butter — 120 g","Sugar — 150 g","Eggs — 3","Flour — 90 g","Cocoa — 20 g","A pinch of salt"],"ua":["Чорний шоколад — 150 г","Вершкове масло — 120 г","Цукор — 150 г","Яйця — 3 шт.","Борошно — 90 г","Какао — 20 г","Дрібка солі"]}'::jsonb,
   '{"ru":["Растопите шоколад с маслом и слегка остудите.","Взбейте яйца с сахаром до светлой пышной массы.","Соедините с шоколадом, затем вмешайте муку, какао и соль.","Вылейте в квадратную форму с пергаментом.","Выпекайте при 175 °C 22–25 минут — центр должен остаться чуть влажным."],"en":["Melt the chocolate with butter and cool slightly.","Whisk the eggs with sugar to a pale, fluffy mass.","Combine with the chocolate, then stir in flour, cocoa and salt.","Pour into a parchment-lined square tin.","Bake at 175 °C for 22–25 minutes — the centre should stay a little moist."],"ua":["Розтопіть шоколад із маслом і трохи остудіть.","Збийте яйця з цукром до світлої пишної маси.","З''єднайте з шоколадом, потім вмішайте борошно, какао й сіль.","Вилийте у квадратну форму з пергаментом.","Випікайте за 175 °C 22–25 хвилин — центр має лишитися трохи вологим."]}'::jsonb,
   '{"ru":["выпечка","шоколад","брауни"],"en":["baking","chocolate","brownies"],"ua":["випічка","шоколад","брауні"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

