npm warn exec The following package was not found and will be installed: tsx@4.23.15
-- Generated by scripts/export-sql.ts — paste into the Supabase SQL editor.
-- image is left NULL on purpose: attach the photo later from the admin panel
-- (the site shows a category placeholder cover until then).

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('kurinoe-file-v-slivochno-chesnochnom-souse', 'main', false, null, 25, 320, 3, 'easy',
   '{"ru":"Куриное филе в сливочно-чесночном соусе","en":"Chicken breast in creamy garlic sauce","ua":"Куряче філе у вершково-часниковому соусі"}'::jsonb,
   '{"ru":"Нежное куриное филе в бархатистом сливочном соусе с чесноком и зеленью. Соус получается насыщенным, но лёгким — идеально с пастой, рисом или картофельным пюре.","en":"Tender chicken breast in a velvety cream sauce with garlic and herbs. The sauce is rich yet light — perfect over pasta, rice or mashed potatoes.","ua":"Ніжне куряче філе в оксамитовому вершковому соусі з часником і зеленню. Соус насичений, але легкий — ідеально з пастою, рисом чи картопляним пюре."}'::jsonb,
   '{"ru":["Куриное филе — 500 г","Сливки 20% — 200 мл","Чеснок — 3 зубчика","Сливочное масло — 20 г","Твёрдый сыр — 40 г","Петрушка — небольшой пучок","Соль — по вкусу","Чёрный перец — по вкусу"],"en":["Chicken breast — 500 g","Cream 20% — 200 ml","Garlic — 3 cloves","Butter — 20 g","Hard cheese — 40 g","Parsley — a small bunch","Salt — to taste","Black pepper — to taste"],"ua":["Куряче філе — 500 г","Вершки 20% — 200 мл","Часник — 3 зубчики","Вершкове масло — 20 г","Твердий сир — 40 г","Петрушка — невеликий пучок","Сіль — до смаку","Чорний перець — до смаку"]}'::jsonb,
   '{"ru":["Нарежьте филе на порционные кусочки, посолите и поперчите.","Обжарьте курицу на сливочном масле до румяности с обеих сторон.","Добавьте измельчённый чеснок, через минуту влейте сливки.","Всыпьте тёртый сыр и прогрейте соус до загустения.","Посыпьте петрушкой и подавайте. Совет: не кипятите сливки сильно, иначе соус расслоится."],"en":["Cut the fillet into portions and season with salt and pepper.","Sear the chicken in butter until golden on both sides.","Add minced garlic, then pour in the cream after a minute.","Stir in grated cheese and simmer until the sauce thickens.","Scatter with parsley and serve. Tip: don''t boil the cream hard or the sauce splits."],"ua":["Наріжте філе на порційні шматочки, посоліть і поперчіть.","Обсмажте курку на вершковому маслі до рум''яності з обох боків.","Додайте подрібнений часник, за хвилину влийте вершки.","Всипте тертий сир і прогрійте соус до загустіння.","Посипте петрушкою й подавайте. Порада: не кип''ятіть вершки сильно, інакше соус розшарується."]}'::jsonb,
   '{"ru":["ужин","курица","сливки","быстро"],"en":["dinner","chicken","cream","quick"],"ua":["вечеря","курка","вершки","швидко"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('kuritsa-teriyaki', 'main', false, null, 20, 340, 3, 'easy',
   '{"ru":"Курица терияки с рисом","en":"Teriyaki chicken with rice","ua":"Курка теріякі з рисом"}'::jsonb,
   '{"ru":"Кусочки курицы в блестящей глазури терияки из соевого соуса, мёда и имбиря. Сладко-солёный вкус, липкий соус и кунжут сверху — азиатский ужин за 20 минут.","en":"Chicken pieces in a glossy teriyaki glaze of soy, honey and ginger. Sweet-savoury, sticky and finished with sesame — an Asian dinner in 20 minutes.","ua":"Шматочки курки в блискучій глазурі теріякі із соєвого соусу, меду й імбиру. Солодко-солоний смак, липкий соус і кунжут зверху — азійська вечеря за 20 хвилин."}'::jsonb,
   '{"ru":["Куриное филе — 500 г","Соевый соус — 4 ст. л.","Мёд — 2 ст. л.","Чеснок — 2 зубчика","Имбирь — 1 ч. л.","Растительное масло — 1 ст. л.","Кунжут — для подачи","Зелёный лук — для подачи","Рис — для подачи"],"en":["Chicken breast — 500 g","Soy sauce — 4 tbsp","Honey — 2 tbsp","Garlic — 2 cloves","Ginger — 1 tsp","Vegetable oil — 1 tbsp","Sesame seeds — to serve","Spring onion — to serve","Rice — to serve"],"ua":["Куряче філе — 500 г","Соєвий соус — 4 ст. л.","Мед — 2 ст. л.","Часник — 2 зубчики","Імбир — 1 ч. л.","Олія — 1 ст. л.","Кунжут — для подачі","Зелена цибуля — для подачі","Рис — для подачі"]}'::jsonb,
   '{"ru":["Нарежьте филе кубиками и обжарьте на масле до румяной корочки.","Смешайте соевый соус, мёд, чеснок и имбирь.","Влейте соус к курице и готовьте на среднем огне, помешивая.","Держите на огне, пока соус не загустеет и не покроет курицу глазурью.","Подавайте с рисом, посыпав кунжутом и зелёным луком."],"en":["Dice the fillet and fry in oil until golden.","Mix the soy sauce, honey, garlic and ginger.","Pour the sauce over the chicken and cook over medium heat, stirring.","Keep cooking until the sauce thickens and glazes the chicken.","Serve with rice, scattered with sesame and spring onion."],"ua":["Наріжте філе кубиками й обсмажте на олії до рум''яної скоринки.","Змішайте соєвий соус, мед, часник та імбир.","Влийте соус до курки й готуйте на середньому вогні, помішуючи.","Тримайте на вогні, поки соус не загусне й не вкриє курку глазур''ю.","Подавайте з рисом, посипавши кунжутом і зеленою цибулею."]}'::jsonb,
   '{"ru":["ужин","курица","терияки","азиатское"],"en":["dinner","chicken","teriyaki","asian"],"ua":["вечеря","курка","теріякі","азійське"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('kurinye-bedra-medovo-gorchichnye', 'main', false, null, 45, 380, 4, 'easy',
   '{"ru":"Куриные бёдра в медово-горчичном соусе","en":"Honey-mustard baked chicken thighs","ua":"Курячі стегна в медово-гірчичному соусі"}'::jsonb,
   '{"ru":"Запечённые куриные бёдра с хрустящей карамельной корочкой из мёда и горчицы. Сочные внутри, ароматные снаружи — минимум усилий, максимум вкуса.","en":"Baked chicken thighs with a caramelised honey-mustard crust. Juicy inside, fragrant outside — minimal effort, maximum flavour.","ua":"Запечені курячі стегна з хрусткою карамельною скоринкою з меду й гірчиці. Соковиті всередині, ароматні зовні — мінімум зусиль, максимум смаку."}'::jsonb,
   '{"ru":["Куриные бёдра — 800 г","Мёд — 2 ст. л.","Горчица — 2 ст. л.","Соевый соус — 1 ст. л.","Чеснок — 3 зубчика","Оливковое масло — 1 ст. л.","Соль — по вкусу","Чёрный перец — по вкусу"],"en":["Chicken thighs — 800 g","Honey — 2 tbsp","Mustard — 2 tbsp","Soy sauce — 1 tbsp","Garlic — 3 cloves","Olive oil — 1 tbsp","Salt — to taste","Black pepper — to taste"],"ua":["Курячі стегна — 800 г","Мед — 2 ст. л.","Гірчиця — 2 ст. л.","Соєвий соус — 1 ст. л.","Часник — 3 зубчики","Оливкова олія — 1 ст. л.","Сіль — до смаку","Чорний перець — до смаку"]}'::jsonb,
   '{"ru":["Смешайте мёд, горчицу, соевый соус, чеснок и масло в маринад.","Обмажьте бёдра маринадом и оставьте на 15–20 минут.","Выложите в форму и запекайте при 200 °C около 35 минут.","Полейте бёдра соусом со дна формы и подрумяньте ещё 5 минут.","Совет: за 10 минут до конца полейте курицу соусом ещё раз — корочка будет ярче."],"en":["Mix honey, mustard, soy sauce, garlic and oil into a marinade.","Coat the thighs and let them sit for 15–20 minutes.","Arrange in a dish and bake at 200 °C for about 35 minutes.","Spoon the pan juices over the thighs and brown for 5 more minutes.","Tip: baste once more 10 minutes before the end for a deeper glaze."],"ua":["Змішайте мед, гірчицю, соєвий соус, часник і олію в маринад.","Обмажте стегна маринадом і залиште на 15–20 хвилин.","Викладіть у форму й запікайте за 200 °C близько 35 хвилин.","Полийте стегна соусом із дна форми й підрум''яньте ще 5 хвилин.","Порада: за 10 хвилин до кінця полийте курку соусом ще раз — скоринка буде яскравішою."]}'::jsonb,
   '{"ru":["ужин","курица","запечённое","мёд"],"en":["dinner","chicken","baked","honey"],"ua":["вечеря","курка","запечене","мед"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('kuritsa-v-karri-s-kokosovym-molokom', 'main', false, null, 35, 400, 4, 'medium',
   '{"ru":"Курица в карри с кокосовым молоком","en":"Coconut curry chicken","ua":"Курка в карі з кокосовим молоком"}'::jsonb,
   '{"ru":"Ароматная курица в нежном соусе из кокосового молока с карри и специями. Пряно, но мягко — подавайте с рисом, чтобы собрать весь соус до капли.","en":"Fragrant chicken in a mild coconut-milk curry with warm spices. Spiced but gentle — serve with rice to soak up every drop of sauce.","ua":"Ароматна курка в ніжному соусі з кокосового молока з карі та спеціями. Пряно, але м''яко — подавайте з рисом, щоб зібрати весь соус до краплі."}'::jsonb,
   '{"ru":["Куриное филе — 600 г","Кокосовое молоко — 400 мл","Лук — 1 шт.","Карри — 1,5 ст. л.","Чеснок — 3 зубчика","Имбирь — 1 ч. л.","Помидоры в собственном соку — 200 г","Растительное масло — 1 ст. л.","Соль — по вкусу"],"en":["Chicken breast — 600 g","Coconut milk — 400 ml","Onion — 1","Curry powder — 1.5 tbsp","Garlic — 3 cloves","Ginger — 1 tsp","Canned tomatoes — 200 g","Vegetable oil — 1 tbsp","Salt — to taste"],"ua":["Куряче філе — 600 г","Кокосове молоко — 400 мл","Цибуля — 1 шт.","Карі — 1,5 ст. л.","Часник — 3 зубчики","Імбир — 1 ч. л.","Помідори у власному соку — 200 г","Олія — 1 ст. л.","Сіль — до смаку"]}'::jsonb,
   '{"ru":["Обжарьте нарезанный лук с чесноком и имбирём до мягкости.","Всыпьте карри и прогрейте 30 секунд до аромата.","Добавьте нарезанную курицу и обжарьте до побеления.","Влейте помидоры и кокосовое молоко, тушите 15–20 минут.","Посолите и дайте соусу загустеть. Подавайте с рисом."],"en":["Fry the chopped onion with garlic and ginger until soft.","Add the curry powder and toast for 30 seconds until fragrant.","Add the diced chicken and fry until it turns white.","Pour in the tomatoes and coconut milk, simmer 15–20 minutes.","Season and let the sauce thicken. Serve with rice."],"ua":["Обсмажте нарізану цибулю з часником та імбиром до м''якості.","Всипте карі й прогрійте 30 секунд до аромату.","Додайте нарізану курку й обсмажте до побіління.","Влийте помідори й кокосове молоко, тушкуйте 15–20 хвилин.","Посоліть і дайте соусу загуснути. Подавайте з рисом."]}'::jsonb,
   '{"ru":["ужин","курица","карри","кокос"],"en":["dinner","chicken","curry","coconut"],"ua":["вечеря","курка","карі","кокос"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('kurinye-shashlychki-v-duhovke', 'main', true, null, 40, 220, 4, 'easy',
   '{"ru":"Куриные шашлычки в духовке","en":"Oven-baked chicken skewers","ua":"Курячі шашлички в духовці"}'::jsonb,
   '{"ru":"Сочные кусочки курицы на шпажках в лёгком йогуртовом маринаде, запечённые до румяной корочки. ПП-вариант шашлыка без мангала — вкусно и по-домашнему просто.","en":"Juicy chicken pieces on skewers in a light yoghurt marinade, baked until golden. A healthy no-grill kebab — tasty and easy to make at home.","ua":"Соковиті шматочки курки на шпажках у легкому йогуртовому маринаді, запечені до рум''яної скоринки. ПХ-варіант шашлику без мангала — смачно й по-домашньому просто."}'::jsonb,
   '{"ru":["Куриное филе — 700 г","Натуральный йогурт — 150 г","Паприка — 1 ч. л.","Чеснок — 3 зубчика","Лимонный сок — 1 ст. л.","Оливковое масло — 1 ст. л.","Соль — по вкусу","Чёрный перец — по вкусу"],"en":["Chicken breast — 700 g","Plain yoghurt — 150 g","Paprika — 1 tsp","Garlic — 3 cloves","Lemon juice — 1 tbsp","Olive oil — 1 tbsp","Salt — to taste","Black pepper — to taste"],"ua":["Куряче філе — 700 г","Натуральний йогурт — 150 г","Паприка — 1 ч. л.","Часник — 3 зубчики","Лимонний сік — 1 ст. л.","Оливкова олія — 1 ст. л.","Сіль — до смаку","Чорний перець — до смаку"]}'::jsonb,
   '{"ru":["Нарежьте филе крупными кубиками.","Смешайте йогурт, паприку, чеснок, лимонный сок и масло; замаринуйте курицу 20–30 минут.","Нанижите кусочки на шпажки.","Запекайте при 210 °C около 20–25 минут, перевернув один раз.","Совет: замочите деревянные шпажки в воде, чтобы не подгорели."],"en":["Cut the fillet into large cubes.","Mix yoghurt, paprika, garlic, lemon juice and oil; marinate the chicken 20–30 minutes.","Thread the pieces onto skewers.","Bake at 210 °C for about 20–25 minutes, turning once.","Tip: soak wooden skewers in water so they don''t scorch."],"ua":["Наріжте філе великими кубиками.","Змішайте йогурт, паприку, часник, лимонний сік і олію; замаринуйте курку 20–30 хвилин.","Нанижіть шматочки на шпажки.","Запікайте за 210 °C близько 20–25 хвилин, перевернувши один раз.","Порада: замочіть дерев''яні шпажки у воді, щоб не підгоріли."]}'::jsonb,
   '{"ru":["ПП","ужин","курица","духовка"],"en":["healthy","dinner","chicken","oven"],"ua":["ПХ","вечеря","курка","духовка"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('kuritsa-stir-fray-s-ovoschami', 'main', true, null, 20, 260, 3, 'easy',
   '{"ru":"Курица стир-фрай с овощами","en":"Chicken and vegetable stir-fry","ua":"Курка стір-фрай з овочами"}'::jsonb,
   '{"ru":"Быстрая обжарка курицы с хрустящими овощами в соево-имбирном соусе на сильном огне. Овощи остаются яркими и хрустящими, а ужин готов за 20 минут.","en":"A fast sear of chicken with crisp vegetables in a soy-ginger sauce over high heat. The veg stays bright and crunchy, and dinner is ready in 20 minutes.","ua":"Швидке обсмажування курки з хрусткими овочами в соєво-імбирному соусі на сильному вогні. Овочі лишаються яскравими й хрусткими, а вечеря готова за 20 хвилин."}'::jsonb,
   '{"ru":["Куриное филе — 400 г","Болгарский перец — 1 шт.","Брокколи — 200 г","Морковь — 1 шт.","Соевый соус — 3 ст. л.","Чеснок — 2 зубчика","Имбирь — 1 ч. л.","Растительное масло — 2 ст. л."],"en":["Chicken breast — 400 g","Bell pepper — 1","Broccoli — 200 g","Carrot — 1","Soy sauce — 3 tbsp","Garlic — 2 cloves","Ginger — 1 tsp","Vegetable oil — 2 tbsp"],"ua":["Куряче філе — 400 г","Болгарський перець — 1 шт.","Броколі — 200 г","Морква — 1 шт.","Соєвий соус — 3 ст. л.","Часник — 2 зубчики","Імбир — 1 ч. л.","Олія — 2 ст. л."]}'::jsonb,
   '{"ru":["Нарежьте курицу и овощи тонкими полосками.","Обжарьте курицу на сильном огне до румяности и уберите со сковороды.","Быстро обжарьте овощи 3–4 минуты, чтобы остались хрустящими.","Верните курицу, добавьте чеснок, имбирь и соевый соус.","Прогрейте всё вместе минуту и сразу подавайте."],"en":["Slice the chicken and vegetables into thin strips.","Sear the chicken over high heat until golden and remove.","Stir-fry the vegetables 3–4 minutes so they stay crisp.","Return the chicken, add garlic, ginger and soy sauce.","Toss together for a minute and serve at once."],"ua":["Наріжте курку й овочі тонкими смужками.","Обсмажте курку на сильному вогні до рум''яності й приберіть зі сковороди.","Швидко обсмажте овочі 3–4 хвилини, щоб лишилися хрусткими.","Поверніть курку, додайте часник, імбир і соєвий соус.","Прогрійте все разом хвилину й одразу подавайте."]}'::jsonb,
   '{"ru":["ПП","ужин","курица","овощи"],"en":["healthy","dinner","chicken","vegetables"],"ua":["ПХ","вечеря","курка","овочі"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('kurinyy-shnitsel-v-panirovke', 'main', false, null, 25, 360, 3, 'easy',
   '{"ru":"Куриный шницель в панировке","en":"Crispy chicken schnitzel","ua":"Курячий шніцель у паніровці"}'::jsonb,
   '{"ru":"Тонкие отбивные из куриного филе в золотистой хрустящей панировке. Снаружи хрустит, внутри остаётся сочным — классика, которую любят и взрослые, и дети.","en":"Thin chicken breast cutlets in a golden, crunchy crust. Crisp outside, juicy inside — a classic loved by kids and grown-ups alike.","ua":"Тонкі відбивні з курячого філе в золотистій хрусткій паніровці. Зовні хрустить, всередині лишається соковитим — класика, яку люблять і дорослі, і діти."}'::jsonb,
   '{"ru":["Куриное филе — 500 г","Яйца — 2 шт.","Панировочные сухари — 100 г","Мука — 3 ст. л.","Соль — по вкусу","Чёрный перец — по вкусу","Масло для жарки — по необходимости"],"en":["Chicken breast — 500 g","Eggs — 2","Breadcrumbs — 100 g","Flour — 3 tbsp","Salt — to taste","Black pepper — to taste","Oil for frying — as needed"],"ua":["Куряче філе — 500 г","Яйця — 2 шт.","Панірувальні сухарі — 100 г","Борошно — 3 ст. л.","Сіль — до смаку","Чорний перець — до смаку","Олія для смаження — за потреби"]}'::jsonb,
   '{"ru":["Разрежьте филе вдоль и слегка отбейте, посолите и поперчите.","Обваляйте кусочки в муке, затем во взбитом яйце и в сухарях.","Обжарьте на среднем огне по 3–4 минуты с каждой стороны до золотистой корочки.","Выложите на бумажное полотенце, чтобы убрать лишнее масло.","Совет: не перегревайте масло, иначе панировка сгорит раньше, чем прожарится мясо."],"en":["Slice the fillet lengthways, gently flatten, then season.","Coat the pieces in flour, then beaten egg, then breadcrumbs.","Fry over medium heat 3–4 minutes per side until golden.","Drain on paper towel to remove excess oil.","Tip: don''t overheat the oil or the crust burns before the meat cooks."],"ua":["Розріжте філе вздовж і злегка відбийте, посоліть і поперчіть.","Обваляйте шматочки в борошні, потім у збитому яйці та в сухарях.","Обсмажте на середньому вогні по 3–4 хвилини з кожного боку до золотистої скоринки.","Викладіть на паперовий рушник, щоб прибрати зайву олію.","Порада: не перегрівайте олію, інакше паніровка згорить раніше, ніж просмажиться м''ясо."]}'::jsonb,
   '{"ru":["ужин","курица","хрустящее","классика"],"en":["dinner","chicken","crispy","classic"],"ua":["вечеря","курка","хрустке","класика"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('kurinyy-sup-s-lapshoy', 'soup', false, null, 40, 180, 5, 'easy',
   '{"ru":"Куриный суп с домашней лапшой","en":"Chicken noodle soup","ua":"Курячий суп з домашньою локшиною"}'::jsonb,
   '{"ru":"Прозрачный ароматный бульон с курицей, морковью и лапшой — тот самый суп, который согревает и лечит. Простой набор продуктов и по-настоящему домашний вкус.","en":"A clear, fragrant broth with chicken, carrot and noodles — the soup that warms and heals. Simple ingredients and a truly homemade taste.","ua":"Прозорий ароматний бульйон з куркою, морквою та локшиною — той самий суп, що зігріває й лікує. Простий набір продуктів і по-справжньому домашній смак."}'::jsonb,
   '{"ru":["Курица (бёдра или грудка) — 500 г","Лапша — 120 г","Морковь — 1 шт.","Лук — 1 шт.","Картофель — 2 шт.","Лавровый лист — 1 шт.","Петрушка — небольшой пучок","Соль — по вкусу","Чёрный перец — по вкусу"],"en":["Chicken (thighs or breast) — 500 g","Noodles — 120 g","Carrot — 1","Onion — 1","Potatoes — 2","Bay leaf — 1","Parsley — a small bunch","Salt — to taste","Black pepper — to taste"],"ua":["Курка (стегна або грудка) — 500 г","Локшина — 120 г","Морква — 1 шт.","Цибуля — 1 шт.","Картопля — 2 шт.","Лавровий лист — 1 шт.","Петрушка — невеликий пучок","Сіль — до смаку","Чорний перець — до смаку"]}'::jsonb,
   '{"ru":["Отварите курицу с целой луковицей и лавровым листом 25 минут, снимая пену.","Достаньте курицу, разберите на кусочки, бульон процедите.","Добавьте в бульон нарезанный картофель и морковь, варите 10 минут.","Всыпьте лапшу и верните курицу, варите до готовности лапши.","Посолите, поперчите и посыпьте петрушкой перед подачей."],"en":["Simmer the chicken with a whole onion and bay leaf for 25 minutes, skimming.","Remove the chicken, shred it, and strain the broth.","Add diced potato and carrot to the broth and cook 10 minutes.","Add the noodles and return the chicken; cook until the noodles are done.","Season and scatter with parsley before serving."],"ua":["Відваріть курку з цілою цибулиною та лавровим листом 25 хвилин, знімаючи піну.","Дістаньте курку, розберіть на шматочки, бульйон процідіть.","Додайте в бульйон нарізану картоплю й моркву, варіть 10 хвилин.","Всипте локшину й поверніть курку, варіть до готовності локшини.","Посоліть, поперчіть і посипте петрушкою перед подачею."]}'::jsonb,
   '{"ru":["суп","курица","обед","домашнее"],"en":["soup","chicken","lunch","homemade"],"ua":["суп","курка","обід","домашнє"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

npm notice
npm notice New major version of npm available! 10.9.7 -> 12.1.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v12.1.0
npm notice To update run: npm install -g npm@12.1.0
npm notice
