-- Generated by scripts/export-sql.ts — paste into the Supabase SQL editor.
-- image is left NULL on purpose: attach the photo later from the admin panel
-- (the site shows a category placeholder cover until then).

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('omlet-s-ovoschami-i-syrom', 'breakfast', true, null, 15, 240, 2, 'easy',
   '{"ru":"Омлет с овощами и сыром","en":"Veggie and cheese omelette","ua":"Омлет з овочами та сиром"}'::jsonb,
   '{"ru":"Пышный омлет с сочными помидорами, перцем и тянущимся сыром. Белковый завтрак, который заряжает энергией и готовится быстрее, чем варится кофе.","en":"A fluffy omelette with juicy tomatoes, pepper and melty cheese. A protein breakfast that fuels the morning and cooks faster than your coffee brews.","ua":"Пишний омлет із соковитими помідорами, перцем і тягучим сиром. Білковий сніданок, що заряджає енергією й готується швидше, ніж вариться кава."}'::jsonb,
   '{"ru":["Яйца — 4 шт.","Молоко — 60 мл","Помидор — 1 шт.","Болгарский перец — половина","Твёрдый сыр — 50 г","Зелень — по вкусу","Сливочное масло — 10 г","Соль и перец — по вкусу"],"en":["Eggs — 4","Milk — 60 ml","Tomato — 1","Bell pepper — half","Hard cheese — 50 g","Herbs — to taste","Butter — 10 g","Salt and pepper — to taste"],"ua":["Яйця — 4 шт.","Молоко — 60 мл","Помідор — 1 шт.","Болгарський перець — половина","Твердий сир — 50 г","Зелень — до смаку","Вершкове масло — 10 г","Сіль і перець — до смаку"]}'::jsonb,
   '{"ru":["Взбейте яйца с молоком, солью и перцем.","Обжарьте нарезанные овощи на масле 2–3 минуты.","Влейте яичную смесь и готовьте на слабом огне под крышкой.","Посыпьте тёртым сыром и зеленью, дайте сыру расплавиться.","Сложите омлет пополам и подавайте сразу."],"en":["Whisk the eggs with milk, salt and pepper.","Fry the chopped vegetables in butter for 2–3 minutes.","Pour in the egg mix and cook over low heat, covered.","Scatter with grated cheese and herbs, let the cheese melt.","Fold the omelette in half and serve at once."],"ua":["Збийте яйця з молоком, сіллю та перцем.","Обсмажте нарізані овочі на маслі 2–3 хвилини.","Влийте яєчну суміш і готуйте на слабкому вогні під кришкою.","Посипте тертим сиром і зеленню, дайте сиру розплавитися.","Складіть омлет навпіл і подавайте одразу."]}'::jsonb,
   '{"ru":["ПП","завтрак","яйца","быстро"],"en":["healthy","breakfast","eggs","quick"],"ua":["ПХ","сніданок","яйця","швидко"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('shakshuka', 'breakfast', false, null, 25, 260, 2, 'easy',
   '{"ru":"Шакшука — яйца в томатном соусе","en":"Shakshuka — eggs in tomato sauce","ua":"Шакшука — яйця в томатному соусі"}'::jsonb,
   '{"ru":"Яйца, запечённые в пряном томатном соусе с перцем и специями. Средиземноморский завтрак прямо на сковороде — сытно, ярко и с ароматным хлебом для макания.","en":"Eggs poached in a spiced tomato sauce with peppers and warm spices. A Mediterranean breakfast straight from the pan — hearty, vivid and made for dunking bread.","ua":"Яйця, запечені в пряному томатному соусі з перцем і спеціями. Середземноморський сніданок просто на сковороді — ситно, яскраво й з ароматним хлібом для вмочання."}'::jsonb,
   '{"ru":["Яйца — 4 шт.","Помидоры — 400 г","Болгарский перец — 1 шт.","Лук — 1 шт.","Чеснок — 2 зубчика","Паприка — 1 ч. л.","Зира — 0,5 ч. л.","Оливковое масло — 2 ст. л.","Соль и перец — по вкусу"],"en":["Eggs — 4","Tomatoes — 400 g","Bell pepper — 1","Onion — 1","Garlic — 2 cloves","Paprika — 1 tsp","Cumin — 0.5 tsp","Olive oil — 2 tbsp","Salt and pepper — to taste"],"ua":["Яйця — 4 шт.","Помідори — 400 г","Болгарський перець — 1 шт.","Цибуля — 1 шт.","Часник — 2 зубчики","Паприка — 1 ч. л.","Кмин — 0,5 ч. л.","Оливкова олія — 2 ст. л.","Сіль і перець — до смаку"]}'::jsonb,
   '{"ru":["Обжарьте лук и перец на оливковом масле до мягкости.","Добавьте чеснок и специи, прогрейте до аромата.","Влейте измельчённые помидоры и тушите 8–10 минут до густоты.","Сделайте углубления и вбейте яйца, накройте крышкой.","Готовьте, пока белок схватится, а желток останется жидким. Подавайте с хлебом."],"en":["Fry the onion and pepper in olive oil until soft.","Add the garlic and spices, warm until fragrant.","Pour in the chopped tomatoes and simmer 8–10 minutes until thick.","Make wells and crack in the eggs, then cover.","Cook until the whites set but the yolks stay runny. Serve with bread."],"ua":["Обсмажте цибулю й перець на оливковій олії до м''якості.","Додайте часник і спеції, прогрійте до аромату.","Влийте подрібнені помідори й тушкуйте 8–10 хвилин до густоти.","Зробіть заглиблення й вбийте яйця, накрийте кришкою.","Готуйте, поки білок схопиться, а жовток лишиться рідким. Подавайте з хлібом."]}'::jsonb,
   '{"ru":["завтрак","яйца","томаты"],"en":["breakfast","eggs","tomato"],"ua":["сніданок","яйця","томати"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('lenivaya-ovsyanka-v-banke', 'breakfast', true, null, 10, 280, 1, 'easy',
   '{"ru":"Ленивая овсянка в банке","en":"Overnight oats in a jar","ua":"Лінива вівсянка в банці"}'::jsonb,
   '{"ru":"Овсянку не нужно варить: с вечера залил йогуртом и молоком, а утром достал готовый завтрак с ягодами и мёдом. Идеально, когда нет времени на готовку.","en":"No cooking needed: mix with yoghurt and milk the night before, and in the morning you have a ready breakfast with berries and honey. Perfect when there''s no time to cook.","ua":"Вівсянку не треба варити: з вечора залив йогуртом і молоком, а вранці дістав готовий сніданок із ягодами й медом. Ідеально, коли немає часу на готування."}'::jsonb,
   '{"ru":["Овсяные хлопья — 50 г","Йогурт — 100 г","Молоко — 100 мл","Мёд — 1 ч. л.","Ягоды — 60 г","Семена чиа — 1 ч. л."],"en":["Rolled oats — 50 g","Yoghurt — 100 g","Milk — 100 ml","Honey — 1 tsp","Berries — 60 g","Chia seeds — 1 tsp"],"ua":["Вівсяні пластівці — 50 г","Йогурт — 100 г","Молоко — 100 мл","Мед — 1 ч. л.","Ягоди — 60 г","Насіння чіа — 1 ч. л."]}'::jsonb,
   '{"ru":["В банку всыпьте хлопья и семена чиа.","Влейте молоко и йогурт, добавьте мёд, перемешайте.","Закройте крышкой и уберите в холодильник на ночь.","Утром добавьте ягоды и при желании орехи.","Совет: регулируйте густоту молоком — за ночь овсянка загустеет."],"en":["Put the oats and chia seeds into a jar.","Pour in the milk and yoghurt, add honey and stir.","Close the lid and refrigerate overnight.","In the morning top with berries and nuts if you like.","Tip: adjust the thickness with milk — the oats thicken overnight."],"ua":["У банку всипте пластівці й насіння чіа.","Влийте молоко та йогурт, додайте мед, перемішайте.","Закрийте кришкою й приберіть у холодильник на ніч.","Вранці додайте ягоди й за бажанням горіхи.","Порада: регулюйте густоту молоком — за ніч вівсянка загусне."]}'::jsonb,
   '{"ru":["ПП","завтрак","овсянка","без готовки"],"en":["healthy","breakfast","oats","no-cook"],"ua":["ПХ","сніданок","вівсянка","без готування"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('domashnyaya-granola', 'breakfast', true, null, 35, 300, 6, 'easy',
   '{"ru":"Домашняя гранола","en":"Homemade granola","ua":"Домашня гранола"}'::jsonb,
   '{"ru":"Хрустящая гранола из овсянки, орехов и мёда, запечённая до золотистых кластеров. Полезнее магазинной, без лишнего сахара — с молоком, йогуртом или просто горстью.","en":"Crunchy granola of oats, nuts and honey, baked into golden clusters. Healthier than shop-bought and lower in sugar — with milk, yoghurt or just a handful.","ua":"Хрустка гранола з вівсянки, горіхів і меду, запечена до золотистих кластерів. Корисніша за магазинну, без зайвого цукру — з молоком, йогуртом чи просто жменею."}'::jsonb,
   '{"ru":["Овсяные хлопья — 250 г","Орехи микс — 100 г","Мёд — 3 ст. л.","Растительное масло — 2 ст. л.","Семечки — 40 г","Сухофрукты — 80 г","Корица — 0,5 ч. л."],"en":["Rolled oats — 250 g","Mixed nuts — 100 g","Honey — 3 tbsp","Vegetable oil — 2 tbsp","Seeds — 40 g","Dried fruit — 80 g","Cinnamon — 0.5 tsp"],"ua":["Вівсяні пластівці — 250 г","Горіхи мікс — 100 г","Мед — 3 ст. л.","Олія — 2 ст. л.","Насіння — 40 г","Сухофрукти — 80 г","Кориця — 0,5 ч. л."]}'::jsonb,
   '{"ru":["Смешайте хлопья, орехи, семечки и корицу.","Добавьте мёд и масло, тщательно перемешайте.","Выложите ровным слоем на противень с пергаментом.","Запекайте при 160 °C 25–30 минут, помешивая каждые 10 минут.","Остудите полностью, затем вмешайте сухофрукты — так гранола станет хрустящей."],"en":["Mix the oats, nuts, seeds and cinnamon.","Add the honey and oil and toss thoroughly.","Spread in an even layer on a lined baking sheet.","Bake at 160 °C for 25–30 minutes, stirring every 10 minutes.","Cool completely, then stir in the dried fruit — that''s what makes it crunchy."],"ua":["Змішайте пластівці, горіхи, насіння й корицю.","Додайте мед і олію, ретельно перемішайте.","Викладіть рівним шаром на деко з пергаментом.","Запікайте за 160 °C 25–30 хвилин, помішуючи кожні 10 хвилин.","Остудіть повністю, потім вмішайте сухофрукти — так гранола стане хрусткою."]}'::jsonb,
   '{"ru":["ПП","завтрак","гранола","овсянка"],"en":["healthy","breakfast","granola","oats"],"ua":["ПХ","сніданок","гранола","вівсянка"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('frantsuzskie-grenki', 'breakfast', false, null, 15, 320, 2, 'easy',
   '{"ru":"Французские гренки (френч-тост)","en":"French toast","ua":"Французькі грінки (френч-тост)"}'::jsonb,
   '{"ru":"Ломтики хлеба в сладком яично-молочном кляре, обжаренные до золотистой карамельной корочки. Подавайте с мёдом, ягодами или сгущёнкой — уютный завтрак выходного дня.","en":"Slices of bread in a sweet egg-and-milk custard, fried to a golden caramel crust. Serve with honey, berries or condensed milk — a cosy weekend breakfast.","ua":"Скибочки хліба в солодкому яєчно-молочному клярі, обсмажені до золотистої карамельної скоринки. Подавайте з медом, ягодами чи згущівкою — затишний сніданок вихідного дня."}'::jsonb,
   '{"ru":["Хлеб (батон) — 6 ломтиков","Яйца — 2 шт.","Молоко — 100 мл","Сахар — 1 ст. л.","Ванильный сахар — 1 ч. л.","Сливочное масло — для жарки"],"en":["Bread (loaf) — 6 slices","Eggs — 2","Milk — 100 ml","Sugar — 1 tbsp","Vanilla sugar — 1 tsp","Butter — for frying"],"ua":["Хліб (батон) — 6 скибочок","Яйця — 2 шт.","Молоко — 100 мл","Цукор — 1 ст. л.","Ванільний цукор — 1 ч. л.","Вершкове масло — для смаження"]}'::jsonb,
   '{"ru":["Взбейте яйца с молоком, сахаром и ванилью.","Обмакивайте ломтики хлеба в смесь с двух сторон.","Обжаривайте на сливочном масле до золотистой корочки.","Переверните и подрумяньте вторую сторону.","Подавайте тёплыми с мёдом, ягодами или сиропом."],"en":["Whisk the eggs with milk, sugar and vanilla.","Dip the bread slices in the mix on both sides.","Fry in butter until golden.","Flip and brown the other side.","Serve warm with honey, berries or syrup."],"ua":["Збийте яйця з молоком, цукром і ваніллю.","Вмочайте скибочки хліба в суміш із двох боків.","Обсмажуйте на вершковому маслі до золотистої скоринки.","Переверніть і підрум''яньте другий бік.","Подавайте теплими з медом, ягодами чи сиропом."]}'::jsonb,
   '{"ru":["завтрак","хлеб","яйца","сладкое"],"en":["breakfast","bread","eggs","sweet"],"ua":["сніданок","хліб","яйця","солодке"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('amerikanskie-pankeyki', 'breakfast', false, null, 25, 300, 3, 'easy',
   '{"ru":"Американские панкейки","en":"American pancakes","ua":"Американські панкейки"}'::jsonb,
   '{"ru":"Толстенькие пышные панкейки, как из американских фильмов — стопкой, с маслом и кленовым сиропом. Секрет пышности — кефир и не перемешивать тесто слишком долго.","en":"Thick, fluffy pancakes like in the movies — stacked with butter and maple syrup. The secret to the rise is buttermilk and not overmixing the batter.","ua":"Товстенькі пишні панкейки, як з американських фільмів — стосом, з маслом і кленовим сиропом. Секрет пишності — кефір і не перемішувати тісто надто довго."}'::jsonb,
   '{"ru":["Мука — 200 г","Кефир — 250 мл","Яйцо — 1 шт.","Сахар — 2 ст. л.","Разрыхлитель — 1 ч. л.","Сода — 0,5 ч. л.","Сливочное масло — 30 г","Щепотка соли"],"en":["Flour — 200 g","Buttermilk — 250 ml","Egg — 1","Sugar — 2 tbsp","Baking powder — 1 tsp","Baking soda — 0.5 tsp","Butter — 30 g","A pinch of salt"],"ua":["Борошно — 200 г","Кефір — 250 мл","Яйце — 1 шт.","Цукор — 2 ст. л.","Розпушувач — 1 ч. л.","Сода — 0,5 ч. л.","Вершкове масло — 30 г","Дрібка солі"]}'::jsonb,
   '{"ru":["Смешайте сухие ингредиенты в одной миске.","В другой соедините кефир, яйцо и растопленное масло.","Быстро соедините смеси — комочки допустимы, не перемешивайте долго.","Выпекайте на сухой сковороде до пузырьков, затем переверните.","Складывайте стопкой и подавайте с сиропом или ягодами."],"en":["Mix the dry ingredients in one bowl.","In another, combine buttermilk, egg and melted butter.","Quickly fold together — lumps are fine, don''t overmix.","Cook on a dry pan until bubbles form, then flip.","Stack them up and serve with syrup or berries."],"ua":["Змішайте сухі інгредієнти в одній мисці.","В іншій поєднайте кефір, яйце й розтоплене масло.","Швидко поєднайте суміші — грудочки припустимі, не перемішуйте довго.","Випікайте на сухій сковороді до бульбашок, потім переверніть.","Складайте стосом і подавайте із сиропом чи ягодами."]}'::jsonb,
   '{"ru":["завтрак","панкейки","сладкое"],"en":["breakfast","pancakes","sweet"],"ua":["сніданок","панкейки","солодке"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('risovaya-kasha-na-moloke', 'breakfast', false, null, 30, 220, 3, 'easy',
   '{"ru":"Рисовая каша на молоке","en":"Creamy milk rice porridge","ua":"Рисова каша на молоці"}'::jsonb,
   '{"ru":"Нежная молочная рисовая каша — тёплый уютный завтрак родом из детства. Кремовая текстура достигается на медленном огне, а сверху — кусочек масла.","en":"A tender milk rice porridge — a warm, comforting breakfast straight from childhood. The creamy texture comes from slow cooking, finished with a knob of butter.","ua":"Ніжна молочна рисова каша — теплий затишний сніданок родом із дитинства. Кремова текстура досягається на повільному вогні, а зверху — шматочок масла."}'::jsonb,
   '{"ru":["Рис круглозёрный — 120 г","Молоко — 600 мл","Вода — 200 мл","Сахар — 2 ст. л.","Сливочное масло — 20 г","Щепотка соли"],"en":["Round rice — 120 g","Milk — 600 ml","Water — 200 ml","Sugar — 2 tbsp","Butter — 20 g","A pinch of salt"],"ua":["Рис круглозернистий — 120 г","Молоко — 600 мл","Вода — 200 мл","Цукор — 2 ст. л.","Вершкове масло — 20 г","Дрібка солі"]}'::jsonb,
   '{"ru":["Промойте рис и залейте водой, варите 5 минут до впитывания.","Влейте молоко и доведите до лёгкого кипения.","Варите на медленном огне 20 минут, помешивая, чтобы не пригорело.","Добавьте сахар и соль, прогрейте пару минут.","Снимите с огня, положите масло и дайте настояться под крышкой."],"en":["Rinse the rice, add water and cook 5 minutes until absorbed.","Pour in the milk and bring to a gentle simmer.","Cook on low for 20 minutes, stirring so it doesn''t catch.","Add sugar and salt and warm a couple of minutes.","Off the heat, add butter and let it rest, covered."],"ua":["Промийте рис і залийте водою, варіть 5 хвилин до вбирання.","Влийте молоко й доведіть до легкого кипіння.","Варіть на повільному вогні 20 хвилин, помішуючи, щоб не пригоріло.","Додайте цукор і сіль, прогрійте пару хвилин.","Зніміть з вогню, покладіть масло й дайте настоятися під кришкою."]}'::jsonb,
   '{"ru":["завтрак","каша","рис","молоко"],"en":["breakfast","porridge","rice","milk"],"ua":["сніданок","каша","рис","молоко"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('smuzi-boul', 'breakfast', true, null, 10, 210, 1, 'easy',
   '{"ru":"Смузи-боул с бананом и ягодами","en":"Berry banana smoothie bowl","ua":"Смузі-боул з бананом і ягодами"}'::jsonb,
   '{"ru":"Густой холодный смузи в тарелке с топпингами: свежие фрукты, гранола и семена. Красивый и полезный завтрак, который заряжает витаминами за пять минут.","en":"A thick, cold smoothie in a bowl with toppings: fresh fruit, granola and seeds. A beautiful, wholesome breakfast that loads you with vitamins in five minutes.","ua":"Густий холодний смузі в тарілці з топінгами: свіжі фрукти, гранола й насіння. Гарний і корисний сніданок, що заряджає вітамінами за п''ять хвилин."}'::jsonb,
   '{"ru":["Банан замороженный — 1 шт.","Ягоды замороженные — 150 г","Йогурт — 100 г","Молоко — 50 мл","Мёд — 1 ч. л.","Гранола и свежие фрукты — для подачи"],"en":["Frozen banana — 1","Frozen berries — 150 g","Yoghurt — 100 g","Milk — 50 ml","Honey — 1 tsp","Granola and fresh fruit — to serve"],"ua":["Заморожений банан — 1 шт.","Заморожені ягоди — 150 г","Йогурт — 100 г","Молоко — 50 мл","Мед — 1 ч. л.","Гранола та свіжі фрукти — для подачі"]}'::jsonb,
   '{"ru":["Пробейте блендером банан, ягоды, йогурт, молоко и мёд.","Масса должна быть густой — регулируйте молоком.","Перелейте в тарелку.","Красиво выложите сверху фрукты, гранолу и семена.","Подавайте сразу, пока холодный."],"en":["Blend the banana, berries, yoghurt, milk and honey.","The mix should be thick — adjust with milk.","Pour into a bowl.","Arrange fruit, granola and seeds neatly on top.","Serve at once while cold."],"ua":["Пробийте блендером банан, ягоди, йогурт, молоко й мед.","Маса має бути густою — регулюйте молоком.","Перелийте в тарілку.","Гарно викладіть зверху фрукти, гранолу й насіння.","Подавайте одразу, поки холодний."]}'::jsonb,
   '{"ru":["ПП","завтрак","смузи","ягоды"],"en":["healthy","breakfast","smoothie","berries"],"ua":["ПХ","сніданок","смузі","ягоди"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

