-- Generated by scripts/export-sql.ts — paste into the Supabase SQL editor.
-- image is left NULL on purpose: attach the photo later from the admin panel
-- (the site shows a category placeholder cover until then).

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('salat-cezar-s-kuricey', 'salad', false, null, 25, 320, 3, 'easy',
   '{"ru":"Салат «Цезарь» с курицей","en":"Chicken Caesar salad","ua":"Салат «Цезар» з куркою"}'::jsonb,
   '{"ru":"Хрустящий салат ромэн с обжаренной курицей, сухариками и пармезаном под кремовым соусом. Классика, которую любят все, — сытно и по-ресторанному вкусно.","en":"Crisp romaine with seared chicken, croutons and parmesan in a creamy dressing. A crowd-pleasing classic — filling and restaurant-good.","ua":"Хрусткий салат ромен з обсмаженою куркою, сухариками й пармезаном під кремовим соусом. Класика, яку люблять усі, — ситно й по-ресторанному смачно."}'::jsonb,
   '{"ru":["Куриное филе — 300 г","Салат ромэн — 1 большой пучок","Пармезан — 50 г","Белый хлеб — 3 ломтика","Чеснок — 1 зубчик","Майонез — 3 ст. л.","Горчица — 1 ч. л.","Лимонный сок — 1 ст. л.","Оливковое масло — 2 ст. л."],"en":["Chicken breast — 300 g","Romaine lettuce — 1 large head","Parmesan — 50 g","White bread — 3 slices","Garlic — 1 clove","Mayonnaise — 3 tbsp","Mustard — 1 tsp","Lemon juice — 1 tbsp","Olive oil — 2 tbsp"],"ua":["Куряче філе — 300 г","Салат ромен — 1 великий пучок","Пармезан — 50 г","Білий хліб — 3 скибочки","Часник — 1 зубчик","Майонез — 3 ст. л.","Гірчиця — 1 ч. л.","Лимонний сік — 1 ст. л.","Оливкова олія — 2 ст. л."]}'::jsonb,
   '{"ru":["Обжарьте курицу до румяности и нарежьте полосками.","Подсушите кубики хлеба на сковороде с чесноком до хруста.","Смешайте майонез, горчицу, лимонный сок и часть пармезана в соус.","Порвите салат руками, заправьте соусом.","Выложите курицу, сухарики и стружку пармезана сверху."],"en":["Sear the chicken until golden and slice into strips.","Toast bread cubes in a pan with garlic until crisp.","Mix mayo, mustard, lemon juice and some parmesan into a dressing.","Tear the lettuce by hand and toss with the dressing.","Top with the chicken, croutons and shaved parmesan."],"ua":["Обсмажте курку до рум''яності й наріжте смужками.","Підсушіть кубики хліба на сковороді з часником до хрускоту.","Змішайте майонез, гірчицю, лимонний сік і частину пармезану в соус.","Порвіть салат руками, заправте соусом.","Викладіть курку, сухарики й стружку пармезану зверху."]}'::jsonb,
   '{"ru":["салат","курица","цезарь"],"en":["salad","chicken","caesar"],"ua":["салат","курка","цезар"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('salat-olivye', 'salad', false, null, 40, 300, 6, 'easy',
   '{"ru":"Салат «Оливье»","en":"Olivier (Russian) salad","ua":"Салат «Олів''є»"}'::jsonb,
   '{"ru":"Тот самый праздничный оливье с колбасой, солёными огурцами и горошком под майонезом. Знакомый вкус, который собирает всю семью за столом.","en":"The classic festive Olivier with sausage, pickles and peas in mayonnaise. A familiar taste that gathers the whole family at the table.","ua":"Той самий святковий олів''є з ковбасою, солоними огірками й горошком під майонезом. Знайомий смак, що збирає всю родину за столом."}'::jsonb,
   '{"ru":["Картофель — 4 шт.","Морковь — 2 шт.","Яйца — 4 шт.","Варёная колбаса — 300 г","Солёные огурцы — 3 шт.","Зелёный горошек — 200 г","Лук — 1 шт.","Майонез — 150 г","Соль — по вкусу"],"en":["Potatoes — 4","Carrots — 2","Eggs — 4","Boiled sausage — 300 g","Pickles — 3","Green peas — 200 g","Onion — 1","Mayonnaise — 150 g","Salt — to taste"],"ua":["Картопля — 4 шт.","Морква — 2 шт.","Яйця — 4 шт.","Варена ковбаса — 300 г","Солоні огірки — 3 шт.","Зелений горошок — 200 г","Цибуля — 1 шт.","Майонез — 150 г","Сіль — до смаку"]}'::jsonb,
   '{"ru":["Отварите картофель, морковь и яйца, остудите и очистите.","Нарежьте всё мелкими кубиками одного размера.","Добавьте колбасу, огурцы, лук и горошек.","Заправьте майонезом, посолите и перемешайте.","Дайте салату настояться в холодильнике 1 час перед подачей."],"en":["Boil the potatoes, carrots and eggs, then cool and peel.","Dice everything into small, even cubes.","Add the sausage, pickles, onion and peas.","Dress with mayonnaise, season and mix.","Chill for 1 hour before serving so the flavours meld."],"ua":["Відваріть картоплю, моркву та яйця, остудіть і почистіть.","Наріжте все дрібними кубиками одного розміру.","Додайте ковбасу, огірки, цибулю й горошок.","Заправте майонезом, посоліть і перемішайте.","Дайте салату настоятися в холодильнику 1 годину перед подачею."]}'::jsonb,
   '{"ru":["салат","оливье","праздничное"],"en":["salad","olivier","festive"],"ua":["салат","олів''є","святкове"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('salat-mimoza', 'salad', false, null, 45, 320, 6, 'easy',
   '{"ru":"Салат «Мимоза» с рыбными консервами","en":"Mimosa layered fish salad","ua":"Салат «Мімоза» з рибними консервами"}'::jsonb,
   '{"ru":"Нежный слоёный салат с рыбными консервами, яйцом и сыром, посыпанный жёлтым желтком — как цветы мимозы. Тает во рту и всегда исчезает первым.","en":"A tender layered salad of canned fish, egg and cheese, topped with grated yolk like mimosa blossoms. It melts in the mouth and always disappears first.","ua":"Ніжний листковий салат із рибними консервами, яйцем і сиром, посипаний жовтим жовтком — як квіти мімози. Тане в роті й завжди зникає першим."}'::jsonb,
   '{"ru":["Рыбные консервы — 240 г","Яйца — 5 шт.","Картофель — 3 шт.","Морковь — 2 шт.","Твёрдый сыр — 100 г","Лук — 1 шт.","Майонез — 150 г","Соль — по вкусу"],"en":["Canned fish — 240 g","Eggs — 5","Potatoes — 3","Carrots — 2","Hard cheese — 100 g","Onion — 1","Mayonnaise — 150 g","Salt — to taste"],"ua":["Рибні консерви — 240 г","Яйця — 5 шт.","Картопля — 3 шт.","Морква — 2 шт.","Твердий сир — 100 г","Цибуля — 1 шт.","Майонез — 150 г","Сіль — до смаку"]}'::jsonb,
   '{"ru":["Отварите картофель, морковь и яйца, натрите на тёрке отдельно.","Разомните рыбу вилкой, удалив кости.","Выкладывайте слои: картофель, рыба с луком, морковь, сыр, белки.","Каждый слой промазывайте тонким слоем майонеза.","Верхний слой — тёртый желток. Дайте настояться 2 часа в холодильнике."],"en":["Boil potatoes, carrots and eggs, then grate each separately.","Mash the fish with a fork, removing any bones.","Layer: potato, fish with onion, carrot, cheese, egg whites.","Spread a thin layer of mayonnaise between each layer.","Top with grated yolk. Chill for 2 hours before serving."],"ua":["Відваріть картоплю, моркву та яйця, натріть на тертці окремо.","Розімніть рибу виделкою, видаливши кістки.","Викладайте шари: картопля, риба з цибулею, морква, сир, білки.","Кожен шар промазуйте тонким шаром майонезу.","Верхній шар — тертий жовток. Дайте настоятися 2 години в холодильнику."]}'::jsonb,
   '{"ru":["салат","мимоза","рыба","праздничное"],"en":["salad","mimosa","fish","festive"],"ua":["салат","мімоза","риба","святкове"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('vinegret', 'salad', true, null, 40, 150, 6, 'easy',
   '{"ru":"Винегрет","en":"Vinegret beet salad","ua":"Вінегрет"}'::jsonb,
   '{"ru":"Яркий постный салат из варёной свёклы, картофеля, моркови и солёных огурцов с квашеной капустой. Полезно, бюджетно и с той самой кислинкой.","en":"A vivid, lean salad of boiled beetroot, potato, carrot and pickles with sauerkraut. Wholesome, budget-friendly and with just the right tang.","ua":"Яскравий пісний салат із вареного буряка, картоплі, моркви й солоних огірків із квашеною капустою. Корисно, бюджетно й із тією самою кислинкою."}'::jsonb,
   '{"ru":["Свёкла — 2 шт.","Картофель — 3 шт.","Морковь — 2 шт.","Солёные огурцы — 3 шт.","Квашеная капуста — 150 г","Лук — 1 шт.","Зелёный горошек — 100 г","Растительное масло — 3 ст. л.","Соль — по вкусу"],"en":["Beetroot — 2","Potatoes — 3","Carrots — 2","Pickles — 3","Sauerkraut — 150 g","Onion — 1","Green peas — 100 g","Vegetable oil — 3 tbsp","Salt — to taste"],"ua":["Буряк — 2 шт.","Картопля — 3 шт.","Морква — 2 шт.","Солоні огірки — 3 шт.","Квашена капуста — 150 г","Цибуля — 1 шт.","Зелений горошок — 100 г","Олія — 3 ст. л.","Сіль — до смаку"]}'::jsonb,
   '{"ru":["Отварите свёклу, картофель и морковь, остудите и очистите.","Нарежьте все овощи мелкими кубиками.","Свёклу отдельно сбрызните маслом, чтобы не окрасила остальное.","Соедините все овощи, капусту, огурцы, лук и горошек.","Заправьте маслом, посолите и перемешайте."],"en":["Boil the beetroot, potato and carrot, then cool and peel.","Dice all the vegetables into small cubes.","Toss the beetroot with oil separately so it doesn''t stain the rest.","Combine all the veg, sauerkraut, pickles, onion and peas.","Dress with oil, season and mix."],"ua":["Відваріть буряк, картоплю й моркву, остудіть і почистіть.","Наріжте всі овочі дрібними кубиками.","Буряк окремо збризніть олією, щоб не забарвив решту.","Поєднайте всі овочі, капусту, огірки, цибулю й горошок.","Заправте олією, посоліть і перемішайте."]}'::jsonb,
   '{"ru":["ПП","салат","постное","свёкла"],"en":["healthy","salad","lean","beetroot"],"ua":["ПХ","салат","пісне","буряк"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('teplyy-salat-s-kuricey', 'salad', true, null, 25, 240, 2, 'easy',
   '{"ru":"Тёплый салат с курицей и овощами","en":"Warm chicken and vegetable salad","ua":"Теплий салат з куркою та овочами"}'::jsonb,
   '{"ru":"Сочная обжаренная курица на подушке из свежих овощей с лёгкой заправкой. Тёплое мясо и хрустящий салат — сытный ПП-обед, который не оставит тяжести.","en":"Juicy seared chicken on a bed of fresh vegetables with a light dressing. Warm meat and crisp salad — a filling healthy lunch that won''t weigh you down.","ua":"Соковита обсмажена курка на подушці зі свіжих овочів із легкою заправкою. Тепле м''ясо й хрусткий салат — ситний ПХ-обід, що не залишить тяжкості."}'::jsonb,
   '{"ru":["Куриное филе — 300 г","Салатный микс — 100 г","Помидоры черри — 150 г","Огурец — 1 шт.","Болгарский перец — 1 шт.","Оливковое масло — 2 ст. л.","Соевый соус — 1 ст. л.","Лимонный сок — 1 ст. л.","Соль и перец — по вкусу"],"en":["Chicken breast — 300 g","Salad mix — 100 g","Cherry tomatoes — 150 g","Cucumber — 1","Bell pepper — 1","Olive oil — 2 tbsp","Soy sauce — 1 tbsp","Lemon juice — 1 tbsp","Salt and pepper — to taste"],"ua":["Куряче філе — 300 г","Салатний мікс — 100 г","Помідори чері — 150 г","Огірок — 1 шт.","Болгарський перець — 1 шт.","Оливкова олія — 2 ст. л.","Соєвий соус — 1 ст. л.","Лимонний сік — 1 ст. л.","Сіль і перець — до смаку"]}'::jsonb,
   '{"ru":["Нарежьте курицу полосками и обжарьте до румяности.","Нарежьте овощи и выложите на тарелку с салатным миксом.","Смешайте масло, соевый соус и лимонный сок в заправку.","Выложите тёплую курицу поверх овощей.","Полейте заправкой и сразу подавайте, пока курица тёплая."],"en":["Slice the chicken into strips and sear until golden.","Chop the vegetables and arrange on a plate with the salad mix.","Mix oil, soy sauce and lemon juice into a dressing.","Place the warm chicken over the vegetables.","Drizzle with dressing and serve while the chicken is warm."],"ua":["Наріжте курку смужками й обсмажте до рум''яності.","Наріжте овочі й викладіть на тарілку із салатним міксом.","Змішайте олію, соєвий соус і лимонний сік у заправку.","Викладіть теплу курку поверх овочів.","Полийте заправкою й одразу подавайте, поки курка тепла."]}'::jsonb,
   '{"ru":["ПП","салат","курица","тёплый"],"en":["healthy","salad","chicken","warm"],"ua":["ПХ","салат","курка","теплий"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('salat-s-tuncom-i-fasolyu', 'salad', true, null, 15, 260, 3, 'easy',
   '{"ru":"Салат с тунцом и фасолью","en":"Tuna and bean salad","ua":"Салат з тунцем і квасолею"}'::jsonb,
   '{"ru":"Быстрый белковый салат из тунца, красной фасоли и свежих овощей с лёгкой заправкой. Готовится за 15 минут без варки — сытно, но легко.","en":"A quick protein salad of tuna, red beans and fresh vegetables with a light dressing. Ready in 15 minutes with no cooking — filling yet light.","ua":"Швидкий білковий салат із тунця, червоної квасолі та свіжих овочів із легкою заправкою. Готується за 15 хвилин без варіння — ситно, але легко."}'::jsonb,
   '{"ru":["Тунец консервированный — 240 г","Красная фасоль — 200 г","Помидоры — 2 шт.","Огурец — 1 шт.","Красный лук — половина","Кукуруза — 100 г","Оливковое масло — 2 ст. л.","Лимонный сок — 1 ст. л.","Зелень — по вкусу"],"en":["Canned tuna — 240 g","Red beans — 200 g","Tomatoes — 2","Cucumber — 1","Red onion — half","Sweetcorn — 100 g","Olive oil — 2 tbsp","Lemon juice — 1 tbsp","Herbs — to taste"],"ua":["Тунець консервований — 240 г","Червона квасоля — 200 г","Помідори — 2 шт.","Огірок — 1 шт.","Червона цибуля — половина","Кукурудза — 100 г","Оливкова олія — 2 ст. л.","Лимонний сік — 1 ст. л.","Зелень — до смаку"]}'::jsonb,
   '{"ru":["Слейте жидкость с тунца, фасоли и кукурузы.","Нарежьте помидоры, огурец и лук.","Соедините все ингредиенты в миске.","Заправьте маслом и лимонным соком, посолите.","Аккуратно перемешайте, чтобы тунец не превратился в пасту."],"en":["Drain the tuna, beans and sweetcorn.","Chop the tomatoes, cucumber and onion.","Combine all the ingredients in a bowl.","Dress with oil and lemon juice, then season.","Toss gently so the tuna doesn''t turn to paste."],"ua":["Злийте рідину з тунця, квасолі й кукурудзи.","Наріжте помідори, огірок і цибулю.","Поєднайте всі інгредієнти в мисці.","Заправте олією й лимонним соком, посоліть.","Обережно перемішайте, щоб тунець не перетворився на пасту."]}'::jsonb,
   '{"ru":["ПП","салат","тунец","быстро"],"en":["healthy","salad","tuna","quick"],"ua":["ПХ","салат","тунець","швидко"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('salat-s-krevetkami-i-avokado', 'salad', true, null, 20, 280, 2, 'easy',
   '{"ru":"Салат с креветками и авокадо","en":"Shrimp and avocado salad","ua":"Салат із креветками та авокадо"}'::jsonb,
   '{"ru":"Освежающий салат с сочными креветками, кремовым авокадо и черри под цитрусовой заправкой. Лёгкий, но эффектный — подойдёт и на ужин, и на праздничный стол.","en":"A refreshing salad of juicy shrimp, creamy avocado and cherry tomatoes in a citrus dressing. Light yet impressive — great for dinner or a special table.","ua":"Освіжаючий салат із соковитими креветками, кремовим авокадо й чері під цитрусовою заправкою. Легкий, але ефектний — підійде і на вечерю, і на святковий стіл."}'::jsonb,
   '{"ru":["Креветки — 250 г","Авокадо — 1 шт.","Помидоры черри — 150 г","Салатный микс — 80 г","Красный лук — половина","Оливковое масло — 2 ст. л.","Сок лайма — 1 ст. л.","Соль и перец — по вкусу"],"en":["Shrimp — 250 g","Avocado — 1","Cherry tomatoes — 150 g","Salad mix — 80 g","Red onion — half","Olive oil — 2 tbsp","Lime juice — 1 tbsp","Salt and pepper — to taste"],"ua":["Креветки — 250 г","Авокадо — 1 шт.","Помідори чері — 150 г","Салатний мікс — 80 г","Червона цибуля — половина","Оливкова олія — 2 ст. л.","Сік лайма — 1 ст. л.","Сіль і перець — до смаку"]}'::jsonb,
   '{"ru":["Обжарьте креветки 1–2 минуты и остудите.","Нарежьте авокадо, черри и лук.","Выложите салатный микс, сверху овощи и креветки.","Смешайте масло с соком лайма в заправку.","Полейте заправкой, посолите и сразу подавайте."],"en":["Sear the shrimp for 1–2 minutes and cool.","Slice the avocado, cherry tomatoes and onion.","Lay out the salad mix, then the vegetables and shrimp.","Mix oil with lime juice into a dressing.","Drizzle over, season and serve at once."],"ua":["Обсмажте креветки 1–2 хвилини й остудіть.","Наріжте авокадо, чері й цибулю.","Викладіть салатний мікс, зверху овочі й креветки.","Змішайте олію із соком лайма в заправку.","Полийте заправкою, посоліть і одразу подавайте."]}'::jsonb,
   '{"ru":["ПП","салат","креветки","авокадо"],"en":["healthy","salad","shrimp","avocado"],"ua":["ПХ","салат","креветки","авокадо"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('salat-kapreze', 'salad', true, null, 10, 230, 2, 'easy',
   '{"ru":"Салат «Капрезе»","en":"Caprese salad","ua":"Салат «Капрезе»"}'::jsonb,
   '{"ru":"Итальянская классика из трёх продуктов: сочные помидоры, моцарелла и базилик под оливковым маслом. Минимум усилий, максимум свежести — важно взять спелые томаты.","en":"An Italian classic of just three things: ripe tomatoes, mozzarella and basil with olive oil. Minimal effort, maximum freshness — ripe tomatoes are key.","ua":"Італійська класика із трьох продуктів: соковиті помідори, моцарела й базилік під оливковою олією. Мінімум зусиль, максимум свіжості — важливо взяти стиглі томати."}'::jsonb,
   '{"ru":["Помидоры — 3 шт.","Моцарелла — 200 г","Базилик свежий — пучок","Оливковое масло — 2 ст. л.","Бальзамический уксус — 1 ст. л.","Соль и перец — по вкусу"],"en":["Tomatoes — 3","Mozzarella — 200 g","Fresh basil — a bunch","Olive oil — 2 tbsp","Balsamic vinegar — 1 tbsp","Salt and pepper — to taste"],"ua":["Помідори — 3 шт.","Моцарела — 200 г","Свіжий базилік — пучок","Оливкова олія — 2 ст. л.","Бальзамічний оцет — 1 ст. л.","Сіль і перець — до смаку"]}'::jsonb,
   '{"ru":["Нарежьте помидоры и моцареллу кружочками.","Выложите их внахлёст, чередуя, на блюдо.","Разложите между ними листья базилика.","Полейте оливковым маслом и бальзамиком.","Посолите, поперчите и подавайте сразу."],"en":["Slice the tomatoes and mozzarella into rounds.","Arrange them overlapping and alternating on a plate.","Tuck basil leaves between them.","Drizzle with olive oil and balsamic.","Season and serve at once."],"ua":["Наріжте помідори й моцарелу кружечками.","Викладіть їх внапуск, чергуючи, на блюдо.","Розкладіть між ними листя базиліку.","Полийте оливковою олією та бальзаміком.","Посоліть, поперчіть і подавайте одразу."]}'::jsonb,
   '{"ru":["ПП","салат","капрезе","моцарелла"],"en":["healthy","salad","caprese","mozzarella"],"ua":["ПХ","салат","капрезе","моцарела"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

