-- Generated by scripts/export-sql.ts — paste into the Supabase SQL editor.
-- image is left NULL on purpose: attach the photo later from the admin panel
-- (the site shows a category placeholder cover until then).

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('domashnie-myasnye-kotlety', 'main', false, null, 40, 380, 4, 'medium',
   '{"ru":"Домашние сочные котлеты из говядины и свинины","en":"Juicy home-style beef & pork cutlets"}'::jsonb,
   '{"ru":"Классические котлеты из смеси говядины и свинины на размоченном в молоке хлебе — румяная корочка снаружи, сочность внутри. Вкус, знакомый с детства.","en":"Classic cutlets from a beef-and-pork mix on milk-soaked bread — a golden crust outside, juicy within. The taste everyone grew up with."}'::jsonb,
   '{"ru":["Говяжий фарш — 300 г","Свиной фарш — 300 г","Лук — 120 г","Белый хлеб — 80 г","Молоко — 120 мл","Яйцо — 1 шт","Чеснок — 1 зубчик","Панировочные сухари — 60 г","Масло для жарки — 30 мл","Соль — 8 г","Чёрный перец — по вкусу"],"en":["Beef mince — 300 g","Pork mince — 300 g","Onion — 120 g","White bread — 80 g","Milk — 120 ml","Egg — 1","Garlic — 1 clove","Breadcrumbs — 60 g","Oil for frying — 30 ml","Salt — 8 g","Black pepper — to taste"]}'::jsonb,
   '{"ru":["Замочите белый хлеб в молоке на 5 минут и отожмите.","Смешайте оба фарша с мелко нарезанным луком, чесноком, яйцом и хлебом; посолите и поперчите.","Вымешайте недолго, сформуйте котлеты и обваляйте в сухарях.","Обжарьте на среднем огне по 4–5 минут с каждой стороны до румяной корочки.","Совет: не вымешивайте фарш слишком долго — котлеты останутся нежными."],"en":["Soak the white bread in milk for 5 minutes and squeeze it out.","Combine both minces with finely chopped onion, garlic, egg and bread; season with salt and pepper.","Mix briefly, shape the cutlets and coat in breadcrumbs.","Fry over medium heat 4–5 minutes per side until golden.","Tip: don''t overwork the mince — the cutlets stay tender."]}'::jsonb,
   '{"ru":["ужин","мясо","классика"],"en":["dinner","meat","classic"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('pozharskie-kotlety', 'main', false, null, 50, 420, 4, 'medium',
   '{"ru":"Пожарские котлеты с хрустящей корочкой","en":"Pozharsky chicken cutlets with a crisp crust"}'::jsonb,
   '{"ru":"Нежнейшие куриные котлеты на сливках в панировке из хлебных кубиков, с кусочком масла внутри. Хрустят снаружи и тают во рту.","en":"The tenderest cream-enriched chicken cutlets in a cubed-bread crust, with a knob of butter hidden inside. Crunchy outside, melting within."}'::jsonb,
   '{"ru":["Куриное бедро без кожи — 600 г","Белый хлеб — 100 г","Сливки 20% — 100 мл","Лук — 80 г","Сливочное масло — 80 г","Белые сухари кубиками — 100 г","Масло для жарки — 25 мл","Соль — 7 г","Чёрный перец — по вкусу"],"en":["Skinless chicken thigh — 600 g","White bread — 100 g","Cream 20% — 100 ml","Onion — 80 g","Butter — 80 g","Cubed bread crumbs — 100 g","Oil for frying — 25 ml","Salt — 7 g","Black pepper — to taste"]}'::jsonb,
   '{"ru":["Замочите хлеб в сливках; измельчите куриное бедро с луком в фарш.","Смешайте фарш с хлебом, посолите, поперчите и охладите 20 минут.","В центр каждой котлеты вложите кусочек холодного масла и залепите.","Обваляйте котлеты в хлебной крошке-кубиках.","Обжарьте до румяности и доведите в духовке 8–10 минут при 180 °C.","Совет: работайте с холодным фаршем — так масло останется внутри."],"en":["Soak the bread in cream; mince the chicken thigh with the onion.","Mix the mince with the bread, season and chill for 20 minutes.","Tuck a piece of cold butter into the centre of each cutlet and seal.","Coat in the cubed bread crumbs.","Fry until golden, then finish in the oven 8–10 minutes at 180 °C.","Tip: keep the mince cold so the butter stays inside."]}'::jsonb,
   '{"ru":["ужин","курица","праздничное"],"en":["dinner","chicken","special"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('kurinye-kotlety-s-syrom', 'main', false, null, 45, 390, 4, 'medium',
   '{"ru":"Куриные котлеты с сырной начинкой","en":"Chicken cutlets with a melting cheese centre"}'::jsonb,
   '{"ru":"Сочные куриные котлеты с сырным сердцем, которое тянется при разломе. Секрет — плотно защипнуть края, чтобы сыр остался внутри.","en":"Juicy chicken cutlets with a molten cheese heart that stretches when you break them open. The trick is sealing the edges tightly."}'::jsonb,
   '{"ru":["Куриный фарш — 600 г","Твёрдый сыр — 150 г","Лук — 100 г","Яйцо — 1 шт","Панировочные сухари — 80 г","Сметана — 50 г","Чеснок — 1 зубчик","Масло для жарки — 25 мл","Соль — 7 г","Чёрный перец — по вкусу"],"en":["Chicken mince — 600 g","Hard cheese — 150 g","Onion — 100 g","Egg — 1","Breadcrumbs — 80 g","Sour cream — 50 g","Garlic — 1 clove","Oil for frying — 25 ml","Salt — 7 g","Black pepper — to taste"]}'::jsonb,
   '{"ru":["Смешайте куриный фарш с луком, чесноком, яйцом и сметаной; посолите и поперчите.","Расплющите порцию фарша на ладони, в центр положите брусочек сыра.","Плотно защипните края, формируя котлету, и обваляйте в сухарях.","Обжарьте на среднем огне по 4–5 минут с каждой стороны.","Совет: защипывайте края плотно, чтобы сыр не вытек."],"en":["Mix the chicken mince with onion, garlic, egg and sour cream; season.","Flatten a portion in your palm and place a stick of cheese in the centre.","Seal the edges tightly into a patty and coat in breadcrumbs.","Fry over medium heat 4–5 minutes per side.","Tip: seal the edges well so the cheese stays in."]}'::jsonb,
   '{"ru":["ужин","курица","сыр"],"en":["dinner","chicken","cheese"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('kotlety-iz-indeyki-s-kabachkom', 'main', true, null, 40, 260, 5, 'easy',
   '{"ru":"Нежные котлеты из индейки с кабачком","en":"Tender turkey & zucchini cutlets"}'::jsonb,
   '{"ru":"Лёгкие котлеты из индейки с сочным кабачком и овсяными хлопьями вместо хлеба. ПП-вариант, который держит форму и остаётся нежным.","en":"Light turkey cutlets with juicy zucchini and oats instead of bread. A healthy version that holds its shape and stays tender."}'::jsonb,
   '{"ru":["Фарш из индейки — 650 г","Кабачок — 250 г","Лук — 100 г","Яйцо — 1 шт","Овсяные хлопья — 50 г","Сметана — 40 г","Укроп — 15 г","Масло для жарки — 25 мл","Соль — 7 г","Чёрный перец — по вкусу"],"en":["Turkey mince — 650 g","Zucchini — 250 g","Onion — 100 g","Egg — 1","Rolled oats — 50 g","Sour cream — 40 g","Dill — 15 g","Oil for frying — 25 ml","Salt — 7 g","Black pepper — to taste"]}'::jsonb,
   '{"ru":["Натрите кабачок и хорошо отожмите лишнюю влагу.","Смешайте фарш индейки с кабачком, луком, яйцом, хлопьями, сметаной и укропом.","Дайте фаршу постоять 10 минут, чтобы хлопья набухли.","Сформуйте котлеты и обжарьте под крышкой по 5 минут с каждой стороны.","Совет: чем лучше отжат кабачок, тем легче котлеты держат форму."],"en":["Grate the zucchini and squeeze out the excess moisture well.","Mix the turkey mince with zucchini, onion, egg, oats, sour cream and dill.","Rest for 10 minutes so the oats swell.","Shape the cutlets and fry, covered, 5 minutes per side.","Tip: the better you squeeze the zucchini, the better they hold shape."]}'::jsonb,
   '{"ru":["ПП","ужин","индейка","кабачок"],"en":["healthy","dinner","turkey","zucchini"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('rybnye-kotlety-iz-mintaya', 'main', false, null, 45, 300, 4, 'medium',
   '{"ru":"Рыбные котлеты из минтая","en":"Pollock fish cutlets"}'::jsonb,
   '{"ru":"Мягкие и ароматные котлеты из филе минтая с укропом. Хлеб на молоке и кусочек масла делают их нежными и сочными.","en":"Soft, fragrant cutlets from pollock fillet with dill. Milk-soaked bread and a little butter keep them tender and moist."}'::jsonb,
   '{"ru":["Филе минтая — 700 г","Лук — 100 г","Белый хлеб — 80 г","Молоко — 100 мл","Яйцо — 1 шт","Сливочное масло — 40 г","Панировочные сухари — 80 г","Укроп — 10 г","Масло для жарки — 30 мл","Соль — 7 г","Чёрный перец — по вкусу"],"en":["Pollock fillet — 700 g","Onion — 100 g","White bread — 80 g","Milk — 100 ml","Egg — 1","Butter — 40 g","Breadcrumbs — 80 g","Dill — 10 g","Oil for frying — 30 ml","Salt — 7 g","Black pepper — to taste"]}'::jsonb,
   '{"ru":["Измельчите филе минтая с луком в фарш.","Добавьте размоченный в молоке хлеб, яйцо, мягкое масло и укроп; посолите.","Охладите фарш 20 минут, сформуйте котлеты и обваляйте в сухарях.","Обжарьте на среднем огне по 3–4 минуты с каждой стороны.","Совет: перед формовкой охладите фарш — он не будет липнуть."],"en":["Mince the pollock fillet with the onion.","Add milk-soaked bread, egg, soft butter and dill; season.","Chill for 20 minutes, shape and coat in breadcrumbs.","Fry over medium heat 3–4 minutes per side.","Tip: chill the mixture before shaping so it doesn''t stick."]}'::jsonb,
   '{"ru":["ужин","рыба","минтай"],"en":["dinner","fish","pollock"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('pechenochnye-kotlety-s-risom', 'main', false, null, 40, 310, 4, 'easy',
   '{"ru":"Печёночные котлеты с рисом и морковью","en":"Chicken-liver cutlets with rice"}'::jsonb,
   '{"ru":"Мягкие печёночные котлеты с варёным рисом и морковью. Быстро, бюджетно и по-настоящему сытно.","en":"Soft chicken-liver patties with boiled rice and carrot. Quick, budget-friendly and genuinely filling."}'::jsonb,
   '{"ru":["Куриная печень — 500 г","Варёный рис — 180 г","Лук — 120 г","Морковь — 100 г","Яйцо — 1 шт","Мука — 60 г","Сметана — 50 г","Масло для жарки — 30 мл","Соль — 7 г","Чёрный перец — по вкусу"],"en":["Chicken liver — 500 g","Boiled rice — 180 g","Onion — 120 g","Carrot — 100 g","Egg — 1","Flour — 60 g","Sour cream — 50 g","Oil for frying — 30 ml","Salt — 7 g","Black pepper — to taste"]}'::jsonb,
   '{"ru":["Измельчите печень с луком блендером до однородности.","Смешайте с варёным рисом, тёртой морковью, яйцом, мукой и сметаной; посолите.","Выкладывайте массу ложкой на разогретую сковороду.","Обжарьте по 3–4 минуты с каждой стороны на среднем огне.","Совет: не делайте котлеты толстыми — так они прожарятся равномерно."],"en":["Blend the liver with the onion until smooth.","Mix with boiled rice, grated carrot, egg, flour and sour cream; season.","Spoon the mixture onto a hot pan.","Fry 3–4 minutes per side over medium heat.","Tip: keep them thin so they cook through evenly."]}'::jsonb,
   '{"ru":["ужин","печень","бюджетно"],"en":["dinner","liver","budget"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('kartofelnye-kotlety-s-gribami', 'main', false, null, 60, 340, 4, 'medium',
   '{"ru":"Картофельные котлеты с грибной начинкой","en":"Potato cutlets stuffed with mushrooms"}'::jsonb,
   '{"ru":"Пышные картофельные котлеты с сочной начинкой из жареных шампиньонов внутри и хрустящей панировкой снаружи.","en":"Fluffy potato cutlets with a juicy fried-mushroom filling inside and a crunchy crust outside."}'::jsonb,
   '{"ru":["Картофель — 800 г","Шампиньоны — 300 г","Лук — 120 г","Яйцо — 1 шт","Мука — 70 г","Панировочные сухари — 100 г","Сливочное масло — 20 г","Масло для жарки — 40 мл","Соль — 8 г","Чёрный перец — по вкусу"],"en":["Potatoes — 800 g","Mushrooms — 300 g","Onion — 120 g","Egg — 1","Flour — 70 g","Breadcrumbs — 100 g","Butter — 20 g","Oil for frying — 40 ml","Salt — 8 g","Black pepper — to taste"]}'::jsonb,
   '{"ru":["Отварите картофель и разомните в пюре с маслом, остудите.","Обжарьте нарезанные грибы с луком до золотистого цвета.","Из картофельной массы сформуйте лепёшку, спрячьте внутрь грибную начинку и залепите.","Обваляйте в муке и сухарях, обжарьте до румяной корочки.","Совет: картофельная масса должна полностью остыть, иначе котлеты расплывутся."],"en":["Boil the potatoes and mash with butter, then cool.","Fry the chopped mushrooms with onion until golden.","Shape a potato patty, hide the mushroom filling inside and seal.","Coat in flour and breadcrumbs, fry until golden.","Tip: the potato must be fully cold or the cutlets spread."]}'::jsonb,
   '{"ru":["ужин","картофель","грибы","вегетарианское"],"en":["dinner","potato","mushrooms","vegetarian"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('grechnevye-kotlety-s-gribami', 'main', false, null, 40, 290, 4, 'easy',
   '{"ru":"Гречневые котлеты с грибами","en":"Buckwheat & mushroom cutlets"}'::jsonb,
   '{"ru":"Постные котлеты из варёной гречки с ароматными шампиньонами. Интересная текстура — если измельчить лишь половину крупы.","en":"Lean cutlets of boiled buckwheat with fragrant mushrooms. Blend only half the grain for a more interesting texture."}'::jsonb,
   '{"ru":["Варёная гречка — 500 г","Шампиньоны — 250 г","Лук — 120 г","Яйца — 2 шт","Мука — 50 г","Сметана — 40 г","Панировочные сухари — 80 г","Масло для жарки — 30 мл","Соль — 7 г","Чёрный перец — по вкусу"],"en":["Boiled buckwheat — 500 g","Mushrooms — 250 g","Onion — 120 g","Eggs — 2","Flour — 50 g","Sour cream — 40 g","Breadcrumbs — 80 g","Oil for frying — 30 ml","Salt — 7 g","Black pepper — to taste"]}'::jsonb,
   '{"ru":["Обжарьте нарезанные грибы с луком до готовности.","Смешайте гречку с грибами, яйцами, мукой и сметаной; посолите.","Сформуйте котлеты и обваляйте в сухарях.","Обжарьте на среднем огне по 3–4 минуты с каждой стороны.","Совет: измельчите блендером только половину гречки — текстура будет интереснее."],"en":["Fry the chopped mushrooms with onion until done.","Mix buckwheat with mushrooms, eggs, flour and sour cream; season.","Shape the cutlets and coat in breadcrumbs.","Fry over medium heat 3–4 minutes per side.","Tip: blend only half the buckwheat for a better texture."]}'::jsonb,
   '{"ru":["ужин","гречка","грибы","постное"],"en":["dinner","buckwheat","mushrooms","lean"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('kapustnye-kotlety-s-syrom', 'main', false, null, 45, 270, 4, 'easy',
   '{"ru":"Капустные котлеты с тянущимся сыром","en":"Cabbage cutlets with melty cheese"}'::jsonb,
   '{"ru":"Мягкие котлеты из тушёной капусты с манкой и сыром, который тянется при разломе. Хрустящая корочка и нежная середина.","en":"Soft cutlets of braised cabbage with semolina and cheese that stretches when broken. Crisp crust, tender middle."}'::jsonb,
   '{"ru":["Белокочанная капуста — 700 г","Твёрдый сыр — 150 г","Лук — 100 г","Яйца — 2 шт","Манная крупа — 80 г","Молоко — 100 мл","Панировочные сухари — 80 г","Укроп — 10 г","Масло для жарки — 30 мл","Соль — 7 г","Чёрный перец — по вкусу"],"en":["White cabbage — 700 g","Hard cheese — 150 g","Onion — 100 g","Eggs — 2","Semolina — 80 g","Milk — 100 ml","Breadcrumbs — 80 g","Dill — 10 g","Oil for frying — 30 ml","Salt — 7 g","Black pepper — to taste"]}'::jsonb,
   '{"ru":["Нашинкуйте капусту и потушите с луком и молоком до мягкости.","Всыпьте манку, перемешайте и дайте постоять, пока масса загустеет.","Вмешайте тёртый сыр, яйца и укроп; посолите и остудите.","Сформуйте котлеты, обваляйте в сухарях и обжарьте до румяной корочки.","Совет: перед формовкой полностью остудите капустную массу."],"en":["Shred the cabbage and braise with onion and milk until soft.","Stir in the semolina and rest until the mixture thickens.","Fold in grated cheese, eggs and dill; season and cool.","Shape the cutlets, coat in breadcrumbs and fry until golden.","Tip: cool the cabbage mixture fully before shaping."]}'::jsonb,
   '{"ru":["ужин","капуста","сыр","вегетарианское"],"en":["dinner","cabbage","cheese","vegetarian"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

