-- Generated by scripts/export-sql.ts — paste into the Supabase SQL editor.
-- image is left NULL on purpose: attach the photo later from the admin panel
-- (the site shows a category placeholder cover until then).

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('krevetki-v-chesnochnom-masle', 'main', false, null, 15, 240, 2, 'easy',
   '{"ru":"Креветки в чесночном масле","en":"Garlic butter shrimp"}'::jsonb,
   '{"ru":"Сочные креветки, обжаренные в сливочном масле с чесноком и петрушкой, с яркой ноткой лимона. Соус со дна сковороды — отдельное удовольствие, которое хочется собрать хлебом.","en":"Juicy shrimp seared in butter with garlic and parsley and a bright squeeze of lemon. The sauce left in the pan is a treat all its own — perfect for mopping up with bread."}'::jsonb,
   '{"ru":["Креветки — 400 г","Сливочное масло — 40 г","Чеснок — 3 зубчика","Лимон — ½ шт","Петрушка — небольшой пучок","Соль — по вкусу","Чёрный перец — по вкусу"],"en":["Shrimp — 400 g","Butter — 40 g","Garlic — 3 cloves","Lemon — ½","Parsley — a small bunch","Salt — to taste","Black pepper — to taste"]}'::jsonb,
   '{"ru":["Обсушите креветки и обжарьте на разогретой сковороде по 1–2 минуты с каждой стороны.","Добавьте сливочное масло и измельчённый чеснок, прогрейте ещё 30 секунд.","Снимите с огня, посолите, поперчите и полейте лимонным соком.","Посыпьте рубленой петрушкой и сразу подавайте.","Совет: не пережаривайте — как только креветки стали розовыми и плотными, они готовы."],"en":["Pat the shrimp dry and sear on a hot pan 1–2 minutes per side.","Add the butter and minced garlic, warm for another 30 seconds.","Take off the heat, season and pour over the lemon juice.","Scatter with chopped parsley and serve at once.","Tip: don''t overcook — once the shrimp turn pink and firm, they''re done."]}'::jsonb,
   '{"ru":["ужин","креветки","чеснок","быстро"],"en":["dinner","shrimp","garlic","quick"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('krevetki-medovo-chili', 'main', false, null, 15, 260, 2, 'easy',
   '{"ru":"Креветки медово-чили","en":"Honey-chili shrimp"}'::jsonb,
   '{"ru":"Креветки в блестящей медово-чили глазури: сладкое встречается с острым, а соевый соус и лайм добавляют глубины. Ровно тот баланс, из-за которого тарелка пустеет первой.","en":"Shrimp in a glossy honey-chili glaze where sweet meets heat, rounded out by soy and lime. Exactly the balance that empties the plate first."}'::jsonb,
   '{"ru":["Креветки — 400 г","Мёд — 1 ст. л.","Соевый соус — 2 ст. л.","Сладкий чили-соус — 2 ст. л.","Чеснок — 2 зубчика","Сок лайма — 1 ст. л.","Зелёный лук — для подачи"],"en":["Shrimp — 400 g","Honey — 1 tbsp","Soy sauce — 2 tbsp","Sweet chili sauce — 2 tbsp","Garlic — 2 cloves","Lime juice — 1 tbsp","Spring onion — to serve"]}'::jsonb,
   '{"ru":["Смешайте мёд, соевый соус, сладкий чили, измельчённый чеснок и сок лайма.","Обжарьте креветки на сильном огне 2–3 минуты.","Влейте соус и прогрейте ещё минуту до густой блестящей глазури.","Подавайте, посыпав зелёным луком.","Совет: держите огонь сильным, чтобы соус карамелизовался, а не выпаривался."],"en":["Mix the honey, soy sauce, sweet chili, minced garlic and lime juice.","Sear the shrimp over high heat for 2–3 minutes.","Pour in the sauce and cook another minute to a thick, glossy glaze.","Serve scattered with spring onion.","Tip: keep the heat high so the sauce caramelises rather than just steams."]}'::jsonb,
   '{"ru":["ужин","креветки","острое","азиатское"],"en":["dinner","shrimp","spicy","asian"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('krevetki-v-slivochnom-souse', 'main', false, null, 20, 340, 2, 'easy',
   '{"ru":"Креветки в сливочном соусе","en":"Creamy garlic parmesan shrimp"}'::jsonb,
   '{"ru":"Нежные креветки в бархатистом сливочном соусе с чесноком и пармезаном. Тот случай, когда соус хочется собрать со сковороды хлебом до последней капли.","en":"Tender shrimp in a velvety cream sauce with garlic and parmesan. The kind of sauce you''ll want to wipe out of the pan with bread to the last drop."}'::jsonb,
   '{"ru":["Креветки — 400 г","Сливки 20% — 200 мл","Пармезан — 50 г","Чеснок — 2 зубчика","Сливочное масло — 20 г","Соль — по вкусу","Чёрный перец — по вкусу"],"en":["Shrimp — 400 g","Cream 20% — 200 ml","Parmesan — 50 g","Garlic — 2 cloves","Butter — 20 g","Salt — to taste","Black pepper — to taste"]}'::jsonb,
   '{"ru":["Обжарьте креветки на масле 1–2 минуты и уберите со сковороды.","В той же сковороде прогрейте чеснок, влейте сливки и добавьте тёртый пармезан.","Прогрейте соус до загустения, посолите и поперчите.","Верните креветки в соус ещё на 1 минуту и подавайте.","Совет: снимайте креветки заранее, чтобы они не стали резиновыми, пока густеет соус."],"en":["Sear the shrimp in butter for 1–2 minutes and remove from the pan.","In the same pan warm the garlic, pour in the cream and add grated parmesan.","Simmer the sauce until it thickens, then season.","Return the shrimp to the sauce for 1 more minute and serve.","Tip: pull the shrimp early so they don''t turn rubbery while the sauce reduces."]}'::jsonb,
   '{"ru":["ужин","креветки","сливки","пармезан"],"en":["dinner","shrimp","cream","parmesan"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('hrustyaschie-krevetki', 'snack', false, null, 25, 320, 3, 'medium',
   '{"ru":"Хрустящие креветки в панировке","en":"Crispy breaded shrimp"}'::jsonb,
   '{"ru":"Креветки в золотистой панировке из сухарей с паприкой — хрустящие снаружи и сочные внутри. Идеальная закуска под белый соус: макаешь — и пропал.","en":"Shrimp in a golden paprika-breadcrumb coating — crunchy outside, juicy within. The ideal dipping snack: one dunk in the white sauce and you''re hooked."}'::jsonb,
   '{"ru":["Креветки — 400 г","Яйцо — 1 шт","Панировочные сухари — 80 г","Мука — 3 ст. л.","Паприка — 1 ч. л.","Соль — по вкусу","Масло для жарки — по необходимости"],"en":["Shrimp — 400 g","Egg — 1","Breadcrumbs — 80 g","Flour — 3 tbsp","Paprika — 1 tsp","Salt — to taste","Oil for frying — as needed"]}'::jsonb,
   '{"ru":["Смешайте сухари с паприкой и солью.","Обваляйте креветки в муке, затем во взбитом яйце и в сухарях.","Обжарьте во фритюре или на сковороде до золотистой корочки — либо запеките до хруста.","Обсушите на бумажном полотенце и подавайте с белым соусом.","Совет: для более лёгкого варианта запеките креветки в духовке при 200 °C, сбрызнув маслом."],"en":["Mix the breadcrumbs with paprika and salt.","Coat the shrimp in flour, then beaten egg, then breadcrumbs.","Deep-fry or pan-fry until golden — or bake until crisp.","Drain on paper towel and serve with a white dipping sauce.","Tip: for a lighter version, bake at 200 °C with a spritz of oil."]}'::jsonb,
   '{"ru":["закуска","креветки","хрустящее","фритюр"],"en":["snack","shrimp","crispy","fried"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('kokosovoe-karri-s-krevetkami', 'main', false, null, 25, 360, 3, 'easy',
   '{"ru":"Кокосовое карри с креветками","en":"Coconut shrimp curry"}'::jsonb,
   '{"ru":"Креветки в нежном кокосовом соусе с карри, имбирём и лаймом — пряное, ароматное и совсем не сложное. Подавайте с рассыпчатым рисом.","en":"Shrimp in a gentle coconut sauce with curry, ginger and lime — spiced, fragrant and genuinely easy. Serve with fluffy rice."}'::jsonb,
   '{"ru":["Креветки — 400 г","Кокосовое молоко — 250 мл","Карри — 1 ч. л.","Чеснок — 2 зубчика","Имбирь — 1 ч. л.","Сок лайма — по вкусу","Кинза — для подачи","Рис — для подачи"],"en":["Shrimp — 400 g","Coconut milk — 250 ml","Curry powder — 1 tsp","Garlic — 2 cloves","Ginger — 1 tsp","Lime juice — to taste","Cilantro — to serve","Rice — to serve"]}'::jsonb,
   '{"ru":["Прогрейте на сковороде измельчённый чеснок, имбирь и карри до аромата.","Влейте кокосовое молоко и доведите до лёгкого кипения.","Добавьте креветки и готовьте 3–4 минуты до готовности.","В конце влейте сок лайма, посыпьте кинзой и подавайте с рисом.","Совет: не кипятите соус слишком долго — креветки станут жёсткими."],"en":["Warm the minced garlic, ginger and curry in a pan until fragrant.","Pour in the coconut milk and bring to a gentle simmer.","Add the shrimp and cook 3–4 minutes until done.","Finish with lime juice, scatter cilantro and serve with rice.","Tip: don''t over-simmer the sauce or the shrimp turn tough."]}'::jsonb,
   '{"ru":["ужин","креветки","карри","кокос"],"en":["dinner","shrimp","curry","coconut"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('krevetki-teriyaki', 'main', false, null, 15, 280, 2, 'easy',
   '{"ru":"Креветки терияки","en":"Teriyaki shrimp"}'::jsonb,
   '{"ru":"Креветки в блестящей глазури терияки из соевого соуса, мёда, чеснока и имбиря, посыпанные кунжутом. Подайте с рисом — и ужин готов за 15 минут.","en":"Shrimp in a shiny teriyaki glaze of soy, honey, garlic and ginger, finished with sesame. Serve over rice and dinner is done in 15 minutes."}'::jsonb,
   '{"ru":["Креветки — 400 г","Соевый соус — 3 ст. л.","Мёд — 1 ст. л.","Чеснок — 2 зубчика","Имбирь — ½ ч. л.","Кунжут — для подачи","Зелёный лук — для подачи","Рис — для подачи"],"en":["Shrimp — 400 g","Soy sauce — 3 tbsp","Honey — 1 tbsp","Garlic — 2 cloves","Ginger — ½ tsp","Sesame seeds — to serve","Spring onion — to serve","Rice — to serve"]}'::jsonb,
   '{"ru":["Смешайте соевый соус, мёд, измельчённый чеснок и имбирь.","Обжарьте креветки на сильном огне 2 минуты.","Влейте соус и готовьте ещё минуту до красивой блестящей глазури.","Посыпьте кунжутом и зелёным луком, подавайте с рисом.","Совет: соус загустеет быстро — снимайте с огня, как только он станет глянцевым."],"en":["Mix the soy sauce, honey, minced garlic and ginger.","Sear the shrimp over high heat for 2 minutes.","Pour in the sauce and cook another minute to a glossy glaze.","Scatter with sesame and spring onion and serve with rice.","Tip: the sauce thickens fast — pull it off the heat as soon as it turns glossy."]}'::jsonb,
   '{"ru":["ужин","креветки","терияки","азиатское"],"en":["dinner","shrimp","teriyaki","asian"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('limonno-perechnye-krevetki', 'main', false, null, 10, 220, 2, 'easy',
   '{"ru":"Лимонно-перечные креветки","en":"Lemon pepper shrimp"}'::jsonb,
   '{"ru":"Креветки, обжаренные до румяности со сливочным маслом, чесноком, свежемолотым перцем и цедрой лимона. Свежо, сочно и готово за 10 минут.","en":"Shrimp seared golden with butter, garlic, cracked pepper and lemon zest. Fresh, juicy and ready in 10 minutes."}'::jsonb,
   '{"ru":["Креветки — 400 г","Сливочное масло — 30 г","Лимон — 1 шт","Чеснок — 2 зубчика","Чёрный перец — по вкусу","Соль — по вкусу"],"en":["Shrimp — 400 g","Butter — 30 g","Lemon — 1","Garlic — 2 cloves","Black pepper — to taste","Salt — to taste"]}'::jsonb,
   '{"ru":["Обжарьте креветки на сухой разогретой сковороде до румяности.","Добавьте сливочное масло и измельчённый чеснок.","Всыпьте свежемолотый чёрный перец, добавьте цедру и сок лимона.","Посолите, прогрейте ещё несколько секунд и подавайте.","Совет: перчите свежемолотым перцем прямо в сковороду — аромат будет ярче."],"en":["Sear the shrimp on a hot dry pan until golden.","Add the butter and minced garlic.","Add freshly cracked black pepper, then lemon zest and juice.","Season with salt, warm a few more seconds and serve.","Tip: grind the pepper fresh straight into the pan for a brighter aroma."]}'::jsonb,
   '{"ru":["ужин","креветки","лимон","быстро"],"en":["dinner","shrimp","lemon","quick"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('pasta-s-krevetkami', 'main', false, null, 25, 520, 2, 'easy',
   '{"ru":"Паста с креветками в сливочном соусе","en":"Creamy shrimp pasta"}'::jsonb,
   '{"ru":"Спагетти с креветками в сливочном соусе с чесноком и пармезаном — тот самый ужин «как в ресторане», который легко приготовить дома за 25 минут.","en":"Spaghetti and shrimp in a creamy garlic-parmesan sauce — that restaurant-style dinner you can make at home in 25 minutes."}'::jsonb,
   '{"ru":["Спагетти — 200 г","Креветки — 300 г","Сливки — 150 мл","Пармезан — 40 г","Чеснок — 2 зубчика","Сливочное масло — 20 г","Соль — по вкусу","Чёрный перец — по вкусу"],"en":["Spaghetti — 200 g","Shrimp — 300 g","Cream — 150 ml","Parmesan — 40 g","Garlic — 2 cloves","Butter — 20 g","Salt — to taste","Black pepper — to taste"]}'::jsonb,
   '{"ru":["Отварите спагетти до состояния аль денте и слейте воду, сохранив немного отвара.","Обжарьте креветки с чесноком на сливочном масле 1–2 минуты.","Влейте сливки и добавьте тёртый пармезан, прогрейте до загустения.","Соедините с пастой, при необходимости добавьте немного отвара и прогрейте 1 минуту.","Совет: ложка воды от пасты сделает соус шелковистым и обволакивающим."],"en":["Boil the spaghetti al dente and drain, keeping a little cooking water.","Sear the shrimp with garlic in butter for 1–2 minutes.","Pour in the cream and add grated parmesan, simmer until thickened.","Toss with the pasta, loosen with a splash of the water and warm for 1 minute.","Tip: a spoon of pasta water makes the sauce silky and clingy."]}'::jsonb,
   '{"ru":["ужин","креветки","паста","сливки"],"en":["dinner","shrimp","pasta","cream"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

