-- Generated by scripts/export-sql.ts — paste into the Supabase SQL editor.
-- image is left NULL on purpose: attach the photo later from the admin panel
-- (the site shows a category placeholder cover until then).

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('zolotye-lukovye-kolca-v-pivnom-klyare', 'snack', false, null, 30, 320, 4, 'medium',
   '{"ru":"Золотые луковые кольца в пивном кляре","en":"Golden onion rings in beer batter"}'::jsonb,
   '{"ru":"Хрустящая корочка, воздушное тесто на газировке и сладкий лук внутри — закуска, которая исчезает со стола первой.","en":"A shell that shatters, airy sparkling-water batter and sweet onion inside — the snack that vanishes first."}'::jsonb,
   '{"ru":["Лук крупный — 3 шт","Мука — 120 г","Крахмал — 40 г","Яйцо — 1 шт","Газированная вода — 160 мл","Панировочные сухари — 100 г","Паприка — 1 ч. л.","Сметана — 90 г","Чеснок — 1 зубчик","Петрушка — 8 г","Масло для фритюра — 500 мл","Соль, перец — по вкусу"],"en":["Large onions — 3","Flour — 120 g","Starch — 40 g","Egg — 1","Sparkling water — 160 ml","Breadcrumbs — 100 g","Paprika — 1 tsp","Sour cream — 90 g","Garlic — 1 clove","Parsley — 8 g","Oil for deep-frying — 500 ml","Salt, pepper — to taste"]}'::jsonb,
   '{"ru":["Нарежьте лук кольцами толщиной 1 см и разберите на отдельные кольца.","Смешайте муку, крахмал, яйцо и газированную воду до гладкого кляра, приправьте паприкой, солью и перцем.","Обмакните каждое кольцо в кляр, затем обваляйте в сухарях.","Жарьте в разогретом масле по 2–3 минуты до золотистого цвета, выложите на салфетку.","Смешайте сметану с тёртым чесноком и петрушкой; подавайте кольца горячими с соусом."],"en":["Slice the onions into 1 cm rings and separate them.","Whisk flour, starch, egg and sparkling water into a smooth batter; season with paprika, salt and pepper.","Dip each ring in the batter, then coat in breadcrumbs.","Fry in hot oil 2–3 minutes until golden; drain on paper.","Stir sour cream with grated garlic and parsley; serve the rings hot with the dip."]}'::jsonb,
   '{"ru":["закуски к пиву","жареное","хрустящее"],"en":["beer snacks","fried","crunchy"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('kartofelnye-dolki-s-paprikoy', 'snack', false, null, 40, 280, 4, 'easy',
   '{"ru":"Картофельные дольки с паприкой и чесночным дипом","en":"Paprika potato wedges with garlic dip"}'::jsonb,
   '{"ru":"Запечённые до румяной корочки дольки с копчёной паприкой и прохладный чесночный соус — простая закуска, которая работает всегда.","en":"Wedges roasted to a crisp edge with smoky paprika and a cool garlic dip — a simple snack that always works."}'::jsonb,
   '{"ru":["Картофель — 800 г","Растительное масло — 35 мл","Паприка — 1,5 ч. л.","Сушёный чеснок — 1 ч. л.","Сметана — 100 г","Свежий чеснок — 1 зубчик","Укроп — 15 г","Соль — 1 ч. л.","Перец — по вкусу"],"en":["Potatoes — 800 g","Vegetable oil — 35 ml","Paprika — 1.5 tsp","Dried garlic — 1 tsp","Sour cream — 100 g","Fresh garlic — 1 clove","Dill — 15 g","Salt — 1 tsp","Pepper — to taste"]}'::jsonb,
   '{"ru":["Нарежьте картофель дольками, промойте от лишнего крахмала и обсушите насухо.","Смешайте масло, паприку, сушёный чеснок, соль и перец.","Обваляйте дольки в специях и разложите на противне в один слой.","Запекайте при 200 °C 30 минут до румяной корочки.","Смешайте сметану со свежим чесноком и укропом; подавайте дип отдельно, чтобы корочка не размокла."],"en":["Cut the potatoes into wedges, rinse off excess starch and pat completely dry.","Mix oil, paprika, dried garlic, salt and pepper.","Coat the wedges and spread on a tray in a single layer.","Roast at 200 °C for 30 minutes until golden.","Stir sour cream with fresh garlic and dill; serve the dip on the side so the crust stays crisp."]}'::jsonb,
   '{"ru":["закуски к пиву","запечённое","картофель"],"en":["beer snacks","baked","potato"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('syrnye-palochki-v-dvoynoy-panirovke', 'snack', false, null, 35, 360, 4, 'medium',
   '{"ru":"Сырные палочки в двойной панировке","en":"Double-crumbed cheese sticks"}'::jsonb,
   '{"ru":"Хрустящая оболочка снаружи и тянущийся сыр внутри. Секрет — подморозить сыр и запанировать дважды, чтобы он не вытек.","en":"A crunchy shell outside and molten, stretchy cheese inside. The trick: freeze the cheese and crumb it twice so it never leaks."}'::jsonb,
   '{"ru":["Твёрдый сыр — 300 г","Яйца — 2 шт","Мука — 60 г","Панировочные сухари — 130 г","Паприка — 1/2 ч. л.","Сметана — 90 г","Чеснок — 1 зубчик","Петрушка — 10 г","Масло для фритюра — 400 мл","Соль, перец — по вкусу"],"en":["Hard cheese — 300 g","Eggs — 2","Flour — 60 g","Breadcrumbs — 130 g","Paprika — 1/2 tsp","Sour cream — 90 g","Garlic — 1 clove","Parsley — 10 g","Oil for deep-frying — 400 ml","Salt, pepper — to taste"]}'::jsonb,
   '{"ru":["Нарежьте сыр брусочками и подморозьте 20 минут.","Обваляйте каждый брусочек в муке, затем в яйце и сухарях.","Повторите панировку (яйцо и сухари) второй раз для прочной корочки.","Обжарьте в горячем масле 1–2 минуты до золота и сразу выложите на салфетку.","Смешайте сметану с чесноком и петрушкой; подавайте немедленно, пока сыр тянется."],"en":["Cut the cheese into batons and freeze for 20 minutes.","Coat each baton in flour, then egg and breadcrumbs.","Repeat the egg-and-crumb coat a second time for a sturdy shell.","Fry in hot oil 1–2 minutes until golden and drain at once.","Stir sour cream with garlic and parsley; serve immediately while the cheese pulls."]}'::jsonb,
   '{"ru":["закуски к пиву","сыр","жареное"],"en":["beer snacks","cheese","fried"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('kurinye-krylya-v-medovo-chesnochnoy-glazuri', 'main', false, null, 70, 430, 4, 'medium',
   '{"ru":"Куриные крылья в медово-чесночной глазури","en":"Honey-garlic glazed chicken wings"}'::jsonb,
   '{"ru":"Липкая блестящая глазурь, обожжённая жаром духовки, с кунжутом и лимоном. Мёд добавляется в конце, чтобы не сгорел.","en":"A sticky, glossy glaze caramelised by oven heat, finished with sesame and lemon. The honey goes on late so it never burns."}'::jsonb,
   '{"ru":["Куриные крылья — 900 г","Мёд — 2 ст. л.","Соевый соус — 45 мл","Чеснок — 3 зубчика","Паприка — 1 ч. л.","Растительное масло — 25 мл","Лимон — 1/2 шт","Кунжут — 1 ч. л.","Петрушка — 10 г","Соль, перец — по вкусу"],"en":["Chicken wings — 900 g","Honey — 2 tbsp","Soy sauce — 45 ml","Garlic — 3 cloves","Paprika — 1 tsp","Vegetable oil — 25 ml","Lemon — 1/2","Sesame — 1 tsp","Parsley — 10 g","Salt, pepper — to taste"]}'::jsonb,
   '{"ru":["Разделите крылья на части и хорошо обсушите кожу — так корочка будет лучше.","Смешайте маринад из мёда, соевого соуса, чеснока, паприки и масла.","Обмажьте крылья и оставьте на 20 минут.","Разложите на противень и запекайте при 200 °C 25 минут.","Смажьте оставшейся глазурью и допеките 5 минут; посыпьте кунжутом и петрушкой, сбрызните лимоном."],"en":["Joint the wings and pat the skin very dry for a better crust.","Mix a marinade of honey, soy sauce, garlic, paprika and oil.","Coat the wings and rest for 20 minutes.","Spread on a tray and bake at 200 °C for 25 minutes.","Brush with the remaining glaze and bake 5 minutes more; scatter sesame and parsley, squeeze over lemon."]}'::jsonb,
   '{"ru":["закуски к пиву","курица","запечённое"],"en":["beer snacks","chicken","baked"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('rzhanye-grenki-s-chesnokom-i-syrnym-dipom', 'snack', false, null, 30, 250, 6, 'easy',
   '{"ru":"Ржаные гренки с чесноком и сырным дипом","en":"Rye garlic croutons with cheese dip"}'::jsonb,
   '{"ru":"Ароматные ржаные брусочки, запечённые до хруста в чесночном масле, и тёплый сырный соус на сливках. Классика к пиву без фритюра.","en":"Fragrant rye batons baked crisp in garlic butter, with a warm cream-and-cheese dip. A beer classic without the deep fryer."}'::jsonb,
   '{"ru":["Ржаной хлеб — 350 г","Чеснок — 3 зубчика","Растительное масло — 35 мл","Твёрдый сыр — 120 г","Сливки 20% — 140 мл","Петрушка — 10 г","Паприка — 1/2 ч. л.","Соль, перец — по вкусу"],"en":["Rye bread — 350 g","Garlic — 3 cloves","Vegetable oil — 35 ml","Hard cheese — 120 g","Cream 20% — 140 ml","Parsley — 10 g","Paprika — 1/2 tsp","Salt, pepper — to taste"]}'::jsonb,
   '{"ru":["Нарежьте хлеб одинаковыми брусочками.","Смешайте масло с тёртым чесноком, паприкой и солью и смажьте брусочки.","Запекайте при 180 °C 12–15 минут до хруста.","Прогрейте сливки на слабом огне, всыпьте тёртый сыр и растопите до гладкости, не доводя до кипения.","Подавайте гренки сразу с тёплым сырным дипом."],"en":["Cut the bread into even batons.","Mix oil with grated garlic, paprika and salt and brush the batons.","Bake at 180 °C for 12–15 minutes until crisp.","Warm the cream over low heat, add grated cheese and melt smooth without boiling.","Serve the croutons right away with the warm cheese dip."]}'::jsonb,
   '{"ru":["закуски к пиву","гренки","запечённое"],"en":["beer snacks","croutons","baked"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

