-- Generated by scripts/export-sql.ts — paste into the Supabase SQL editor.
-- image is left NULL on purpose: attach the photo later from the admin panel
-- (the site shows a category placeholder cover until then).

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('ovsyanka-s-yagodami', 'breakfast', true, null, 10, 320, 1, 'easy',
   '{"ru":"Овсянка с ягодами и орехами","en":"Berry & nut oatmeal"}'::jsonb,
   '{"ru":"Тёплый завтрак, который заряжает энергией на полдня. Готовится, пока варится кофе.","en":"A warm breakfast that fuels half your day. Ready before the coffee is."}'::jsonb,
   '{"ru":["Овсяные хлопья — 50 г","Молоко или вода — 200 мл","Банан — 1/2 шт","Горсть ягод (свежих или замороженных)","Грецкие орехи — 15 г","Мёд — 1 ч. л. (по желанию)"],"en":["Rolled oats — 50 g","Milk or water — 200 ml","Banana — 1/2","A handful of berries (fresh or frozen)","Walnuts — 15 g","Honey — 1 tsp (optional)"]}'::jsonb,
   '{"ru":["Залейте хлопья молоком и доведите до кипения на среднем огне.","Варите 4–5 минут, помешивая, до кремовой текстуры.","Снимите с огня, добавьте нарезанный банан.","Выложите в тарелку, сверху — ягоды, орехи и мёд."],"en":["Cover the oats with milk and bring to a boil over medium heat.","Simmer 4–5 minutes, stirring, until creamy.","Off the heat, fold in the sliced banana.","Serve topped with berries, nuts and honey."]}'::jsonb,
   '{"ru":["завтрак","быстро","полезно"],"en":["breakfast","quick","healthy"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('tost-s-avokado-i-yaycom', 'breakfast', true, null, 12, 380, 1, 'easy',
   '{"ru":"Тост с авокадо и яйцом пашот","en":"Avocado toast with poached egg"}'::jsonb,
   '{"ru":"Классика полезных завтраков: хрустящий хлеб, кремовое авокадо и жидкий желток.","en":"A healthy-breakfast classic: crisp bread, creamy avocado and a runny yolk."}'::jsonb,
   '{"ru":["Цельнозерновой хлеб — 1 ломтик","Авокадо — 1/2 шт","Яйцо — 1 шт","Лимонный сок — несколько капель","Соль, перец, хлопья чили"],"en":["Wholegrain bread — 1 slice","Avocado — 1/2","Egg — 1","Lemon juice — a few drops","Salt, pepper, chilli flakes"]}'::jsonb,
   '{"ru":["Разомните авокадо вилкой с лимонным соком, солью и перцем.","Сварите яйцо пашот: 3 минуты в чуть кипящей воде с ложкой уксуса.","Подсушите хлеб в тостере.","Намажьте авокадо, сверху — яйцо и хлопья чили."],"en":["Mash the avocado with lemon juice, salt and pepper.","Poach the egg: 3 minutes in barely simmering water with a splash of vinegar.","Toast the bread.","Spread the avocado, top with the egg and chilli flakes."]}'::jsonb,
   '{"ru":["завтрак","ПП","авокадо"],"en":["breakfast","healthy","avocado"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('pyshnye-blinchiki', 'breakfast', false, null, 25, 540, 3, 'easy',
   '{"ru":"Пышные панкейки","en":"Fluffy pancakes"}'::jsonb,
   '{"ru":"Высокие, воздушные панкейки на кефире — выходные начинаются правильно.","en":"Tall, airy buttermilk pancakes — the right way to start the weekend."}'::jsonb,
   '{"ru":["Мука — 200 г","Кефир — 250 мл","Яйцо — 1 шт","Сахар — 2 ст. л.","Разрыхлитель — 1 ч. л.","Сода — 1/2 ч. л.","Масло сливочное — 20 г"],"en":["Flour — 200 g","Buttermilk — 250 ml","Egg — 1","Sugar — 2 tbsp","Baking powder — 1 tsp","Baking soda — 1/2 tsp","Butter — 20 g"]}'::jsonb,
   '{"ru":["Смешайте сухие ингредиенты в одной миске, влажные — в другой.","Соедините, не перемешивая до гладкости: комочки — это нормально.","Дайте тесту постоять 10 минут.","Жарьте на сухой сковороде на среднем огне до пузырьков, затем переверните."],"en":["Combine dry ingredients in one bowl, wet in another.","Fold together — lumps are fine, do not overmix.","Rest the batter 10 minutes.","Cook on a dry pan over medium heat until bubbles form, then flip."]}'::jsonb,
   '{"ru":["завтрак","выпечка","выходные"],"en":["breakfast","baking","weekend"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('grecheskiy-salat', 'salad', true, null, 15, 290, 2, 'easy',
   '{"ru":"Греческий салат","en":"Greek salad"}'::jsonb,
   '{"ru":"Свежие овощи, фета и оливковое масло. Лёгкий обед за 15 минут.","en":"Fresh vegetables, feta and olive oil. A light lunch in 15 minutes."}'::jsonb,
   '{"ru":["Помидоры — 3 шт","Огурец — 1 шт","Красный лук — 1/2 шт","Фета — 100 г","Оливки — горсть","Оливковое масло, орегано, соль"],"en":["Tomatoes — 3","Cucumber — 1","Red onion — 1/2","Feta — 100 g","Olives — a handful","Olive oil, oregano, salt"]}'::jsonb,
   '{"ru":["Нарежьте овощи крупными кусками.","Добавьте оливки и кубик феты сверху.","Полейте оливковым маслом, посыпьте орегано и солью.","Не перемешивайте — подавайте слоями."],"en":["Chop the vegetables into large chunks.","Add olives and a block of feta on top.","Drizzle with olive oil, sprinkle oregano and salt.","Do not toss — serve in layers."]}'::jsonb,
   '{"ru":["салат","ПП","лето"],"en":["salad","healthy","summer"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('tomatnyy-krem-sup', 'soup', true, null, 35, 220, 4, 'easy',
   '{"ru":"Томатный крем-суп","en":"Creamy tomato soup"}'::jsonb,
   '{"ru":"Бархатистый суп из запечённых томатов с базиликом. Уютно и полезно.","en":"A velvety roasted-tomato soup with basil. Cosy and healthy."}'::jsonb,
   '{"ru":["Помидоры — 800 г","Лук — 1 шт","Чеснок — 3 зубчика","Овощной бульон — 400 мл","Базилик — пучок","Оливковое масло, соль, перец"],"en":["Tomatoes — 800 g","Onion — 1","Garlic — 3 cloves","Vegetable stock — 400 ml","Basil — a bunch","Olive oil, salt, pepper"]}'::jsonb,
   '{"ru":["Запеките половинки томатов с чесноком и маслом при 200 °C 20 минут.","Обжарьте лук до мягкости в кастрюле.","Добавьте томаты и бульон, варите 10 минут.","Пробейте блендером, добавьте базилик, приправьте."],"en":["Roast tomato halves with garlic and oil at 200 °C for 20 minutes.","Soften the onion in a pot.","Add tomatoes and stock, simmer 10 minutes.","Blend smooth, stir in basil, season."]}'::jsonb,
   '{"ru":["суп","ПП","осень"],"en":["soup","healthy","autumn"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('kurica-s-kinoa-bowl', 'main', true, null, 30, 470, 2, 'medium',
   '{"ru":"Боул с курицей и киноа","en":"Chicken & quinoa bowl"}'::jsonb,
   '{"ru":"Сбалансированный обед: белок, сложные углеводы и много овощей в одной миске.","en":"A balanced lunch: protein, complex carbs and plenty of veg in one bowl."}'::jsonb,
   '{"ru":["Куриное филе — 250 г","Киноа — 100 г","Огурец — 1 шт","Помидоры черри — 8 шт","Авокадо — 1/2 шт","Йогурт, лимон, специи для соуса"],"en":["Chicken breast — 250 g","Quinoa — 100 g","Cucumber — 1","Cherry tomatoes — 8","Avocado — 1/2","Yogurt, lemon, spices for the dressing"]}'::jsonb,
   '{"ru":["Отварите киноа по инструкции и остудите.","Обжарьте курицу со специями до золотистой корочки, нарежьте.","Нарежьте овощи и авокадо.","Соберите боул, полейте йогуртовым соусом с лимоном."],"en":["Cook the quinoa per the packet and cool.","Sear the seasoned chicken until golden, then slice.","Chop the vegetables and avocado.","Assemble the bowl and spoon over the lemon-yogurt dressing."]}'::jsonb,
   '{"ru":["обед","ПП","белок"],"en":["lunch","healthy","protein"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('pasta-s-tomatami-i-bazilikom', 'main', false, null, 20, 610, 2, 'easy',
   '{"ru":"Паста с томатами и базиликом","en":"Tomato & basil pasta"}'::jsonb,
   '{"ru":"Пять ингредиентов, двадцать минут — и на столе ресторанная паста.","en":"Five ingredients, twenty minutes — restaurant pasta at home."}'::jsonb,
   '{"ru":["Спагетти — 200 г","Помидоры — 4 шт","Чеснок — 2 зубчика","Базилик — пучок","Пармезан, оливковое масло, соль"],"en":["Spaghetti — 200 g","Tomatoes — 4","Garlic — 2 cloves","Basil — a bunch","Parmesan, olive oil, salt"]}'::jsonb,
   '{"ru":["Отварите пасту al dente, сохраните полстакана воды.","Обжарьте чеснок в масле, добавьте нарезанные томаты.","Тушите 8 минут, влейте немного пасты-воды.","Смешайте с пастой, добавьте базилик и пармезан."],"en":["Cook the pasta al dente, save half a cup of the water.","Fry the garlic in oil, add the chopped tomatoes.","Simmer 8 minutes, splash in the pasta water.","Toss with the pasta, add basil and parmesan."]}'::jsonb,
   '{"ru":["ужин","паста","италия"],"en":["dinner","pasta","italian"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('zelenyy-smuzi', 'drink', true, null, 5, 180, 1, 'easy',
   '{"ru":"Зелёный смузи","en":"Green smoothie"}'::jsonb,
   '{"ru":"Шпинат, банан и яблоко — витаминный заряд за пять минут.","en":"Spinach, banana and apple — a vitamin hit in five minutes."}'::jsonb,
   '{"ru":["Шпинат — горсть","Банан — 1 шт","Яблоко — 1 шт","Вода или кокосовое молоко — 200 мл","Семена чиа — 1 ч. л."],"en":["Spinach — a handful","Banana — 1","Apple — 1","Water or coconut milk — 200 ml","Chia seeds — 1 tsp"]}'::jsonb,
   '{"ru":["Сложите все ингредиенты в блендер.","Взбейте до однородности 30–40 секунд.","Попробуйте: если кисло — добавьте немного мёда.","Перелейте в стакан и пейте сразу."],"en":["Put everything in the blender.","Blend smooth for 30–40 seconds.","Taste: add a little honey if too sharp.","Pour into a glass and drink right away."]}'::jsonb,
   '{"ru":["напиток","ПП","детокс"],"en":["drink","healthy","detox"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('shokoladnyy-brauni', 'dessert', false, null, 40, 480, 8, 'medium',
   '{"ru":"Шоколадный брауни","en":"Chocolate brownie"}'::jsonb,
   '{"ru":"Влажный внутри, с хрустящей корочкой сверху. Опасно вкусный.","en":"Gooey inside, crackly on top. Dangerously good."}'::jsonb,
   '{"ru":["Тёмный шоколад — 200 г","Сливочное масло — 150 г","Сахар — 200 г","Яйца — 3 шт","Мука — 90 г","Какао — 2 ст. л."],"en":["Dark chocolate — 200 g","Butter — 150 g","Sugar — 200 g","Eggs — 3","Flour — 90 g","Cocoa — 2 tbsp"]}'::jsonb,
   '{"ru":["Растопите шоколад с маслом на водяной бане.","Взбейте яйца с сахаром до пышности.","Соедините всё, просейте муку и какао.","Выпекайте при 180 °C 22–25 минут — центр должен слегка дрожать."],"en":["Melt chocolate with butter over a water bath.","Whisk eggs and sugar until fluffy.","Combine, sift in flour and cocoa.","Bake at 180 °C for 22–25 minutes — the centre should wobble slightly."]}'::jsonb,
   '{"ru":["десерт","шоколад","выпечка"],"en":["dessert","chocolate","baking"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('syrniki-iz-tvoroga', 'breakfast', true, null, 20, 260, 2, 'easy',
   '{"ru":"Сырники из творога","en":"Cottage-cheese pancakes"}'::jsonb,
   '{"ru":"Нежные творожные сырники с минимумом муки — белковый завтрак без лишнего.","en":"Tender cottage-cheese pancakes with barely any flour — a lean protein breakfast."}'::jsonb,
   '{"ru":["Творог 5% — 300 г","Яйцо — 1 шт","Рисовая мука — 2 ст. л.","Мёд — 1 ст. л.","Ванилин — щепотка"],"en":["Cottage cheese 5% — 300 g","Egg — 1","Rice flour — 2 tbsp","Honey — 1 tbsp","Vanilla — a pinch"]}'::jsonb,
   '{"ru":["Разомните творог с яйцом, мёдом и ванилином.","Вмешайте муку до мягкого теста.","Сформируйте небольшие лепёшки, обваляйте в муке.","Обжарьте на антипригарной сковороде по 3 минуты с каждой стороны."],"en":["Mash the cottage cheese with egg, honey and vanilla.","Fold in the flour to a soft dough.","Shape small patties, dust with flour.","Cook on a non-stick pan 3 minutes per side."]}'::jsonb,
   '{"ru":["завтрак","ПП","творог"],"en":["breakfast","healthy","protein"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('zolotye-lukovye-kolca-v-pivnom-klyare', 'snack', false, null, 30, 320, 4, 'medium',
   '{"ru":"Золотые луковые кольца в пивном кляре","en":"Golden onion rings in beer batter"}'::jsonb,
   '{"ru":"Хрустящая корочка, воздушное тесто на газировке и сладкий лук внутри — закуска, которая исчезает со стола первой.","en":"A shell that shatters, airy sparkling-water batter and sweet onion inside — the snack that vanishes first."}'::jsonb,
   '{"ru":["Лук крупный — 3 шт","Мука — 120 г","Крахмал — 40 г","Яйцо — 1 шт","Газированная вода — 160 мл","Панировочные сухари — 100 г","Паприка — 1 ч. л.","Сметана — 90 г","Чеснок — 1 зубчик","Петрушка — 8 г","Масло для фритюра — 500 мл","Соль, перец — по вкусу"],"en":["Large onions — 3","Flour — 120 g","Starch — 40 g","Egg — 1","Sparkling water — 160 ml","Breadcrumbs — 100 g","Paprika — 1 tsp","Sour cream — 90 g","Garlic — 1 clove","Parsley — 8 g","Oil for deep-frying — 500 ml","Salt, pepper — to taste"]}'::jsonb,
   '{"ru":["Нарежьте лук кольцами толщиной 1 см и разберите на отдельные кольца.","Смешайте муку, крахмал, яйцо и газированную воду до гладкого кляра, приправьте паприкой, солью и перцем.","Обмакните каждое кольцо в кляр, затем обваляйте в сухарях.","Жарьте в разогретом масле по 2–3 минуты до золотистого цвета, выложите на салфетку.","Смешайте сметану с тёртым чесноком и петрушкой; подавайте кольца горячими с соусом."],"en":["Slice the onions into 1 cm rings and separate them.","Whisk flour, starch, egg and sparkling water into a smooth batter; season with paprika, salt and pepper.","Dip each ring in the batter, then coat in breadcrumbs.","Fry in hot oil 2–3 minutes until golden; drain on paper.","Stir sour cream with grated garlic and parsley; serve the rings hot with the dip."]}'::jsonb,
   '{"ru":["закуски к пиву","жареное","хрустящее"],"en":["beer snacks","fried","crunchy"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('kartofelnye-dolki-s-paprikoy', 'snack', false, null, 40, 280, 4, 'easy',
   '{"ru":"Картофельные дольки с паприкой и чесночным дипом","en":"Paprika potato wedges with garlic dip"}'::jsonb,
   '{"ru":"Запечённые до румяной корочки дольки с копчёной паприкой и прохладный чесночный соус — простая закуска, которая работает всегда.","en":"Wedges roasted to a crisp edge with smoky paprika and a cool garlic dip — a simple snack that always works."}'::jsonb,
   '{"ru":["Картофель — 800 г","Растительное масло — 35 мл","Паприка — 1,5 ч. л.","Сушёный чеснок — 1 ч. л.","Сметана — 100 г","Свежий чеснок — 1 зубчик","Укроп — 15 г","Соль — 1 ч. л.","Перец — по вкусу"],"en":["Potatoes — 800 g","Vegetable oil — 35 ml","Paprika — 1.5 tsp","Dried garlic — 1 tsp","Sour cream — 100 g","Fresh garlic — 1 clove","Dill — 15 g","Salt — 1 tsp","Pepper — to taste"]}'::jsonb,
   '{"ru":["Нарежьте картофель дольками, промойте от лишнего крахмала и обсушите насухо.","Смешайте масло, паприку, сушёный чеснок, соль и перец.","Обваляйте дольки в специях и разложите на противне в один слой.","Запекайте при 200 °C 30 минут до румяной корочки.","Смешайте сметану со свежим чесноком и укропом; подавайте дип отдельно, чтобы корочка не размокла."],"en":["Cut the potatoes into wedges, rinse off excess starch and pat completely dry.","Mix oil, paprika, dried garlic, salt and pepper.","Coat the wedges and spread on a tray in a single layer.","Roast at 200 °C for 30 minutes until golden.","Stir sour cream with fresh garlic and dill; serve the dip on the side so the crust stays crisp."]}'::jsonb,
   '{"ru":["закуски к пиву","запечённое","картофель"],"en":["beer snacks","baked","potato"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('syrnye-palochki-v-dvoynoy-panirovke', 'snack', false, null, 35, 360, 4, 'medium',
   '{"ru":"Сырные палочки в двойной панировке","en":"Double-crumbed cheese sticks"}'::jsonb,
   '{"ru":"Хрустящая оболочка снаружи и тянущийся сыр внутри. Секрет — подморозить сыр и запанировать дважды, чтобы он не вытек.","en":"A crunchy shell outside and molten, stretchy cheese inside. The trick: freeze the cheese and crumb it twice so it never leaks."}'::jsonb,
   '{"ru":["Твёрдый сыр — 300 г","Яйца — 2 шт","Мука — 60 г","Панировочные сухари — 130 г","Паприка — 1/2 ч. л.","Сметана — 90 г","Чеснок — 1 зубчик","Петрушка — 10 г","Масло для фритюра — 400 мл","Соль, перец — по вкусу"],"en":["Hard cheese — 300 g","Eggs — 2","Flour — 60 g","Breadcrumbs — 130 g","Paprika — 1/2 tsp","Sour cream — 90 g","Garlic — 1 clove","Parsley — 10 g","Oil for deep-frying — 400 ml","Salt, pepper — to taste"]}'::jsonb,
   '{"ru":["Нарежьте сыр брусочками и подморозьте 20 минут.","Обваляйте каждый брусочек в муке, затем в яйце и сухарях.","Повторите панировку (яйцо и сухари) второй раз для прочной корочки.","Обжарьте в горячем масле 1–2 минуты до золота и сразу выложите на салфетку.","Смешайте сметану с чесноком и петрушкой; подавайте немедленно, пока сыр тянется."],"en":["Cut the cheese into batons and freeze for 20 minutes.","Coat each baton in flour, then egg and breadcrumbs.","Repeat the egg-and-crumb coat a second time for a sturdy shell.","Fry in hot oil 1–2 minutes until golden and drain at once.","Stir sour cream with garlic and parsley; serve immediately while the cheese pulls."]}'::jsonb,
   '{"ru":["закуски к пиву","сыр","жареное"],"en":["beer snacks","cheese","fried"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('kurinye-krylya-v-medovo-chesnochnoy-glazuri', 'main', false, null, 70, 430, 4, 'medium',
   '{"ru":"Куриные крылья в медово-чесночной глазури","en":"Honey-garlic glazed chicken wings"}'::jsonb,
   '{"ru":"Липкая блестящая глазурь, обожжённая жаром духовки, с кунжутом и лимоном. Мёд добавляется в конце, чтобы не сгорел.","en":"A sticky, glossy glaze caramelised by oven heat, finished with sesame and lemon. The honey goes on late so it never burns."}'::jsonb,
   '{"ru":["Куриные крылья — 900 г","Мёд — 2 ст. л.","Соевый соус — 45 мл","Чеснок — 3 зубчика","Паприка — 1 ч. л.","Растительное масло — 25 мл","Лимон — 1/2 шт","Кунжут — 1 ч. л.","Петрушка — 10 г","Соль, перец — по вкусу"],"en":["Chicken wings — 900 g","Honey — 2 tbsp","Soy sauce — 45 ml","Garlic — 3 cloves","Paprika — 1 tsp","Vegetable oil — 25 ml","Lemon — 1/2","Sesame — 1 tsp","Parsley — 10 g","Salt, pepper — to taste"]}'::jsonb,
   '{"ru":["Разделите крылья на части и хорошо обсушите кожу — так корочка будет лучше.","Смешайте маринад из мёда, соевого соуса, чеснока, паприки и масла.","Обмажьте крылья и оставьте на 20 минут.","Разложите на противень и запекайте при 200 °C 25 минут.","Смажьте оставшейся глазурью и допеките 5 минут; посыпьте кунжутом и петрушкой, сбрызните лимоном."],"en":["Joint the wings and pat the skin very dry for a better crust.","Mix a marinade of honey, soy sauce, garlic, paprika and oil.","Coat the wings and rest for 20 minutes.","Spread on a tray and bake at 200 °C for 25 minutes.","Brush with the remaining glaze and bake 5 minutes more; scatter sesame and parsley, squeeze over lemon."]}'::jsonb,
   '{"ru":["закуски к пиву","курица","запечённое"],"en":["beer snacks","chicken","baked"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('rzhanye-grenki-s-chesnokom-i-syrnym-dipom', 'snack', false, null, 30, 250, 6, 'easy',
   '{"ru":"Ржаные гренки с чесноком и сырным дипом","en":"Rye garlic croutons with cheese dip"}'::jsonb,
   '{"ru":"Ароматные ржаные брусочки, запечённые до хруста в чесночном масле, и тёплый сырный соус на сливках. Классика к пиву без фритюра.","en":"Fragrant rye batons baked crisp in garlic butter, with a warm cream-and-cheese dip. A beer classic without the deep fryer."}'::jsonb,
   '{"ru":["Ржаной хлеб — 350 г","Чеснок — 3 зубчика","Растительное масло — 35 мл","Твёрдый сыр — 120 г","Сливки 20% — 140 мл","Петрушка — 10 г","Паприка — 1/2 ч. л.","Соль, перец — по вкусу"],"en":["Rye bread — 350 g","Garlic — 3 cloves","Vegetable oil — 35 ml","Hard cheese — 120 g","Cream 20% — 140 ml","Parsley — 10 g","Paprika — 1/2 tsp","Salt, pepper — to taste"]}'::jsonb,
   '{"ru":["Нарежьте хлеб одинаковыми брусочками.","Смешайте масло с тёртым чесноком, паприкой и солью и смажьте брусочки.","Запекайте при 180 °C 12–15 минут до хруста.","Прогрейте сливки на слабом огне, всыпьте тёртый сыр и растопите до гладкости, не доводя до кипения.","Подавайте гренки сразу с тёплым сырным дипом."],"en":["Cut the bread into even batons.","Mix oil with grated garlic, paprika and salt and brush the batons.","Bake at 180 °C for 12–15 minutes until crisp.","Warm the cream over low heat, add grated cheese and melt smooth without boiling.","Serve the croutons right away with the warm cheese dip."]}'::jsonb,
   '{"ru":["закуски к пиву","гренки","запечённое"],"en":["beer snacks","croutons","baked"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  ('kurinye-oladi-s-kabachkom', 'main', true, null, 40, 190, 4, 'easy',
   '{"ru":"Сочные куриные оладьи с кабачком и сыром","en":"Juicy chicken & zucchini patties"}'::jsonb,
   '{"ru":"Нежные ПП-оладьи из куриного фарша и кабачка, запечённые в духовке без капли масла. Сочные внутри, румяные сверху — идеальный лёгкий ужин.","en":"Tender healthy patties of chicken mince and zucchini, oven-baked without a drop of oil. Juicy inside, golden on top — the perfect light dinner."}'::jsonb,
   '{"ru":["Куриный фарш — 500 г","Кабачок — 1 средний (~250–300 г)","Яйцо — 1 шт","Твёрдый сыр — 80–100 г","Мука — 2 ст. л.","Паприка — 1 ч. л.","Соль — по вкусу","Чёрный молотый перец — по вкусу","Для подачи: огурец — 1 шт, помидоры — 2 шт, укроп — небольшой пучок"],"en":["Chicken mince — 500 g","Zucchini — 1 medium (~250–300 g)","Egg — 1","Hard cheese — 80–100 g","Flour — 2 tbsp","Paprika — 1 tsp","Salt — to taste","Black pepper — to taste","To serve: cucumber — 1, tomatoes — 2, dill — a small bunch"]}'::jsonb,
   '{"ru":["Кабачок натрите на крупной тёрке и слегка отожмите лишнюю влагу.","Смешайте куриный фарш, кабачок, яйцо, тёртый сыр, муку, паприку, соль и перец.","Хорошо перемешайте до однородного вязкого фарша.","Выкладывайте ложкой на противень с пергаментом, формируя оладьи.","Запекайте 20–25 минут при 180 °C до румяной корочки.","Подавайте горячими с салатом из огурца, помидоров и укропа."],"en":["Grate the zucchini coarsely and squeeze out the excess moisture.","Combine the chicken mince, zucchini, egg, grated cheese, flour, paprika, salt and pepper.","Mix well into a smooth, sticky mixture.","Spoon onto a parchment-lined tray, shaping patties.","Bake for 20–25 minutes at 180 °C until golden.","Serve hot with a cucumber, tomato and dill salad."]}'::jsonb,
   '{"ru":["ПП","ужин","курица","кабачок"],"en":["healthy","dinner","chicken","zucchini"]}'::jsonb)
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;

