import type { Lifehack, Recipe } from "./types";

// Built-in seed content. This is what renders when Supabase is not configured,
// and it doubles as the reference shape for the `recipes` / `lifehacks` tables
// (see supabase/migrations). Images are local SVG covers under public/img
// (scripts/generate-images.mjs) in the "Свежо" palette — the site needs no
// external image host. Swap `image` for a photo URL any time.

export const SEED_RECIPES: Recipe[] = [
  {
    id: "r-oatmeal",
    slug: "ovsyanka-s-yagodami",
    category: "breakfast",
    isPp: true,
    image: "/img/recipes/breakfast.svg",
    minutes: 10,
    calories: 320,
    servings: 1,
    difficulty: "easy",
    title: { ru: "Овсянка с ягодами и орехами", en: "Berry & nut oatmeal" },
    description: {
      ru: "Тёплый завтрак, который заряжает энергией на полдня. Готовится, пока варится кофе.",
      en: "A warm breakfast that fuels half your day. Ready before the coffee is.",
    },
    ingredients: {
      ru: [
        "Овсяные хлопья — 50 г",
        "Молоко или вода — 200 мл",
        "Банан — 1/2 шт",
        "Горсть ягод (свежих или замороженных)",
        "Грецкие орехи — 15 г",
        "Мёд — 1 ч. л. (по желанию)",
      ],
      en: [
        "Rolled oats — 50 g",
        "Milk or water — 200 ml",
        "Banana — 1/2",
        "A handful of berries (fresh or frozen)",
        "Walnuts — 15 g",
        "Honey — 1 tsp (optional)",
      ],
    },
    steps: {
      ru: [
        "Залейте хлопья молоком и доведите до кипения на среднем огне.",
        "Варите 4–5 минут, помешивая, до кремовой текстуры.",
        "Снимите с огня, добавьте нарезанный банан.",
        "Выложите в тарелку, сверху — ягоды, орехи и мёд.",
      ],
      en: [
        "Cover the oats with milk and bring to a boil over medium heat.",
        "Simmer 4–5 minutes, stirring, until creamy.",
        "Off the heat, fold in the sliced banana.",
        "Serve topped with berries, nuts and honey.",
      ],
    },
    tags: { ru: ["завтрак", "быстро", "полезно"], en: ["breakfast", "quick", "healthy"] },
    createdAt: "2026-08-01T08:00:00Z",
  },
  {
    id: "r-avocado-toast",
    slug: "tost-s-avokado-i-yaycom",
    category: "breakfast",
    isPp: true,
    image: "/img/recipes/breakfast.svg",
    minutes: 12,
    calories: 380,
    servings: 1,
    difficulty: "easy",
    title: { ru: "Тост с авокадо и яйцом пашот", en: "Avocado toast with poached egg" },
    description: {
      ru: "Классика полезных завтраков: хрустящий хлеб, кремовое авокадо и жидкий желток.",
      en: "A healthy-breakfast classic: crisp bread, creamy avocado and a runny yolk.",
    },
    ingredients: {
      ru: [
        "Цельнозерновой хлеб — 1 ломтик",
        "Авокадо — 1/2 шт",
        "Яйцо — 1 шт",
        "Лимонный сок — несколько капель",
        "Соль, перец, хлопья чили",
      ],
      en: [
        "Wholegrain bread — 1 slice",
        "Avocado — 1/2",
        "Egg — 1",
        "Lemon juice — a few drops",
        "Salt, pepper, chilli flakes",
      ],
    },
    steps: {
      ru: [
        "Разомните авокадо вилкой с лимонным соком, солью и перцем.",
        "Сварите яйцо пашот: 3 минуты в чуть кипящей воде с ложкой уксуса.",
        "Подсушите хлеб в тостере.",
        "Намажьте авокадо, сверху — яйцо и хлопья чили.",
      ],
      en: [
        "Mash the avocado with lemon juice, salt and pepper.",
        "Poach the egg: 3 minutes in barely simmering water with a splash of vinegar.",
        "Toast the bread.",
        "Spread the avocado, top with the egg and chilli flakes.",
      ],
    },
    tags: { ru: ["завтрак", "ПП", "авокадо"], en: ["breakfast", "healthy", "avocado"] },
    createdAt: "2026-08-02T08:00:00Z",
  },
  {
    id: "r-pancakes",
    slug: "pyshnye-blinchiki",
    category: "breakfast",
    isPp: false,
    image: "/img/recipes/breakfast.svg",
    minutes: 25,
    calories: 540,
    servings: 3,
    difficulty: "easy",
    title: { ru: "Пышные панкейки", en: "Fluffy pancakes" },
    description: {
      ru: "Высокие, воздушные панкейки на кефире — выходные начинаются правильно.",
      en: "Tall, airy buttermilk pancakes — the right way to start the weekend.",
    },
    ingredients: {
      ru: [
        "Мука — 200 г",
        "Кефир — 250 мл",
        "Яйцо — 1 шт",
        "Сахар — 2 ст. л.",
        "Разрыхлитель — 1 ч. л.",
        "Сода — 1/2 ч. л.",
        "Масло сливочное — 20 г",
      ],
      en: [
        "Flour — 200 g",
        "Buttermilk — 250 ml",
        "Egg — 1",
        "Sugar — 2 tbsp",
        "Baking powder — 1 tsp",
        "Baking soda — 1/2 tsp",
        "Butter — 20 g",
      ],
    },
    steps: {
      ru: [
        "Смешайте сухие ингредиенты в одной миске, влажные — в другой.",
        "Соедините, не перемешивая до гладкости: комочки — это нормально.",
        "Дайте тесту постоять 10 минут.",
        "Жарьте на сухой сковороде на среднем огне до пузырьков, затем переверните.",
      ],
      en: [
        "Combine dry ingredients in one bowl, wet in another.",
        "Fold together — lumps are fine, do not overmix.",
        "Rest the batter 10 minutes.",
        "Cook on a dry pan over medium heat until bubbles form, then flip.",
      ],
    },
    tags: { ru: ["завтрак", "выпечка", "выходные"], en: ["breakfast", "baking", "weekend"] },
    createdAt: "2026-08-03T08:00:00Z",
  },
  {
    id: "r-greek-salad",
    slug: "grecheskiy-salat",
    category: "salad",
    isPp: true,
    image: "/img/recipes/salad.svg",
    minutes: 15,
    calories: 290,
    servings: 2,
    difficulty: "easy",
    title: { ru: "Греческий салат", en: "Greek salad" },
    description: {
      ru: "Свежие овощи, фета и оливковое масло. Лёгкий обед за 15 минут.",
      en: "Fresh vegetables, feta and olive oil. A light lunch in 15 minutes.",
    },
    ingredients: {
      ru: [
        "Помидоры — 3 шт",
        "Огурец — 1 шт",
        "Красный лук — 1/2 шт",
        "Фета — 100 г",
        "Оливки — горсть",
        "Оливковое масло, орегано, соль",
      ],
      en: [
        "Tomatoes — 3",
        "Cucumber — 1",
        "Red onion — 1/2",
        "Feta — 100 g",
        "Olives — a handful",
        "Olive oil, oregano, salt",
      ],
    },
    steps: {
      ru: [
        "Нарежьте овощи крупными кусками.",
        "Добавьте оливки и кубик феты сверху.",
        "Полейте оливковым маслом, посыпьте орегано и солью.",
        "Не перемешивайте — подавайте слоями.",
      ],
      en: [
        "Chop the vegetables into large chunks.",
        "Add olives and a block of feta on top.",
        "Drizzle with olive oil, sprinkle oregano and salt.",
        "Do not toss — serve in layers.",
      ],
    },
    tags: { ru: ["салат", "ПП", "лето"], en: ["salad", "healthy", "summer"] },
    createdAt: "2026-08-04T08:00:00Z",
  },
  {
    id: "r-tomato-soup",
    slug: "tomatnyy-krem-sup",
    category: "soup",
    isPp: true,
    image: "/img/recipes/soup.svg",
    minutes: 35,
    calories: 220,
    servings: 4,
    difficulty: "easy",
    title: { ru: "Томатный крем-суп", en: "Creamy tomato soup" },
    description: {
      ru: "Бархатистый суп из запечённых томатов с базиликом. Уютно и полезно.",
      en: "A velvety roasted-tomato soup with basil. Cosy and healthy.",
    },
    ingredients: {
      ru: [
        "Помидоры — 800 г",
        "Лук — 1 шт",
        "Чеснок — 3 зубчика",
        "Овощной бульон — 400 мл",
        "Базилик — пучок",
        "Оливковое масло, соль, перец",
      ],
      en: [
        "Tomatoes — 800 g",
        "Onion — 1",
        "Garlic — 3 cloves",
        "Vegetable stock — 400 ml",
        "Basil — a bunch",
        "Olive oil, salt, pepper",
      ],
    },
    steps: {
      ru: [
        "Запеките половинки томатов с чесноком и маслом при 200 °C 20 минут.",
        "Обжарьте лук до мягкости в кастрюле.",
        "Добавьте томаты и бульон, варите 10 минут.",
        "Пробейте блендером, добавьте базилик, приправьте.",
      ],
      en: [
        "Roast tomato halves with garlic and oil at 200 °C for 20 minutes.",
        "Soften the onion in a pot.",
        "Add tomatoes and stock, simmer 10 minutes.",
        "Blend smooth, stir in basil, season.",
      ],
    },
    tags: { ru: ["суп", "ПП", "осень"], en: ["soup", "healthy", "autumn"] },
    createdAt: "2026-08-05T08:00:00Z",
  },
  {
    id: "r-chicken-bowl",
    slug: "kurica-s-kinoa-bowl",
    category: "main",
    isPp: true,
    image: "/img/recipes/main.svg",
    minutes: 30,
    calories: 470,
    servings: 2,
    difficulty: "medium",
    title: { ru: "Боул с курицей и киноа", en: "Chicken & quinoa bowl" },
    description: {
      ru: "Сбалансированный обед: белок, сложные углеводы и много овощей в одной миске.",
      en: "A balanced lunch: protein, complex carbs and plenty of veg in one bowl.",
    },
    ingredients: {
      ru: [
        "Куриное филе — 250 г",
        "Киноа — 100 г",
        "Огурец — 1 шт",
        "Помидоры черри — 8 шт",
        "Авокадо — 1/2 шт",
        "Йогурт, лимон, специи для соуса",
      ],
      en: [
        "Chicken breast — 250 g",
        "Quinoa — 100 g",
        "Cucumber — 1",
        "Cherry tomatoes — 8",
        "Avocado — 1/2",
        "Yogurt, lemon, spices for the dressing",
      ],
    },
    steps: {
      ru: [
        "Отварите киноа по инструкции и остудите.",
        "Обжарьте курицу со специями до золотистой корочки, нарежьте.",
        "Нарежьте овощи и авокадо.",
        "Соберите боул, полейте йогуртовым соусом с лимоном.",
      ],
      en: [
        "Cook the quinoa per the packet and cool.",
        "Sear the seasoned chicken until golden, then slice.",
        "Chop the vegetables and avocado.",
        "Assemble the bowl and spoon over the lemon-yogurt dressing.",
      ],
    },
    tags: { ru: ["обед", "ПП", "белок"], en: ["lunch", "healthy", "protein"] },
    createdAt: "2026-08-06T08:00:00Z",
  },
  {
    id: "r-pasta",
    slug: "pasta-s-tomatami-i-bazilikom",
    category: "main",
    isPp: false,
    image: "/img/recipes/main.svg",
    minutes: 20,
    calories: 610,
    servings: 2,
    difficulty: "easy",
    title: { ru: "Паста с томатами и базиликом", en: "Tomato & basil pasta" },
    description: {
      ru: "Пять ингредиентов, двадцать минут — и на столе ресторанная паста.",
      en: "Five ingredients, twenty minutes — restaurant pasta at home.",
    },
    ingredients: {
      ru: [
        "Спагетти — 200 г",
        "Помидоры — 4 шт",
        "Чеснок — 2 зубчика",
        "Базилик — пучок",
        "Пармезан, оливковое масло, соль",
      ],
      en: [
        "Spaghetti — 200 g",
        "Tomatoes — 4",
        "Garlic — 2 cloves",
        "Basil — a bunch",
        "Parmesan, olive oil, salt",
      ],
    },
    steps: {
      ru: [
        "Отварите пасту al dente, сохраните полстакана воды.",
        "Обжарьте чеснок в масле, добавьте нарезанные томаты.",
        "Тушите 8 минут, влейте немного пасты-воды.",
        "Смешайте с пастой, добавьте базилик и пармезан.",
      ],
      en: [
        "Cook the pasta al dente, save half a cup of the water.",
        "Fry the garlic in oil, add the chopped tomatoes.",
        "Simmer 8 minutes, splash in the pasta water.",
        "Toss with the pasta, add basil and parmesan.",
      ],
    },
    tags: { ru: ["ужин", "паста", "италия"], en: ["dinner", "pasta", "italian"] },
    createdAt: "2026-08-07T08:00:00Z",
  },
  {
    id: "r-smoothie",
    slug: "zelenyy-smuzi",
    category: "drink",
    isPp: true,
    image: "/img/recipes/drink.svg",
    minutes: 5,
    calories: 180,
    servings: 1,
    difficulty: "easy",
    title: { ru: "Зелёный смузи", en: "Green smoothie" },
    description: {
      ru: "Шпинат, банан и яблоко — витаминный заряд за пять минут.",
      en: "Spinach, banana and apple — a vitamin hit in five minutes.",
    },
    ingredients: {
      ru: [
        "Шпинат — горсть",
        "Банан — 1 шт",
        "Яблоко — 1 шт",
        "Вода или кокосовое молоко — 200 мл",
        "Семена чиа — 1 ч. л.",
      ],
      en: [
        "Spinach — a handful",
        "Banana — 1",
        "Apple — 1",
        "Water or coconut milk — 200 ml",
        "Chia seeds — 1 tsp",
      ],
    },
    steps: {
      ru: [
        "Сложите все ингредиенты в блендер.",
        "Взбейте до однородности 30–40 секунд.",
        "Попробуйте: если кисло — добавьте немного мёда.",
        "Перелейте в стакан и пейте сразу.",
      ],
      en: [
        "Put everything in the blender.",
        "Blend smooth for 30–40 seconds.",
        "Taste: add a little honey if too sharp.",
        "Pour into a glass and drink right away.",
      ],
    },
    tags: { ru: ["напиток", "ПП", "детокс"], en: ["drink", "healthy", "detox"] },
    createdAt: "2026-08-08T08:00:00Z",
  },
  {
    id: "r-brownie",
    slug: "shokoladnyy-brauni",
    category: "dessert",
    isPp: false,
    image: "/img/recipes/dessert.svg",
    minutes: 40,
    calories: 480,
    servings: 8,
    difficulty: "medium",
    title: { ru: "Шоколадный брауни", en: "Chocolate brownie" },
    description: {
      ru: "Влажный внутри, с хрустящей корочкой сверху. Опасно вкусный.",
      en: "Gooey inside, crackly on top. Dangerously good.",
    },
    ingredients: {
      ru: [
        "Тёмный шоколад — 200 г",
        "Сливочное масло — 150 г",
        "Сахар — 200 г",
        "Яйца — 3 шт",
        "Мука — 90 г",
        "Какао — 2 ст. л.",
      ],
      en: [
        "Dark chocolate — 200 g",
        "Butter — 150 g",
        "Sugar — 200 g",
        "Eggs — 3",
        "Flour — 90 g",
        "Cocoa — 2 tbsp",
      ],
    },
    steps: {
      ru: [
        "Растопите шоколад с маслом на водяной бане.",
        "Взбейте яйца с сахаром до пышности.",
        "Соедините всё, просейте муку и какао.",
        "Выпекайте при 180 °C 22–25 минут — центр должен слегка дрожать.",
      ],
      en: [
        "Melt chocolate with butter over a water bath.",
        "Whisk eggs and sugar until fluffy.",
        "Combine, sift in flour and cocoa.",
        "Bake at 180 °C for 22–25 minutes — the centre should wobble slightly.",
      ],
    },
    tags: { ru: ["десерт", "шоколад", "выпечка"], en: ["dessert", "chocolate", "baking"] },
    createdAt: "2026-08-09T08:00:00Z",
  },
  {
    id: "r-cottage-pancakes",
    slug: "syrniki-iz-tvoroga",
    category: "breakfast",
    isPp: true,
    image: "/img/recipes/breakfast.svg",
    minutes: 20,
    calories: 260,
    servings: 2,
    difficulty: "easy",
    title: { ru: "Сырники из творога", en: "Cottage-cheese pancakes" },
    description: {
      ru: "Нежные творожные сырники с минимумом муки — белковый завтрак без лишнего.",
      en: "Tender cottage-cheese pancakes with barely any flour — a lean protein breakfast.",
    },
    ingredients: {
      ru: [
        "Творог 5% — 300 г",
        "Яйцо — 1 шт",
        "Рисовая мука — 2 ст. л.",
        "Мёд — 1 ст. л.",
        "Ванилин — щепотка",
      ],
      en: [
        "Cottage cheese 5% — 300 g",
        "Egg — 1",
        "Rice flour — 2 tbsp",
        "Honey — 1 tbsp",
        "Vanilla — a pinch",
      ],
    },
    steps: {
      ru: [
        "Разомните творог с яйцом, мёдом и ванилином.",
        "Вмешайте муку до мягкого теста.",
        "Сформируйте небольшие лепёшки, обваляйте в муке.",
        "Обжарьте на антипригарной сковороде по 3 минуты с каждой стороны.",
      ],
      en: [
        "Mash the cottage cheese with egg, honey and vanilla.",
        "Fold in the flour to a soft dough.",
        "Shape small patties, dust with flour.",
        "Cook on a non-stick pan 3 minutes per side.",
      ],
    },
    tags: { ru: ["завтрак", "ПП", "творог"], en: ["breakfast", "healthy", "protein"] },
    createdAt: "2026-08-10T08:00:00Z",
  },

  // ── Коллекция «Закуски к пиву» — image left as a category placeholder cover
  // until a photo is attached from the admin panel. ──────────────────────────
  {
    id: "r-onion-rings",
    slug: "zolotye-lukovye-kolca-v-pivnom-klyare",
    category: "snack",
    isPp: false,
    image: "/img/recipes/snack.svg",
    minutes: 30,
    calories: 320,
    servings: 4,
    difficulty: "medium",
    title: {
      ru: "Золотые луковые кольца в пивном кляре",
      en: "Golden onion rings in beer batter",
    },
    description: {
      ru: "Хрустящая корочка, воздушное тесто на газировке и сладкий лук внутри — закуска, которая исчезает со стола первой.",
      en: "A shell that shatters, airy sparkling-water batter and sweet onion inside — the snack that vanishes first.",
    },
    ingredients: {
      ru: [
        "Лук крупный — 3 шт",
        "Мука — 120 г",
        "Крахмал — 40 г",
        "Яйцо — 1 шт",
        "Газированная вода — 160 мл",
        "Панировочные сухари — 100 г",
        "Паприка — 1 ч. л.",
        "Сметана — 90 г",
        "Чеснок — 1 зубчик",
        "Петрушка — 8 г",
        "Масло для фритюра — 500 мл",
        "Соль, перец — по вкусу",
      ],
      en: [
        "Large onions — 3",
        "Flour — 120 g",
        "Starch — 40 g",
        "Egg — 1",
        "Sparkling water — 160 ml",
        "Breadcrumbs — 100 g",
        "Paprika — 1 tsp",
        "Sour cream — 90 g",
        "Garlic — 1 clove",
        "Parsley — 8 g",
        "Oil for deep-frying — 500 ml",
        "Salt, pepper — to taste",
      ],
    },
    steps: {
      ru: [
        "Нарежьте лук кольцами толщиной 1 см и разберите на отдельные кольца.",
        "Смешайте муку, крахмал, яйцо и газированную воду до гладкого кляра, приправьте паприкой, солью и перцем.",
        "Обмакните каждое кольцо в кляр, затем обваляйте в сухарях.",
        "Жарьте в разогретом масле по 2–3 минуты до золотистого цвета, выложите на салфетку.",
        "Смешайте сметану с тёртым чесноком и петрушкой; подавайте кольца горячими с соусом.",
      ],
      en: [
        "Slice the onions into 1 cm rings and separate them.",
        "Whisk flour, starch, egg and sparkling water into a smooth batter; season with paprika, salt and pepper.",
        "Dip each ring in the batter, then coat in breadcrumbs.",
        "Fry in hot oil 2–3 minutes until golden; drain on paper.",
        "Stir sour cream with grated garlic and parsley; serve the rings hot with the dip.",
      ],
    },
    tags: {
      ru: ["закуски к пиву", "жареное", "хрустящее"],
      en: ["beer snacks", "fried", "crunchy"],
    },
    createdAt: "2026-08-11T08:00:00Z",
  },
  {
    id: "r-potato-wedges",
    slug: "kartofelnye-dolki-s-paprikoy",
    category: "snack",
    isPp: false,
    image: "/img/recipes/snack.svg",
    minutes: 40,
    calories: 280,
    servings: 4,
    difficulty: "easy",
    title: {
      ru: "Картофельные дольки с паприкой и чесночным дипом",
      en: "Paprika potato wedges with garlic dip",
    },
    description: {
      ru: "Запечённые до румяной корочки дольки с копчёной паприкой и прохладный чесночный соус — простая закуска, которая работает всегда.",
      en: "Wedges roasted to a crisp edge with smoky paprika and a cool garlic dip — a simple snack that always works.",
    },
    ingredients: {
      ru: [
        "Картофель — 800 г",
        "Растительное масло — 35 мл",
        "Паприка — 1,5 ч. л.",
        "Сушёный чеснок — 1 ч. л.",
        "Сметана — 100 г",
        "Свежий чеснок — 1 зубчик",
        "Укроп — 15 г",
        "Соль — 1 ч. л.",
        "Перец — по вкусу",
      ],
      en: [
        "Potatoes — 800 g",
        "Vegetable oil — 35 ml",
        "Paprika — 1.5 tsp",
        "Dried garlic — 1 tsp",
        "Sour cream — 100 g",
        "Fresh garlic — 1 clove",
        "Dill — 15 g",
        "Salt — 1 tsp",
        "Pepper — to taste",
      ],
    },
    steps: {
      ru: [
        "Нарежьте картофель дольками, промойте от лишнего крахмала и обсушите насухо.",
        "Смешайте масло, паприку, сушёный чеснок, соль и перец.",
        "Обваляйте дольки в специях и разложите на противне в один слой.",
        "Запекайте при 200 °C 30 минут до румяной корочки.",
        "Смешайте сметану со свежим чесноком и укропом; подавайте дип отдельно, чтобы корочка не размокла.",
      ],
      en: [
        "Cut the potatoes into wedges, rinse off excess starch and pat completely dry.",
        "Mix oil, paprika, dried garlic, salt and pepper.",
        "Coat the wedges and spread on a tray in a single layer.",
        "Roast at 200 °C for 30 minutes until golden.",
        "Stir sour cream with fresh garlic and dill; serve the dip on the side so the crust stays crisp.",
      ],
    },
    tags: {
      ru: ["закуски к пиву", "запечённое", "картофель"],
      en: ["beer snacks", "baked", "potato"],
    },
    createdAt: "2026-08-12T08:00:00Z",
  },
  {
    id: "r-cheese-sticks",
    slug: "syrnye-palochki-v-dvoynoy-panirovke",
    category: "snack",
    isPp: false,
    image: "/img/recipes/snack.svg",
    minutes: 35,
    calories: 360,
    servings: 4,
    difficulty: "medium",
    title: {
      ru: "Сырные палочки в двойной панировке",
      en: "Double-crumbed cheese sticks",
    },
    description: {
      ru: "Хрустящая оболочка снаружи и тянущийся сыр внутри. Секрет — подморозить сыр и запанировать дважды, чтобы он не вытек.",
      en: "A crunchy shell outside and molten, stretchy cheese inside. The trick: freeze the cheese and crumb it twice so it never leaks.",
    },
    ingredients: {
      ru: [
        "Твёрдый сыр — 300 г",
        "Яйца — 2 шт",
        "Мука — 60 г",
        "Панировочные сухари — 130 г",
        "Паприка — 1/2 ч. л.",
        "Сметана — 90 г",
        "Чеснок — 1 зубчик",
        "Петрушка — 10 г",
        "Масло для фритюра — 400 мл",
        "Соль, перец — по вкусу",
      ],
      en: [
        "Hard cheese — 300 g",
        "Eggs — 2",
        "Flour — 60 g",
        "Breadcrumbs — 130 g",
        "Paprika — 1/2 tsp",
        "Sour cream — 90 g",
        "Garlic — 1 clove",
        "Parsley — 10 g",
        "Oil for deep-frying — 400 ml",
        "Salt, pepper — to taste",
      ],
    },
    steps: {
      ru: [
        "Нарежьте сыр брусочками и подморозьте 20 минут.",
        "Обваляйте каждый брусочек в муке, затем в яйце и сухарях.",
        "Повторите панировку (яйцо и сухари) второй раз для прочной корочки.",
        "Обжарьте в горячем масле 1–2 минуты до золота и сразу выложите на салфетку.",
        "Смешайте сметану с чесноком и петрушкой; подавайте немедленно, пока сыр тянется.",
      ],
      en: [
        "Cut the cheese into batons and freeze for 20 minutes.",
        "Coat each baton in flour, then egg and breadcrumbs.",
        "Repeat the egg-and-crumb coat a second time for a sturdy shell.",
        "Fry in hot oil 1–2 minutes until golden and drain at once.",
        "Stir sour cream with garlic and parsley; serve immediately while the cheese pulls.",
      ],
    },
    tags: {
      ru: ["закуски к пиву", "сыр", "жареное"],
      en: ["beer snacks", "cheese", "fried"],
    },
    createdAt: "2026-08-13T08:00:00Z",
  },
  {
    id: "r-chicken-wings",
    slug: "kurinye-krylya-v-medovo-chesnochnoy-glazuri",
    category: "main",
    isPp: false,
    image: "/img/recipes/main.svg",
    minutes: 70,
    calories: 430,
    servings: 4,
    difficulty: "medium",
    title: {
      ru: "Куриные крылья в медово-чесночной глазури",
      en: "Honey-garlic glazed chicken wings",
    },
    description: {
      ru: "Липкая блестящая глазурь, обожжённая жаром духовки, с кунжутом и лимоном. Мёд добавляется в конце, чтобы не сгорел.",
      en: "A sticky, glossy glaze caramelised by oven heat, finished with sesame and lemon. The honey goes on late so it never burns.",
    },
    ingredients: {
      ru: [
        "Куриные крылья — 900 г",
        "Мёд — 2 ст. л.",
        "Соевый соус — 45 мл",
        "Чеснок — 3 зубчика",
        "Паприка — 1 ч. л.",
        "Растительное масло — 25 мл",
        "Лимон — 1/2 шт",
        "Кунжут — 1 ч. л.",
        "Петрушка — 10 г",
        "Соль, перец — по вкусу",
      ],
      en: [
        "Chicken wings — 900 g",
        "Honey — 2 tbsp",
        "Soy sauce — 45 ml",
        "Garlic — 3 cloves",
        "Paprika — 1 tsp",
        "Vegetable oil — 25 ml",
        "Lemon — 1/2",
        "Sesame — 1 tsp",
        "Parsley — 10 g",
        "Salt, pepper — to taste",
      ],
    },
    steps: {
      ru: [
        "Разделите крылья на части и хорошо обсушите кожу — так корочка будет лучше.",
        "Смешайте маринад из мёда, соевого соуса, чеснока, паприки и масла.",
        "Обмажьте крылья и оставьте на 20 минут.",
        "Разложите на противень и запекайте при 200 °C 25 минут.",
        "Смажьте оставшейся глазурью и допеките 5 минут; посыпьте кунжутом и петрушкой, сбрызните лимоном.",
      ],
      en: [
        "Joint the wings and pat the skin very dry for a better crust.",
        "Mix a marinade of honey, soy sauce, garlic, paprika and oil.",
        "Coat the wings and rest for 20 minutes.",
        "Spread on a tray and bake at 200 °C for 25 minutes.",
        "Brush with the remaining glaze and bake 5 minutes more; scatter sesame and parsley, squeeze over lemon.",
      ],
    },
    tags: {
      ru: ["закуски к пиву", "курица", "запечённое"],
      en: ["beer snacks", "chicken", "baked"],
    },
    createdAt: "2026-08-14T08:00:00Z",
  },
  {
    id: "r-rye-croutons",
    slug: "rzhanye-grenki-s-chesnokom-i-syrnym-dipom",
    category: "snack",
    isPp: false,
    image: "/img/recipes/snack.svg",
    minutes: 30,
    calories: 250,
    servings: 6,
    difficulty: "easy",
    title: {
      ru: "Ржаные гренки с чесноком и сырным дипом",
      en: "Rye garlic croutons with cheese dip",
    },
    description: {
      ru: "Ароматные ржаные брусочки, запечённые до хруста в чесночном масле, и тёплый сырный соус на сливках. Классика к пиву без фритюра.",
      en: "Fragrant rye batons baked crisp in garlic butter, with a warm cream-and-cheese dip. A beer classic without the deep fryer.",
    },
    ingredients: {
      ru: [
        "Ржаной хлеб — 350 г",
        "Чеснок — 3 зубчика",
        "Растительное масло — 35 мл",
        "Твёрдый сыр — 120 г",
        "Сливки 20% — 140 мл",
        "Петрушка — 10 г",
        "Паприка — 1/2 ч. л.",
        "Соль, перец — по вкусу",
      ],
      en: [
        "Rye bread — 350 g",
        "Garlic — 3 cloves",
        "Vegetable oil — 35 ml",
        "Hard cheese — 120 g",
        "Cream 20% — 140 ml",
        "Parsley — 10 g",
        "Paprika — 1/2 tsp",
        "Salt, pepper — to taste",
      ],
    },
    steps: {
      ru: [
        "Нарежьте хлеб одинаковыми брусочками.",
        "Смешайте масло с тёртым чесноком, паприкой и солью и смажьте брусочки.",
        "Запекайте при 180 °C 12–15 минут до хруста.",
        "Прогрейте сливки на слабом огне, всыпьте тёртый сыр и растопите до гладкости, не доводя до кипения.",
        "Подавайте гренки сразу с тёплым сырным дипом.",
      ],
      en: [
        "Cut the bread into even batons.",
        "Mix oil with grated garlic, paprika and salt and brush the batons.",
        "Bake at 180 °C for 12–15 minutes until crisp.",
        "Warm the cream over low heat, add grated cheese and melt smooth without boiling.",
        "Serve the croutons right away with the warm cheese dip.",
      ],
    },
    tags: {
      ru: ["закуски к пиву", "гренки", "запечённое"],
      en: ["beer snacks", "croutons", "baked"],
    },
    createdAt: "2026-08-15T08:00:00Z",
  },
  {
    id: "r-chicken-zucchini-patties",
    slug: "kurinye-oladi-s-kabachkom",
    category: "main",
    isPp: true,
    image: "/img/recipes/main.svg",
    minutes: 40,
    calories: 190,
    servings: 4,
    difficulty: "easy",
    title: {
      ru: "Сочные куриные оладьи с кабачком и сыром",
      en: "Juicy chicken & zucchini patties",
    },
    description: {
      ru: "Нежные ПП-оладьи из куриного фарша и кабачка, запечённые в духовке без капли масла. Сочные внутри, румяные сверху — идеальный лёгкий ужин.",
      en: "Tender healthy patties of chicken mince and zucchini, oven-baked without a drop of oil. Juicy inside, golden on top — the perfect light dinner.",
    },
    ingredients: {
      ru: [
        "Куриный фарш — 500 г",
        "Кабачок — 1 средний (~250–300 г)",
        "Яйцо — 1 шт",
        "Твёрдый сыр — 80–100 г",
        "Мука — 2 ст. л.",
        "Паприка — 1 ч. л.",
        "Соль — по вкусу",
        "Чёрный молотый перец — по вкусу",
        "Для подачи: огурец — 1 шт, помидоры — 2 шт, укроп — небольшой пучок",
      ],
      en: [
        "Chicken mince — 500 g",
        "Zucchini — 1 medium (~250–300 g)",
        "Egg — 1",
        "Hard cheese — 80–100 g",
        "Flour — 2 tbsp",
        "Paprika — 1 tsp",
        "Salt — to taste",
        "Black pepper — to taste",
        "To serve: cucumber — 1, tomatoes — 2, dill — a small bunch",
      ],
    },
    steps: {
      ru: [
        "Кабачок натрите на крупной тёрке и слегка отожмите лишнюю влагу.",
        "Смешайте куриный фарш, кабачок, яйцо, тёртый сыр, муку, паприку, соль и перец.",
        "Хорошо перемешайте до однородного вязкого фарша.",
        "Выкладывайте ложкой на противень с пергаментом, формируя оладьи.",
        "Запекайте 20–25 минут при 180 °C до румяной корочки.",
        "Подавайте горячими с салатом из огурца, помидоров и укропа.",
      ],
      en: [
        "Grate the zucchini coarsely and squeeze out the excess moisture.",
        "Combine the chicken mince, zucchini, egg, grated cheese, flour, paprika, salt and pepper.",
        "Mix well into a smooth, sticky mixture.",
        "Spoon onto a parchment-lined tray, shaping patties.",
        "Bake for 20–25 minutes at 180 °C until golden.",
        "Serve hot with a cucumber, tomato and dill salad.",
      ],
    },
    tags: {
      ru: ["ПП", "ужин", "курица", "кабачок"],
      en: ["healthy", "dinner", "chicken", "zucchini"],
    },
    createdAt: "2026-08-16T08:00:00Z",
  },

  // ── Коллекция «9 видов котлет» ───────────────────────────────────────────
  {
    id: "r-kotlety-myasnye",
    slug: "domashnie-myasnye-kotlety",
    category: "main",
    isPp: false,
    image: "/img/recipes/main.svg",
    minutes: 40,
    calories: 380,
    servings: 4,
    difficulty: "medium",
    title: {
      ru: "Домашние сочные котлеты из говядины и свинины",
      en: "Juicy home-style beef & pork cutlets",
    },
    description: {
      ru: "Классические котлеты из смеси говядины и свинины на размоченном в молоке хлебе — румяная корочка снаружи, сочность внутри. Вкус, знакомый с детства.",
      en: "Classic cutlets from a beef-and-pork mix on milk-soaked bread — a golden crust outside, juicy within. The taste everyone grew up with.",
    },
    ingredients: {
      ru: ["Говяжий фарш — 300 г", "Свиной фарш — 300 г", "Лук — 120 г", "Белый хлеб — 80 г", "Молоко — 120 мл", "Яйцо — 1 шт", "Чеснок — 1 зубчик", "Панировочные сухари — 60 г", "Масло для жарки — 30 мл", "Соль — 8 г", "Чёрный перец — по вкусу"],
      en: ["Beef mince — 300 g", "Pork mince — 300 g", "Onion — 120 g", "White bread — 80 g", "Milk — 120 ml", "Egg — 1", "Garlic — 1 clove", "Breadcrumbs — 60 g", "Oil for frying — 30 ml", "Salt — 8 g", "Black pepper — to taste"],
    },
    steps: {
      ru: ["Замочите белый хлеб в молоке на 5 минут и отожмите.", "Смешайте оба фарша с мелко нарезанным луком, чесноком, яйцом и хлебом; посолите и поперчите.", "Вымешайте недолго, сформуйте котлеты и обваляйте в сухарях.", "Обжарьте на среднем огне по 4–5 минут с каждой стороны до румяной корочки.", "Совет: не вымешивайте фарш слишком долго — котлеты останутся нежными."],
      en: ["Soak the white bread in milk for 5 minutes and squeeze it out.", "Combine both minces with finely chopped onion, garlic, egg and bread; season with salt and pepper.", "Mix briefly, shape the cutlets and coat in breadcrumbs.", "Fry over medium heat 4–5 minutes per side until golden.", "Tip: don't overwork the mince — the cutlets stay tender."],
    },
    tags: { ru: ["ужин", "мясо", "классика"], en: ["dinner", "meat", "classic"] },
    createdAt: "2026-08-17T08:00:00Z",
  },
  {
    id: "r-kotlety-pozharskie",
    slug: "pozharskie-kotlety",
    category: "main",
    isPp: false,
    image: "/img/recipes/main.svg",
    minutes: 50,
    calories: 420,
    servings: 4,
    difficulty: "medium",
    title: {
      ru: "Пожарские котлеты с хрустящей корочкой",
      en: "Pozharsky chicken cutlets with a crisp crust",
    },
    description: {
      ru: "Нежнейшие куриные котлеты на сливках в панировке из хлебных кубиков, с кусочком масла внутри. Хрустят снаружи и тают во рту.",
      en: "The tenderest cream-enriched chicken cutlets in a cubed-bread crust, with a knob of butter hidden inside. Crunchy outside, melting within.",
    },
    ingredients: {
      ru: ["Куриное бедро без кожи — 600 г", "Белый хлеб — 100 г", "Сливки 20% — 100 мл", "Лук — 80 г", "Сливочное масло — 80 г", "Белые сухари кубиками — 100 г", "Масло для жарки — 25 мл", "Соль — 7 г", "Чёрный перец — по вкусу"],
      en: ["Skinless chicken thigh — 600 g", "White bread — 100 g", "Cream 20% — 100 ml", "Onion — 80 g", "Butter — 80 g", "Cubed bread crumbs — 100 g", "Oil for frying — 25 ml", "Salt — 7 g", "Black pepper — to taste"],
    },
    steps: {
      ru: ["Замочите хлеб в сливках; измельчите куриное бедро с луком в фарш.", "Смешайте фарш с хлебом, посолите, поперчите и охладите 20 минут.", "В центр каждой котлеты вложите кусочек холодного масла и залепите.", "Обваляйте котлеты в хлебной крошке-кубиках.", "Обжарьте до румяности и доведите в духовке 8–10 минут при 180 °C.", "Совет: работайте с холодным фаршем — так масло останется внутри."],
      en: ["Soak the bread in cream; mince the chicken thigh with the onion.", "Mix the mince with the bread, season and chill for 20 minutes.", "Tuck a piece of cold butter into the centre of each cutlet and seal.", "Coat in the cubed bread crumbs.", "Fry until golden, then finish in the oven 8–10 minutes at 180 °C.", "Tip: keep the mince cold so the butter stays inside."],
    },
    tags: { ru: ["ужин", "курица", "праздничное"], en: ["dinner", "chicken", "special"] },
    createdAt: "2026-08-18T08:00:00Z",
  },
  {
    id: "r-kotlety-kurinye-syr",
    slug: "kurinye-kotlety-s-syrom",
    category: "main",
    isPp: false,
    image: "/img/recipes/main.svg",
    minutes: 45,
    calories: 390,
    servings: 4,
    difficulty: "medium",
    title: {
      ru: "Куриные котлеты с сырной начинкой",
      en: "Chicken cutlets with a melting cheese centre",
    },
    description: {
      ru: "Сочные куриные котлеты с сырным сердцем, которое тянется при разломе. Секрет — плотно защипнуть края, чтобы сыр остался внутри.",
      en: "Juicy chicken cutlets with a molten cheese heart that stretches when you break them open. The trick is sealing the edges tightly.",
    },
    ingredients: {
      ru: ["Куриный фарш — 600 г", "Твёрдый сыр — 150 г", "Лук — 100 г", "Яйцо — 1 шт", "Панировочные сухари — 80 г", "Сметана — 50 г", "Чеснок — 1 зубчик", "Масло для жарки — 25 мл", "Соль — 7 г", "Чёрный перец — по вкусу"],
      en: ["Chicken mince — 600 g", "Hard cheese — 150 g", "Onion — 100 g", "Egg — 1", "Breadcrumbs — 80 g", "Sour cream — 50 g", "Garlic — 1 clove", "Oil for frying — 25 ml", "Salt — 7 g", "Black pepper — to taste"],
    },
    steps: {
      ru: ["Смешайте куриный фарш с луком, чесноком, яйцом и сметаной; посолите и поперчите.", "Расплющите порцию фарша на ладони, в центр положите брусочек сыра.", "Плотно защипните края, формируя котлету, и обваляйте в сухарях.", "Обжарьте на среднем огне по 4–5 минут с каждой стороны.", "Совет: защипывайте края плотно, чтобы сыр не вытек."],
      en: ["Mix the chicken mince with onion, garlic, egg and sour cream; season.", "Flatten a portion in your palm and place a stick of cheese in the centre.", "Seal the edges tightly into a patty and coat in breadcrumbs.", "Fry over medium heat 4–5 minutes per side.", "Tip: seal the edges well so the cheese stays in."],
    },
    tags: { ru: ["ужин", "курица", "сыр"], en: ["dinner", "chicken", "cheese"] },
    createdAt: "2026-08-19T08:00:00Z",
  },
  {
    id: "r-kotlety-indeyka-kabachok",
    slug: "kotlety-iz-indeyki-s-kabachkom",
    category: "main",
    isPp: true,
    image: "/img/recipes/main.svg",
    minutes: 40,
    calories: 260,
    servings: 5,
    difficulty: "easy",
    title: {
      ru: "Нежные котлеты из индейки с кабачком",
      en: "Tender turkey & zucchini cutlets",
    },
    description: {
      ru: "Лёгкие котлеты из индейки с сочным кабачком и овсяными хлопьями вместо хлеба. ПП-вариант, который держит форму и остаётся нежным.",
      en: "Light turkey cutlets with juicy zucchini and oats instead of bread. A healthy version that holds its shape and stays tender.",
    },
    ingredients: {
      ru: ["Фарш из индейки — 650 г", "Кабачок — 250 г", "Лук — 100 г", "Яйцо — 1 шт", "Овсяные хлопья — 50 г", "Сметана — 40 г", "Укроп — 15 г", "Масло для жарки — 25 мл", "Соль — 7 г", "Чёрный перец — по вкусу"],
      en: ["Turkey mince — 650 g", "Zucchini — 250 g", "Onion — 100 g", "Egg — 1", "Rolled oats — 50 g", "Sour cream — 40 g", "Dill — 15 g", "Oil for frying — 25 ml", "Salt — 7 g", "Black pepper — to taste"],
    },
    steps: {
      ru: ["Натрите кабачок и хорошо отожмите лишнюю влагу.", "Смешайте фарш индейки с кабачком, луком, яйцом, хлопьями, сметаной и укропом.", "Дайте фаршу постоять 10 минут, чтобы хлопья набухли.", "Сформуйте котлеты и обжарьте под крышкой по 5 минут с каждой стороны.", "Совет: чем лучше отжат кабачок, тем легче котлеты держат форму."],
      en: ["Grate the zucchini and squeeze out the excess moisture well.", "Mix the turkey mince with zucchini, onion, egg, oats, sour cream and dill.", "Rest for 10 minutes so the oats swell.", "Shape the cutlets and fry, covered, 5 minutes per side.", "Tip: the better you squeeze the zucchini, the better they hold shape."],
    },
    tags: { ru: ["ПП", "ужин", "индейка", "кабачок"], en: ["healthy", "dinner", "turkey", "zucchini"] },
    createdAt: "2026-08-20T08:00:00Z",
  },
  {
    id: "r-kotlety-rybnye",
    slug: "rybnye-kotlety-iz-mintaya",
    category: "main",
    isPp: false,
    image: "/img/recipes/main.svg",
    minutes: 45,
    calories: 300,
    servings: 4,
    difficulty: "medium",
    title: {
      ru: "Рыбные котлеты из минтая",
      en: "Pollock fish cutlets",
    },
    description: {
      ru: "Мягкие и ароматные котлеты из филе минтая с укропом. Хлеб на молоке и кусочек масла делают их нежными и сочными.",
      en: "Soft, fragrant cutlets from pollock fillet with dill. Milk-soaked bread and a little butter keep them tender and moist.",
    },
    ingredients: {
      ru: ["Филе минтая — 700 г", "Лук — 100 г", "Белый хлеб — 80 г", "Молоко — 100 мл", "Яйцо — 1 шт", "Сливочное масло — 40 г", "Панировочные сухари — 80 г", "Укроп — 10 г", "Масло для жарки — 30 мл", "Соль — 7 г", "Чёрный перец — по вкусу"],
      en: ["Pollock fillet — 700 g", "Onion — 100 g", "White bread — 80 g", "Milk — 100 ml", "Egg — 1", "Butter — 40 g", "Breadcrumbs — 80 g", "Dill — 10 g", "Oil for frying — 30 ml", "Salt — 7 g", "Black pepper — to taste"],
    },
    steps: {
      ru: ["Измельчите филе минтая с луком в фарш.", "Добавьте размоченный в молоке хлеб, яйцо, мягкое масло и укроп; посолите.", "Охладите фарш 20 минут, сформуйте котлеты и обваляйте в сухарях.", "Обжарьте на среднем огне по 3–4 минуты с каждой стороны.", "Совет: перед формовкой охладите фарш — он не будет липнуть."],
      en: ["Mince the pollock fillet with the onion.", "Add milk-soaked bread, egg, soft butter and dill; season.", "Chill for 20 minutes, shape and coat in breadcrumbs.", "Fry over medium heat 3–4 minutes per side.", "Tip: chill the mixture before shaping so it doesn't stick."],
    },
    tags: { ru: ["ужин", "рыба", "минтай"], en: ["dinner", "fish", "pollock"] },
    createdAt: "2026-08-21T08:00:00Z",
  },
  {
    id: "r-kotlety-pechenochnye",
    slug: "pechenochnye-kotlety-s-risom",
    category: "main",
    isPp: false,
    image: "/img/recipes/main.svg",
    minutes: 40,
    calories: 310,
    servings: 4,
    difficulty: "easy",
    title: {
      ru: "Печёночные котлеты с рисом и морковью",
      en: "Chicken-liver cutlets with rice",
    },
    description: {
      ru: "Мягкие печёночные котлеты с варёным рисом и морковью. Быстро, бюджетно и по-настоящему сытно.",
      en: "Soft chicken-liver patties with boiled rice and carrot. Quick, budget-friendly and genuinely filling.",
    },
    ingredients: {
      ru: ["Куриная печень — 500 г", "Варёный рис — 180 г", "Лук — 120 г", "Морковь — 100 г", "Яйцо — 1 шт", "Мука — 60 г", "Сметана — 50 г", "Масло для жарки — 30 мл", "Соль — 7 г", "Чёрный перец — по вкусу"],
      en: ["Chicken liver — 500 g", "Boiled rice — 180 g", "Onion — 120 g", "Carrot — 100 g", "Egg — 1", "Flour — 60 g", "Sour cream — 50 g", "Oil for frying — 30 ml", "Salt — 7 g", "Black pepper — to taste"],
    },
    steps: {
      ru: ["Измельчите печень с луком блендером до однородности.", "Смешайте с варёным рисом, тёртой морковью, яйцом, мукой и сметаной; посолите.", "Выкладывайте массу ложкой на разогретую сковороду.", "Обжарьте по 3–4 минуты с каждой стороны на среднем огне.", "Совет: не делайте котлеты толстыми — так они прожарятся равномерно."],
      en: ["Blend the liver with the onion until smooth.", "Mix with boiled rice, grated carrot, egg, flour and sour cream; season.", "Spoon the mixture onto a hot pan.", "Fry 3–4 minutes per side over medium heat.", "Tip: keep them thin so they cook through evenly."],
    },
    tags: { ru: ["ужин", "печень", "бюджетно"], en: ["dinner", "liver", "budget"] },
    createdAt: "2026-08-22T08:00:00Z",
  },
  {
    id: "r-kotlety-kartofelnye",
    slug: "kartofelnye-kotlety-s-gribami",
    category: "main",
    isPp: false,
    image: "/img/recipes/main.svg",
    minutes: 60,
    calories: 340,
    servings: 4,
    difficulty: "medium",
    title: {
      ru: "Картофельные котлеты с грибной начинкой",
      en: "Potato cutlets stuffed with mushrooms",
    },
    description: {
      ru: "Пышные картофельные котлеты с сочной начинкой из жареных шампиньонов внутри и хрустящей панировкой снаружи.",
      en: "Fluffy potato cutlets with a juicy fried-mushroom filling inside and a crunchy crust outside.",
    },
    ingredients: {
      ru: ["Картофель — 800 г", "Шампиньоны — 300 г", "Лук — 120 г", "Яйцо — 1 шт", "Мука — 70 г", "Панировочные сухари — 100 г", "Сливочное масло — 20 г", "Масло для жарки — 40 мл", "Соль — 8 г", "Чёрный перец — по вкусу"],
      en: ["Potatoes — 800 g", "Mushrooms — 300 g", "Onion — 120 g", "Egg — 1", "Flour — 70 g", "Breadcrumbs — 100 g", "Butter — 20 g", "Oil for frying — 40 ml", "Salt — 8 g", "Black pepper — to taste"],
    },
    steps: {
      ru: ["Отварите картофель и разомните в пюре с маслом, остудите.", "Обжарьте нарезанные грибы с луком до золотистого цвета.", "Из картофельной массы сформуйте лепёшку, спрячьте внутрь грибную начинку и залепите.", "Обваляйте в муке и сухарях, обжарьте до румяной корочки.", "Совет: картофельная масса должна полностью остыть, иначе котлеты расплывутся."],
      en: ["Boil the potatoes and mash with butter, then cool.", "Fry the chopped mushrooms with onion until golden.", "Shape a potato patty, hide the mushroom filling inside and seal.", "Coat in flour and breadcrumbs, fry until golden.", "Tip: the potato must be fully cold or the cutlets spread."],
    },
    tags: { ru: ["ужин", "картофель", "грибы", "вегетарианское"], en: ["dinner", "potato", "mushrooms", "vegetarian"] },
    createdAt: "2026-08-23T08:00:00Z",
  },
  {
    id: "r-kotlety-grechnevye",
    slug: "grechnevye-kotlety-s-gribami",
    category: "main",
    isPp: false,
    image: "/img/recipes/main.svg",
    minutes: 40,
    calories: 290,
    servings: 4,
    difficulty: "easy",
    title: {
      ru: "Гречневые котлеты с грибами",
      en: "Buckwheat & mushroom cutlets",
    },
    description: {
      ru: "Постные котлеты из варёной гречки с ароматными шампиньонами. Интересная текстура — если измельчить лишь половину крупы.",
      en: "Lean cutlets of boiled buckwheat with fragrant mushrooms. Blend only half the grain for a more interesting texture.",
    },
    ingredients: {
      ru: ["Варёная гречка — 500 г", "Шампиньоны — 250 г", "Лук — 120 г", "Яйца — 2 шт", "Мука — 50 г", "Сметана — 40 г", "Панировочные сухари — 80 г", "Масло для жарки — 30 мл", "Соль — 7 г", "Чёрный перец — по вкусу"],
      en: ["Boiled buckwheat — 500 g", "Mushrooms — 250 g", "Onion — 120 g", "Eggs — 2", "Flour — 50 g", "Sour cream — 40 g", "Breadcrumbs — 80 g", "Oil for frying — 30 ml", "Salt — 7 g", "Black pepper — to taste"],
    },
    steps: {
      ru: ["Обжарьте нарезанные грибы с луком до готовности.", "Смешайте гречку с грибами, яйцами, мукой и сметаной; посолите.", "Сформуйте котлеты и обваляйте в сухарях.", "Обжарьте на среднем огне по 3–4 минуты с каждой стороны.", "Совет: измельчите блендером только половину гречки — текстура будет интереснее."],
      en: ["Fry the chopped mushrooms with onion until done.", "Mix buckwheat with mushrooms, eggs, flour and sour cream; season.", "Shape the cutlets and coat in breadcrumbs.", "Fry over medium heat 3–4 minutes per side.", "Tip: blend only half the buckwheat for a better texture."],
    },
    tags: { ru: ["ужин", "гречка", "грибы", "постное"], en: ["dinner", "buckwheat", "mushrooms", "lean"] },
    createdAt: "2026-08-24T08:00:00Z",
  },
  {
    id: "r-kotlety-kapustnye",
    slug: "kapustnye-kotlety-s-syrom",
    category: "main",
    isPp: false,
    image: "/img/recipes/main.svg",
    minutes: 45,
    calories: 270,
    servings: 4,
    difficulty: "easy",
    title: {
      ru: "Капустные котлеты с тянущимся сыром",
      en: "Cabbage cutlets with melty cheese",
    },
    description: {
      ru: "Мягкие котлеты из тушёной капусты с манкой и сыром, который тянется при разломе. Хрустящая корочка и нежная середина.",
      en: "Soft cutlets of braised cabbage with semolina and cheese that stretches when broken. Crisp crust, tender middle.",
    },
    ingredients: {
      ru: ["Белокочанная капуста — 700 г", "Твёрдый сыр — 150 г", "Лук — 100 г", "Яйца — 2 шт", "Манная крупа — 80 г", "Молоко — 100 мл", "Панировочные сухари — 80 г", "Укроп — 10 г", "Масло для жарки — 30 мл", "Соль — 7 г", "Чёрный перец — по вкусу"],
      en: ["White cabbage — 700 g", "Hard cheese — 150 g", "Onion — 100 g", "Eggs — 2", "Semolina — 80 g", "Milk — 100 ml", "Breadcrumbs — 80 g", "Dill — 10 g", "Oil for frying — 30 ml", "Salt — 7 g", "Black pepper — to taste"],
    },
    steps: {
      ru: ["Нашинкуйте капусту и потушите с луком и молоком до мягкости.", "Всыпьте манку, перемешайте и дайте постоять, пока масса загустеет.", "Вмешайте тёртый сыр, яйца и укроп; посолите и остудите.", "Сформуйте котлеты, обваляйте в сухарях и обжарьте до румяной корочки.", "Совет: перед формовкой полностью остудите капустную массу."],
      en: ["Shred the cabbage and braise with onion and milk until soft.", "Stir in the semolina and rest until the mixture thickens.", "Fold in grated cheese, eggs and dill; season and cool.", "Shape the cutlets, coat in breadcrumbs and fry until golden.", "Tip: cool the cabbage mixture fully before shaping."],
    },
    tags: { ru: ["ужин", "капуста", "сыр", "вегетарианское"], en: ["dinner", "cabbage", "cheese", "vegetarian"] },
    createdAt: "2026-08-25T08:00:00Z",
  },

  // --- Подборка «8 рецептов креветок» ---
  {
    id: "r-krevetki-chesnochnoe-maslo",
    slug: "krevetki-v-chesnochnom-masle",
    category: "main",
    isPp: false,
    image: "/img/recipes/main.svg",
    minutes: 15,
    calories: 240,
    servings: 2,
    difficulty: "easy",
    title: {
      ru: "Креветки в чесночном масле",
      en: "Garlic butter shrimp",
    },
    description: {
      ru: "Сочные креветки, обжаренные в сливочном масле с чесноком и петрушкой, с яркой ноткой лимона. Соус со дна сковороды — отдельное удовольствие, которое хочется собрать хлебом.",
      en: "Juicy shrimp seared in butter with garlic and parsley and a bright squeeze of lemon. The sauce left in the pan is a treat all its own — perfect for mopping up with bread.",
    },
    ingredients: {
      ru: ["Креветки — 400 г", "Сливочное масло — 40 г", "Чеснок — 3 зубчика", "Лимон — ½ шт", "Петрушка — небольшой пучок", "Соль — по вкусу", "Чёрный перец — по вкусу"],
      en: ["Shrimp — 400 g", "Butter — 40 g", "Garlic — 3 cloves", "Lemon — ½", "Parsley — a small bunch", "Salt — to taste", "Black pepper — to taste"],
    },
    steps: {
      ru: ["Обсушите креветки и обжарьте на разогретой сковороде по 1–2 минуты с каждой стороны.", "Добавьте сливочное масло и измельчённый чеснок, прогрейте ещё 30 секунд.", "Снимите с огня, посолите, поперчите и полейте лимонным соком.", "Посыпьте рубленой петрушкой и сразу подавайте.", "Совет: не пережаривайте — как только креветки стали розовыми и плотными, они готовы."],
      en: ["Pat the shrimp dry and sear on a hot pan 1–2 minutes per side.", "Add the butter and minced garlic, warm for another 30 seconds.", "Take off the heat, season and pour over the lemon juice.", "Scatter with chopped parsley and serve at once.", "Tip: don't overcook — once the shrimp turn pink and firm, they're done."],
    },
    tags: { ru: ["ужин", "креветки", "чеснок", "быстро"], en: ["dinner", "shrimp", "garlic", "quick"] },
    createdAt: "2026-08-26T08:00:00Z",
  },
  {
    id: "r-krevetki-medovo-chili",
    slug: "krevetki-medovo-chili",
    category: "main",
    isPp: false,
    image: "/img/recipes/main.svg",
    minutes: 15,
    calories: 260,
    servings: 2,
    difficulty: "easy",
    title: {
      ru: "Креветки медово-чили",
      en: "Honey-chili shrimp",
    },
    description: {
      ru: "Креветки в блестящей медово-чили глазури: сладкое встречается с острым, а соевый соус и лайм добавляют глубины. Ровно тот баланс, из-за которого тарелка пустеет первой.",
      en: "Shrimp in a glossy honey-chili glaze where sweet meets heat, rounded out by soy and lime. Exactly the balance that empties the plate first.",
    },
    ingredients: {
      ru: ["Креветки — 400 г", "Мёд — 1 ст. л.", "Соевый соус — 2 ст. л.", "Сладкий чили-соус — 2 ст. л.", "Чеснок — 2 зубчика", "Сок лайма — 1 ст. л.", "Зелёный лук — для подачи"],
      en: ["Shrimp — 400 g", "Honey — 1 tbsp", "Soy sauce — 2 tbsp", "Sweet chili sauce — 2 tbsp", "Garlic — 2 cloves", "Lime juice — 1 tbsp", "Spring onion — to serve"],
    },
    steps: {
      ru: ["Смешайте мёд, соевый соус, сладкий чили, измельчённый чеснок и сок лайма.", "Обжарьте креветки на сильном огне 2–3 минуты.", "Влейте соус и прогрейте ещё минуту до густой блестящей глазури.", "Подавайте, посыпав зелёным луком.", "Совет: держите огонь сильным, чтобы соус карамелизовался, а не выпаривался."],
      en: ["Mix the honey, soy sauce, sweet chili, minced garlic and lime juice.", "Sear the shrimp over high heat for 2–3 minutes.", "Pour in the sauce and cook another minute to a thick, glossy glaze.", "Serve scattered with spring onion.", "Tip: keep the heat high so the sauce caramelises rather than just steams."],
    },
    tags: { ru: ["ужин", "креветки", "острое", "азиатское"], en: ["dinner", "shrimp", "spicy", "asian"] },
    createdAt: "2026-08-26T08:05:00Z",
  },
  {
    id: "r-krevetki-slivochnyy-sous",
    slug: "krevetki-v-slivochnom-souse",
    category: "main",
    isPp: false,
    image: "/img/recipes/main.svg",
    minutes: 20,
    calories: 340,
    servings: 2,
    difficulty: "easy",
    title: {
      ru: "Креветки в сливочном соусе",
      en: "Creamy garlic parmesan shrimp",
    },
    description: {
      ru: "Нежные креветки в бархатистом сливочном соусе с чесноком и пармезаном. Тот случай, когда соус хочется собрать со сковороды хлебом до последней капли.",
      en: "Tender shrimp in a velvety cream sauce with garlic and parmesan. The kind of sauce you'll want to wipe out of the pan with bread to the last drop.",
    },
    ingredients: {
      ru: ["Креветки — 400 г", "Сливки 20% — 200 мл", "Пармезан — 50 г", "Чеснок — 2 зубчика", "Сливочное масло — 20 г", "Соль — по вкусу", "Чёрный перец — по вкусу"],
      en: ["Shrimp — 400 g", "Cream 20% — 200 ml", "Parmesan — 50 g", "Garlic — 2 cloves", "Butter — 20 g", "Salt — to taste", "Black pepper — to taste"],
    },
    steps: {
      ru: ["Обжарьте креветки на масле 1–2 минуты и уберите со сковороды.", "В той же сковороде прогрейте чеснок, влейте сливки и добавьте тёртый пармезан.", "Прогрейте соус до загустения, посолите и поперчите.", "Верните креветки в соус ещё на 1 минуту и подавайте.", "Совет: снимайте креветки заранее, чтобы они не стали резиновыми, пока густеет соус."],
      en: ["Sear the shrimp in butter for 1–2 minutes and remove from the pan.", "In the same pan warm the garlic, pour in the cream and add grated parmesan.", "Simmer the sauce until it thickens, then season.", "Return the shrimp to the sauce for 1 more minute and serve.", "Tip: pull the shrimp early so they don't turn rubbery while the sauce reduces."],
    },
    tags: { ru: ["ужин", "креветки", "сливки", "пармезан"], en: ["dinner", "shrimp", "cream", "parmesan"] },
    createdAt: "2026-08-26T08:10:00Z",
  },
  {
    id: "r-krevetki-hrustyaschie",
    slug: "hrustyaschie-krevetki",
    category: "snack",
    isPp: false,
    image: "/img/recipes/snack.svg",
    minutes: 25,
    calories: 320,
    servings: 3,
    difficulty: "medium",
    title: {
      ru: "Хрустящие креветки в панировке",
      en: "Crispy breaded shrimp",
    },
    description: {
      ru: "Креветки в золотистой панировке из сухарей с паприкой — хрустящие снаружи и сочные внутри. Идеальная закуска под белый соус: макаешь — и пропал.",
      en: "Shrimp in a golden paprika-breadcrumb coating — crunchy outside, juicy within. The ideal dipping snack: one dunk in the white sauce and you're hooked.",
    },
    ingredients: {
      ru: ["Креветки — 400 г", "Яйцо — 1 шт", "Панировочные сухари — 80 г", "Мука — 3 ст. л.", "Паприка — 1 ч. л.", "Соль — по вкусу", "Масло для жарки — по необходимости"],
      en: ["Shrimp — 400 g", "Egg — 1", "Breadcrumbs — 80 g", "Flour — 3 tbsp", "Paprika — 1 tsp", "Salt — to taste", "Oil for frying — as needed"],
    },
    steps: {
      ru: ["Смешайте сухари с паприкой и солью.", "Обваляйте креветки в муке, затем во взбитом яйце и в сухарях.", "Обжарьте во фритюре или на сковороде до золотистой корочки — либо запеките до хруста.", "Обсушите на бумажном полотенце и подавайте с белым соусом.", "Совет: для более лёгкого варианта запеките креветки в духовке при 200 °C, сбрызнув маслом."],
      en: ["Mix the breadcrumbs with paprika and salt.", "Coat the shrimp in flour, then beaten egg, then breadcrumbs.", "Deep-fry or pan-fry until golden — or bake until crisp.", "Drain on paper towel and serve with a white dipping sauce.", "Tip: for a lighter version, bake at 200 °C with a spritz of oil."],
    },
    tags: { ru: ["закуска", "креветки", "хрустящее", "фритюр"], en: ["snack", "shrimp", "crispy", "fried"] },
    createdAt: "2026-08-26T08:15:00Z",
  },
  {
    id: "r-krevetki-kokosovoe-karri",
    slug: "kokosovoe-karri-s-krevetkami",
    category: "main",
    isPp: false,
    image: "/img/recipes/main.svg",
    minutes: 25,
    calories: 360,
    servings: 3,
    difficulty: "easy",
    title: {
      ru: "Кокосовое карри с креветками",
      en: "Coconut shrimp curry",
    },
    description: {
      ru: "Креветки в нежном кокосовом соусе с карри, имбирём и лаймом — пряное, ароматное и совсем не сложное. Подавайте с рассыпчатым рисом.",
      en: "Shrimp in a gentle coconut sauce with curry, ginger and lime — spiced, fragrant and genuinely easy. Serve with fluffy rice.",
    },
    ingredients: {
      ru: ["Креветки — 400 г", "Кокосовое молоко — 250 мл", "Карри — 1 ч. л.", "Чеснок — 2 зубчика", "Имбирь — 1 ч. л.", "Сок лайма — по вкусу", "Кинза — для подачи", "Рис — для подачи"],
      en: ["Shrimp — 400 g", "Coconut milk — 250 ml", "Curry powder — 1 tsp", "Garlic — 2 cloves", "Ginger — 1 tsp", "Lime juice — to taste", "Cilantro — to serve", "Rice — to serve"],
    },
    steps: {
      ru: ["Прогрейте на сковороде измельчённый чеснок, имбирь и карри до аромата.", "Влейте кокосовое молоко и доведите до лёгкого кипения.", "Добавьте креветки и готовьте 3–4 минуты до готовности.", "В конце влейте сок лайма, посыпьте кинзой и подавайте с рисом.", "Совет: не кипятите соус слишком долго — креветки станут жёсткими."],
      en: ["Warm the minced garlic, ginger and curry in a pan until fragrant.", "Pour in the coconut milk and bring to a gentle simmer.", "Add the shrimp and cook 3–4 minutes until done.", "Finish with lime juice, scatter cilantro and serve with rice.", "Tip: don't over-simmer the sauce or the shrimp turn tough."],
    },
    tags: { ru: ["ужин", "креветки", "карри", "кокос"], en: ["dinner", "shrimp", "curry", "coconut"] },
    createdAt: "2026-08-26T08:20:00Z",
  },
  {
    id: "r-krevetki-teriyaki",
    slug: "krevetki-teriyaki",
    category: "main",
    isPp: false,
    image: "/img/recipes/main.svg",
    minutes: 15,
    calories: 280,
    servings: 2,
    difficulty: "easy",
    title: {
      ru: "Креветки терияки",
      en: "Teriyaki shrimp",
    },
    description: {
      ru: "Креветки в блестящей глазури терияки из соевого соуса, мёда, чеснока и имбиря, посыпанные кунжутом. Подайте с рисом — и ужин готов за 15 минут.",
      en: "Shrimp in a shiny teriyaki glaze of soy, honey, garlic and ginger, finished with sesame. Serve over rice and dinner is done in 15 minutes.",
    },
    ingredients: {
      ru: ["Креветки — 400 г", "Соевый соус — 3 ст. л.", "Мёд — 1 ст. л.", "Чеснок — 2 зубчика", "Имбирь — ½ ч. л.", "Кунжут — для подачи", "Зелёный лук — для подачи", "Рис — для подачи"],
      en: ["Shrimp — 400 g", "Soy sauce — 3 tbsp", "Honey — 1 tbsp", "Garlic — 2 cloves", "Ginger — ½ tsp", "Sesame seeds — to serve", "Spring onion — to serve", "Rice — to serve"],
    },
    steps: {
      ru: ["Смешайте соевый соус, мёд, измельчённый чеснок и имбирь.", "Обжарьте креветки на сильном огне 2 минуты.", "Влейте соус и готовьте ещё минуту до красивой блестящей глазури.", "Посыпьте кунжутом и зелёным луком, подавайте с рисом.", "Совет: соус загустеет быстро — снимайте с огня, как только он станет глянцевым."],
      en: ["Mix the soy sauce, honey, minced garlic and ginger.", "Sear the shrimp over high heat for 2 minutes.", "Pour in the sauce and cook another minute to a glossy glaze.", "Scatter with sesame and spring onion and serve with rice.", "Tip: the sauce thickens fast — pull it off the heat as soon as it turns glossy."],
    },
    tags: { ru: ["ужин", "креветки", "терияки", "азиатское"], en: ["dinner", "shrimp", "teriyaki", "asian"] },
    createdAt: "2026-08-26T08:25:00Z",
  },
  {
    id: "r-krevetki-limonno-perechnye",
    slug: "limonno-perechnye-krevetki",
    category: "main",
    isPp: false,
    image: "/img/recipes/main.svg",
    minutes: 10,
    calories: 220,
    servings: 2,
    difficulty: "easy",
    title: {
      ru: "Лимонно-перечные креветки",
      en: "Lemon pepper shrimp",
    },
    description: {
      ru: "Креветки, обжаренные до румяности со сливочным маслом, чесноком, свежемолотым перцем и цедрой лимона. Свежо, сочно и готово за 10 минут.",
      en: "Shrimp seared golden with butter, garlic, cracked pepper and lemon zest. Fresh, juicy and ready in 10 minutes.",
    },
    ingredients: {
      ru: ["Креветки — 400 г", "Сливочное масло — 30 г", "Лимон — 1 шт", "Чеснок — 2 зубчика", "Чёрный перец — по вкусу", "Соль — по вкусу"],
      en: ["Shrimp — 400 g", "Butter — 30 g", "Lemon — 1", "Garlic — 2 cloves", "Black pepper — to taste", "Salt — to taste"],
    },
    steps: {
      ru: ["Обжарьте креветки на сухой разогретой сковороде до румяности.", "Добавьте сливочное масло и измельчённый чеснок.", "Всыпьте свежемолотый чёрный перец, добавьте цедру и сок лимона.", "Посолите, прогрейте ещё несколько секунд и подавайте.", "Совет: перчите свежемолотым перцем прямо в сковороду — аромат будет ярче."],
      en: ["Sear the shrimp on a hot dry pan until golden.", "Add the butter and minced garlic.", "Add freshly cracked black pepper, then lemon zest and juice.", "Season with salt, warm a few more seconds and serve.", "Tip: grind the pepper fresh straight into the pan for a brighter aroma."],
    },
    tags: { ru: ["ужин", "креветки", "лимон", "быстро"], en: ["dinner", "shrimp", "lemon", "quick"] },
    createdAt: "2026-08-26T08:30:00Z",
  },
  {
    id: "r-krevetki-pasta",
    slug: "pasta-s-krevetkami",
    category: "main",
    isPp: false,
    image: "/img/recipes/main.svg",
    minutes: 25,
    calories: 520,
    servings: 2,
    difficulty: "easy",
    title: {
      ru: "Паста с креветками в сливочном соусе",
      en: "Creamy shrimp pasta",
    },
    description: {
      ru: "Спагетти с креветками в сливочном соусе с чесноком и пармезаном — тот самый ужин «как в ресторане», который легко приготовить дома за 25 минут.",
      en: "Spaghetti and shrimp in a creamy garlic-parmesan sauce — that restaurant-style dinner you can make at home in 25 minutes.",
    },
    ingredients: {
      ru: ["Спагетти — 200 г", "Креветки — 300 г", "Сливки — 150 мл", "Пармезан — 40 г", "Чеснок — 2 зубчика", "Сливочное масло — 20 г", "Соль — по вкусу", "Чёрный перец — по вкусу"],
      en: ["Spaghetti — 200 g", "Shrimp — 300 g", "Cream — 150 ml", "Parmesan — 40 g", "Garlic — 2 cloves", "Butter — 20 g", "Salt — to taste", "Black pepper — to taste"],
    },
    steps: {
      ru: ["Отварите спагетти до состояния аль денте и слейте воду, сохранив немного отвара.", "Обжарьте креветки с чесноком на сливочном масле 1–2 минуты.", "Влейте сливки и добавьте тёртый пармезан, прогрейте до загустения.", "Соедините с пастой, при необходимости добавьте немного отвара и прогрейте 1 минуту.", "Совет: ложка воды от пасты сделает соус шелковистым и обволакивающим."],
      en: ["Boil the spaghetti al dente and drain, keeping a little cooking water.", "Sear the shrimp with garlic in butter for 1–2 minutes.", "Pour in the cream and add grated parmesan, simmer until thickened.", "Toss with the pasta, loosen with a splash of the water and warm for 1 minute.", "Tip: a spoon of pasta water makes the sauce silky and clingy."],
    },
    tags: { ru: ["ужин", "креветки", "паста", "сливки"], en: ["dinner", "shrimp", "pasta", "cream"] },
    createdAt: "2026-08-26T08:35:00Z",
  },
];

export const SEED_LIFEHACKS: Lifehack[] = [
  {
    id: "l-herbs",
    slug: "kak-hranit-zelen",
    category: "storage",
    image: "/img/lifehacks/storage.svg",
    title: { ru: "Как хранить зелень две недели", en: "Keep herbs fresh for two weeks" },
    summary: {
      ru: "Простой способ, чтобы петрушка и укроп не желтели через два дня.",
      en: "A simple trick so parsley and dill don't yellow in two days.",
    },
    body: {
      ru: [
        "Обрежьте кончики стеблей и поставьте пучок в стакан с водой, как букет.",
        "Накройте зелень сверху пакетом и уберите в холодильник.",
        "Меняйте воду раз в 2–3 дня — зелень останется свежей до двух недель.",
      ],
      en: [
        "Trim the stem ends and stand the bunch in a glass of water, like flowers.",
        "Cover the tops loosely with a bag and refrigerate.",
        "Change the water every 2–3 days — the herbs stay fresh up to two weeks.",
      ],
    },
    createdAt: "2026-08-01T09:00:00Z",
  },
  {
    id: "l-onion",
    slug: "rezat-luk-bez-slez",
    category: "cooking",
    image: "/img/lifehacks/cooking.svg",
    title: { ru: "Резать лук без слёз", en: "Chop onions without crying" },
    summary: {
      ru: "Три рабочих приёма против жгучих слёз при нарезке лука.",
      en: "Three tricks that actually stop the onion tears.",
    },
    body: {
      ru: [
        "Охладите лук в холодильнике 15 минут перед нарезкой — холод замедляет выделение газа.",
        "Используйте острый нож: он режет клетки, а не давит их.",
        "Не срезайте корневую часть до конца — там больше всего раздражающих веществ.",
      ],
      en: [
        "Chill the onion for 15 minutes first — cold slows the gas release.",
        "Use a sharp knife: it cuts cells instead of crushing them.",
        "Leave the root end intact until last — that's where the irritants concentrate.",
      ],
    },
    createdAt: "2026-08-02T09:00:00Z",
  },
  {
    id: "l-pan",
    slug: "otmyt-prigorevshuyu-skovorodu",
    category: "cleaning",
    image: "/img/lifehacks/cleaning.svg",
    title: { ru: "Отмыть пригоревшую сковороду", en: "Clean a burnt pan" },
    summary: {
      ru: "Без агрессивной химии и часа оттирания — только сода и вода.",
      en: "No harsh chemicals, no hour of scrubbing — just soda and water.",
    },
    body: {
      ru: [
        "Насыпьте на дно 2 ст. л. соды и залейте водой на палец выше нагара.",
        "Доведите до кипения и проварите 10 минут.",
        "Слейте, остудите — нагар отойдёт лопаткой почти без усилий.",
      ],
      en: [
        "Cover the bottom with 2 tbsp of baking soda and add water a finger above the burn.",
        "Bring to a boil and simmer 10 minutes.",
        "Drain, cool — the residue lifts off with a spatula almost effortlessly.",
      ],
    },
    createdAt: "2026-08-03T09:00:00Z",
  },
  {
    id: "l-freeze",
    slug: "zamorozka-produktov-pravilno",
    category: "storage",
    image: "/img/lifehacks/storage.svg",
    title: { ru: "Заморозка продуктов без потерь", en: "Freeze food without waste" },
    summary: {
      ru: "Что и как замораживать, чтобы не выбрасывать испорченное.",
      en: "What to freeze and how, so nothing ends up in the bin.",
    },
    body: {
      ru: [
        "Замораживайте порциями: разложите по пакетам плоским слоем — оттаивает быстрее.",
        "Подписывайте дату: большинство продуктов хранятся 3 месяца без потери качества.",
        "Зелень и травы залейте оливковым маслом в форме для льда — готовая заправка под рукой.",
      ],
      en: [
        "Freeze in portions: lay flat in bags — they thaw faster.",
        "Label the date: most foods keep 3 months without losing quality.",
        "Freeze herbs in olive oil in an ice-cube tray — instant seasoning on demand.",
      ],
    },
    createdAt: "2026-08-04T09:00:00Z",
  },
  {
    id: "l-budget",
    slug: "ekonomit-na-produktah",
    category: "saving",
    image: "/img/lifehacks/saving.svg",
    title: { ru: "Экономить на продуктах без диеты", en: "Save on groceries without dieting" },
    summary: {
      ru: "Пять привычек, которые снижают счёт в магазине на треть.",
      en: "Five habits that cut the grocery bill by a third.",
    },
    body: {
      ru: [
        "Планируйте меню на неделю и покупайте по списку — импульсивные покупки уходят.",
        "Готовьте базовые продукты сами: бульон, хлеб, соусы дешевле домашние.",
        "Используйте сезонные овощи — они дешевле и вкуснее.",
        "Не выбрасывайте остатки: из них получаются супы, запеканки и начинки.",
      ],
      en: [
        "Plan a weekly menu and shop from a list — impulse buys disappear.",
        "Make staples yourself: stock, bread and sauces are cheaper homemade.",
        "Buy seasonal vegetables — cheaper and tastier.",
        "Don't bin leftovers: they become soups, bakes and fillings.",
      ],
    },
    createdAt: "2026-08-05T09:00:00Z",
  },
  {
    id: "l-eggs",
    slug: "proverit-svezhest-yaic",
    category: "cooking",
    image: "/img/lifehacks/cooking.svg",
    title: { ru: "Проверить свежесть яиц за 10 секунд", en: "Check egg freshness in 10 seconds" },
    summary: {
      ru: "Стакан воды скажет о яйце больше, чем срок на упаковке.",
      en: "A glass of water tells you more than the date on the box.",
    },
    body: {
      ru: [
        "Опустите яйцо в стакан с холодной водой.",
        "Лежит на дне — свежее. Встало вертикально — используйте скорее.",
        "Всплыло на поверхность — выбросьте, оно испорчено.",
      ],
      en: [
        "Drop the egg into a glass of cold water.",
        "Lies flat on the bottom — fresh. Stands upright — use it soon.",
        "Floats to the top — throw it out, it's off.",
      ],
    },
    createdAt: "2026-08-06T09:00:00Z",
  },
];
