/*
  Turn recipes into ready-to-paste Supabase SQL (idempotent upserts on `slug`).
  This is the "add recipes via SQL" workflow: write the recipe once (RU + EN),
  run this, paste the output into the Supabase SQL editor. Leave `image` empty
  and attach the photo later from the admin panel.

    npx tsx scripts/export-sql.ts                 # all seed recipes
    npx tsx scripts/export-sql.ts r-onion-rings   # only these ids
    npx tsx scripts/export-sql.ts > out.sql

  It reads lib/data.ts, so the seed content is the single source of truth.
*/
import { SEED_RECIPES } from "../lib/data";
import type { Recipe } from "../lib/types";

// SQL string literal: single quotes doubled.
const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
// jsonb literal from any JS value.
const j = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;

function recipeToSql(r: Recipe): string {
  return `insert into public.recipes
  (slug, category, is_pp, image, minutes, calories, servings, difficulty, title, description, ingredients, steps, tags)
values
  (${q(r.slug)}, ${q(r.category)}, ${r.isPp}, null, ${r.minutes}, ${r.calories}, ${r.servings}, ${q(r.difficulty)},
   ${j(r.title)},
   ${j(r.description)},
   ${j(r.ingredients)},
   ${j(r.steps)},
   ${j(r.tags)})
on conflict (slug) do update set
  category = excluded.category,
  is_pp = excluded.is_pp,
  minutes = excluded.minutes,
  calories = excluded.calories,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  steps = excluded.steps,
  tags = excluded.tags;`;
}

const only = process.argv.slice(2);
const rows = only.length
  ? SEED_RECIPES.filter((r) => only.includes(r.id) || only.includes(r.slug))
  : SEED_RECIPES;

const header = `-- Generated by scripts/export-sql.ts — paste into the Supabase SQL editor.
-- image is left NULL on purpose: attach the photo later from the admin panel
-- (the site shows a category placeholder cover until then).
`;

console.log(header + "\n" + rows.map(recipeToSql).join("\n\n") + "\n");
